### ISSUE TITLE
SSL Cloud9 small problem

### ISSUE THREAD

**Issue by mak1966** [pencilblue/pencilblue#1005]
Hi, 
I tried to install pencilBlue using cloud9 as an IDE.

Every things was ok until I reach the setup step:

Cloud9 uses https protocol, so I configured "siteRoot": "https://workspace-user.c9users.io/",

It worked fine and redirected me to https://workspace-user.c9users.io/setup

I filled the form then clicked submit.

It redirected me to http://workspace-user.c9users.io/actions/setup

Note that it uses the http protocol instead of https.

I searched the code and found that there is a call to getHostWithProtocol function in setup.js that replace https with http.

getHostWithProtocol function exists in the file site_service.js line 562.

In the body of the function, I found the following:

urlObject.protocol = pb.config.server.ssl.enabled ? 'https' : 'http';

So I added the following to the config.js:
    server: {
        ssl: {
            enabled: true
        }
    },

It did not work.

I replaced it with:

    server: {
        ssl: {
            use_x_forwarded: true
        }
    },

and changed the 
urlObject.protocol = pb.config.server.ssl.enabled ? 'https' : 'http';
to
urlObject.protocol = pb.config.server.ssl.use_x_forwarded ? 'https' : 'http';

It worked.

Any idea if this is a bug?, or I did something wrong? 
I am a DotNet developer and nodejs + pencelBlue are too new to me. :)

Thanks

**Comment by brianhyder** [comment]
We've only had one other report of somebody using cloud 9 with PB.  They were having issues with ports  (#956) which doesn't sound like it applies to you.  

My guess is that cloud 9 does ssl termination at the load balancer.  You can probably set ```server.ssl.enabled = false``` in your config but leave ```server.ssl.use_x_forwarded = true```.  We honestly haven't tried to setup PB in cloud 9.  The majority of our users run local IDEs or editors.

**Comment by brianhyder** [comment]
@mak1966 I tested this out on an instance in cloud 9.  The following configuration worked without issue:

config.js
```
module.exports = {
  siteRoot: "https://workspace-user.c9users.io:8081",
  sitePort: 8081,
  db: {
      name: "dbname",
      servers: [
        "some.mongo.server:74829"    
      ],
      authentication: {
          un: "someuser",
          pw: "somepassword"
      }
  },
  server: {
      ssl: {
          enabled: false,
          use_x_forwarded_for: false
      }
  },
  cluster: {
      self_managed: false
  }
};
```
