### ISSUE TITLE
Point article to a custom object

### ISSUE THREAD

**Issue by larskarbo** [pencilblue/pencilblue#1008]
I need to add some extra data to an article. How can I do that?

I have created a custom object with the properties I need, and my idea is to link the article and the custom object.

I know the portfolio plugin is doing something similar with the hero image, but I don't fully understand it.
````

//setup for custom fields on page objects (hero_image)
pb.BaseObjectService.on('page' + '.' + pb.BaseObjectService.FORMAT, function(context, cb) {
    var dto = context.data;
    dto.hero_image = pb.BaseObjectService.sanitize(dto.hero_image);
    
    cb(null);
});
pb.BaseObjectService.on('page' + '.' + pb.BaseObjectService.MERGE, function(context, cb) {
    var dto = context.data;
    var obj = context.object;

    obj.hero_image = dto.hero_image;
    
    cb(null);
});
pb.BaseObjectService.on('page' + '.' + pb.BaseObjectService.VALIDATE, function(context, cb) {
    var obj = context.data;
    var errors = context.validationErrors;
    
    if (!pb.ValidationService.isUrl(obj.hero_image, false)) {
        errors.push(pb.BaseObjectService.validationFailure('hero_image', 'Hero image must be a valid URL or media path'));
    }
    
    cb(null);
});
````

**Comment by brianhyder** [comment]
The plugin is utilizing the ability to "listen" for events of a given object type.  The early versions of PB allowed for you to pass in extra fields and they would just flow through to the DB.  This was a very unsecure practice.  

Now, we have introduced the BaseObjectService.  It is the base prototype that is extended by other collection types (ArticleServiceV2, PageService, TopicService, UserService, etc.).  It allows for plugins and other pieces of code to interact with the CRUD operations of objects.

What the portfolio plugin is doing is allowing for the supplementary field ```hero_image``` to be formatted, merged, and validated.

About the events:

* FORMAT - Allows for the sanitization of the incoming fields.  It allows developers to add, sanitize, or remove unwanted fields before the MERGE.
* MERGE - The event that provides the already persisted object on update or a new object to be persisted on create for moving the values that were provided in the request to the object that will be saved to the DB.  This allows for you data model to be different than your outgoing model.  This is handy if you have computed fields or want to remove sensitive data that shouldn't be persisted or sent back out over the wire (user password hashes).  
* VALIDATE - The event that fires after the merge but before persistence.  It is meant to validate the fields on an object.  In the case above, the ArticleServiceV2 handles the validations for the default article fields.  The code provided by the portfolio plugin listens for the validate event to provide validations for the one extra field that it is responsible for.

Hopefully, that provides a bit of clarify.  Let me know if there are any other questions I can answer.

**Comment by brianhyder** [comment]
The downside to using the custom objects is that it would require an additional DB call to get the extra information.  If you use the BaseObjectService it will attach the extra data directly to the article object.
