### ISSUE TITLE
Error when updated an topic

### ISSUE THREAD

**Issue by diana-silva** [pencilblue/pencilblue#1012]
I am using plugin portfolio (version 0.5.1) and when i try update an topic, Is always updated the first topic.
E.g:
1º Create two topics ("topic01", "topic02");
2ª When click in topic02 for updating the name and click in save the name of  first topic is changed for topic02.

Someone can you help me ?
cheers !

**Comment by brianhyder** [comment]
@diana-silva Thank you for reporting.  I saw your message in gitter and plan to take a look at it over the weekend.  Would you mind confirming if this issue is occurring in the default theme too?

**Comment by diana-silva** [comment]
Hi,

Yes also in the default theme.

**Comment by brianhyder** [comment]
@diana-silva thanks again for reporting the bug.  It has bee fixed and merged to master
