### ISSUE TITLE
how to customize css, html in pencilblue

### ISSUE THREAD

**Issue by ramireddypingala** [pencilblue/pencilblue#1014]
I am using pencilblue  now i am trying to customize the css/html file.

**Comment by rubennleonardoo** [comment]
Hi, try in directory: your_project/public/css/pencilblue_theme.css

**Comment by ramireddypingala** [comment]
no changes effecting.

**Comment by rubennleonardoo** [comment]
which plugin you have installed ?

**Comment by ramireddypingala** [comment]
jennifer. And I applied for portfolio theme also it is not working.

**Comment by rubennleonardoo** [comment]
so, if you have installed jennifer you have apply jennifer theme and edit css files of this theme

**Comment by ramireddypingala** [comment]
I applied Jennifer theme and i edited the css file from the path of  \plugins\jennifer-master\public\css, but no changes effected.

**Comment by brianhyder** [comment]
The folder name that contains the contents of the plugin must match the
plugin uid located in the details.json file

**Comment by ramireddypingala** [comment]
Already i have given same as you told.

**Comment by ramireddypingala** [comment]
Please can anyone tell me the process that how to change css for a particular theme.

**Comment by blakecallens** [comment]
Please read through the [quickstart guide](https://github.com/pencilblue/pencilblue/wiki/Quickstart%20Guide) before posting any issues.

**Comment by yasirrafiq33** [comment]
I follow the complete video to change my theme but still css doesn't have any effect.
Kindly guide me above all answers are applied but still no effect.
