### ISSUE TITLE
Can anyone explain the below where to replace and how?

### ISSUE THREAD

**Issue by ramireddypingala** [pencilblue/pencilblue#1018]
You'll notice a few new directives being used, here's what they'll get replaced with:

^bootstrap_css_src^ the url for Bootstrap's CSS (CDN, Bower, or custom)
^jquery_src^ the url for the jQuery library
^bootstrap_js_src the url for Bootstrap's JavaScript
^landing_page_headline^ we'll make this load our headline setting
^landing_page_subheader^ we'll make this load our subheader setting

**Comment by brianhyder** [comment]
The flags that already exist such as the ```^bootstrap_css_src^``` have handlers registered with the TemplateService by default.  Those custom ones that you mention can either be registered on a per controller basis or globally.  The sample plugin demonstrates how to register flags on a per controller basis.  https://github.com/pencilblue/pencilblue/blob/master/plugins/sample/controllers/random_text_view.js#L97

There are also method that allow you to register on a global basis:
http://pencilblue.github.io/classes/TemplateService.html#method_registerGlobal

Your flags can then be placed in your html templates.

**Comment by laomagege** [comment]
But where is the code in TemplateService to register the "^bootstrap_css_src^", "^bootstrap_js_src"? Would you mind help point out, appreciated in advance.
