### ISSUE TITLE
Bug when close alerts.

### ISSUE THREAD

**Issue by diana-silva** [pencilblue/pencilblue#1019]
Hello!
I found that an error occurs when we close the alerts (by clicking the X) of creation, edition or deletion of any item (Pages, topics, ...).

If they can investigate the situation.

Thanks again for your help.
:)

**Comment by brianhyder** [comment]
Please follow our guidelines for submitting issues located on our Readme under "submitting issues". This helps us to be more efficient at diagnosing, prioritizing and fixing incoming issues.
