### ISSUE TITLE
Is node.js knowledge required to develop custom plugins and themes in PencilBlue cms framework.

### ISSUE THREAD

**Issue by ramireddypingala** [pencilblue/pencilblue#1022]

**Comment by blakecallens** [comment]
Node.js is a knowledge requirement to work with the platform, yes.

You can give WebStorm a try, for an Eclipse like feel.

Please go through the [Quickstart Guide](https://github.com/pencilblue/pencilblue/wiki/Quickstart%20Guide) and (watch the theme developement video)[https://www.youtube.com/watch?v=-5k1zePdgC4] before asking questions on theme development.
