### ISSUE TITLE
customization of plugins/themes

### ISSUE THREAD

**Issue by ramireddypingala** [pencilblue/pencilblue#1023]
We are envisaging and doing r&d for porting of a public website done earlier on HTML5, onto pencilblue framework in view of the advantages pencilblue cms offers. Here we are taking the standard Themes or plugins provided by PencilBlue and trying to change the CSS or HTML or JS, however there is no success in this approach. Please advice if this approach is wrong or do we need to create a fresh theme and use the same for website.

**Comment by blakecallens** [comment]
Rolling under #1022. Please keep our issue queue clean by rolling multiple tech questions under one issue.
