### ISSUE TITLE
Error while running pencilblue in cmd

### ISSUE THREAD

**Issue by ramireddypingala** [pencilblue/pencilblue#1025]
![pb error](https://cloud.githubusercontent.com/assets/18442142/15005410/b83010ea-11e1-11e6-9c56-d42a597b6818.PNG)

**Comment by dukeofsussex** [comment]
Is this error occurring for a clean PB installation or have you made modifications?

**Comment by brianhyder** [comment]
Please verify that you are using a supported version of Node.js.  They are listed on our README
