### ISSUE TITLE
I uninstall my pencilblue, Mongodb and nodejs but my previous data is not deleting

### ISSUE THREAD

**Issue by ramireddypingala** [pencilblue/pencilblue#1026]
I uninstall the pencilblue and again i reinstall the nodejs , mongoDB, git, and pencilblue. But when I open the localhost:8080 my previous pages are opening. Now I want to delet the previous data and want to do freshly. how to do can anyone help me please. Thank you.

**Comment by brianhyder** [comment]
It appears that your mongoDB database is still hanging around you will need to delete it or change the DB name in your config.js file.
