### ISSUE TITLE
How to add more content in a page

### ISSUE THREAD

**Issue by Jobbyr** [pencilblue/pencilblue#1029]
After I login to the admin of pencilblue and then on adding a new page and in the content part of the page I am able to add contents but it has a limit. if I add more data there it breaks, any solution to extend the limit of data that I can add in the content part.

PencilBlue Version: 0.5.1
Environment Description: Windows 8

**Comment by brianhyder** [comment]
To clarify, are you having issues with the numbers of characters that you can enter into the wysiwyg field or the type of content that can be entered?

**Comment by Jobbyr** [comment]
yes in wysiwyg field when I go to html area and type the html code It get struck and somehow I am able to save, but again if I reopen the page in admin I cant see anything in the content portion it just hangs.

![struck1](https://cloud.githubusercontent.com/assets/18713830/15099428/874f7490-1572-11e6-8c33-90eb4b98133d.jpg)

**Comment by brianhyder** [comment]
Woukd you mind providing the hotel that you are entering into the content
field?

**Comment by Jobbyr** [comment]
After adding html I get an error message now as post limit reached maximum of 1mb.
![test](https://cloud.githubusercontent.com/assets/18713830/15113056/a2437ede-160f-11e6-8b88-4c7e39a4d838.jpg)

**Comment by brianhyder** [comment]
Awesome, thank you for the clarification.  We limit the amount of data that can be uploaded for form posts.  At the moment this is not configurable.  It has a hard 1MB limit.  This should be configurable and probably bumped to 2MB instead of 1.  In the meantime, you can modify this line:
https://github.com/pencilblue/pencilblue/blob/9a1eb601567decb3017e304721b12e20d2483510/include/http/parsers/index.js#L84 and it will allow you to bypass the limit.

1MB of HTML is a lot of HTML. I would consider building custom routes and pages with sub-templates to break it up a bit.

**Comment by brianhyder** [comment]
@Jobbyr The ability to set the limit is about to be merged to the 0.6.0 branch.  All you will have to do is set the media.max_upload_size property in your config.js file.  The new limit will default to 2MB.

**Comment by Jobbyr** [comment]
Thanks for your Help.!!

How ever I see it get struck when I add these code

  <div class="col s12 l6">
                            <h4 class="p-b-20">Client <span> Says</span></h4>
                            <div class="black-text margin-top-5">
                                <ul id="testimonialSlider" class="row">
                                    <li>
                                        <div class="in-box">
                                            <div class="white-box">
                                                <p class="m-t-none"> "test message."
                                                <p>
                                            </div>
                                        </div>
                                        <img src="images/clients-says/test.jpg" alt="test" />
                                        <p>
                                            <strong>
                                                test name,  CEO<br />
                                                <span>test.com</span>
                                            </strong>
                                        </p>
                                    </li>
                                    <li>
                                        <div class="in-box">
                                            <div class="white-box">
                                                <p class="m-t-none"> "test message"
                                                <p>
                                            </div>
                                        </div>
                                        <img src="images/clients-says/test.jpg" alt="test" />
                                        <p>
                                            <strong>
                                                testname,  Project Manager<br />
                                                <span>test</span>
                                            </strong>
                                        </p>
                                    </li>
                                    <li>
                                        <div class="in-box">
                                            <div class="white-box">
                                                <p class="m-t-none"> "test message"
                                                <p>
                                            </div>
                                        </div>
                                        <img src="images/clients-says/test.jpg" alt="test" />
                                        <p>
                                            <strong>
                                                test name,  Professor<br />
                                                <span>test</span>
                                            </strong>
                                        </p>
                                    </li>
                                </ul>
                            </div>
                        </div>

![struck1](https://cloud.githubusercontent.com/assets/18713830/15149166/24241c5c-16e6-11e6-92d2-1d737db4709e.jpg)

**Comment by Jobbyr** [comment]
[test.txt](https://github.com/pencilblue/pencilblue/files/257345/test.txt)
