### ISSUE TITLE
themes howto-guide

### ISSUE THREAD

**Issue by awb99** [pencilblue/pencilblue#1039]
**Description:**
I am investigating into pencilblue for a small project. The technology for sure is super. But at some stage, I believe we need to hire front end developers to make us a nice theme. Is there any guideline how to do this? This would be really good, because possibly many people would be interested to convert their wordpress templates to pecilblue...

**Comment by brianhyder** [comment]
I would start here.  https://github.com/pencilblue/pencilblue/wiki/Quickstart:-Developing-Themes

If you are interested in recommendations for PB developer partners please send a request through our contact form on our website.

**Comment by brianhyder** [comment]
Additionally, while there is no migration tool for themes there is a tool for importing data from WP.  This plugin ships with each distribution of PB

**Comment by awb99** [comment]
@brianhyder thank you so much!
