### ISSUE TITLE
Rangy cdn returns 404

### ISSUE THREAD

**Issue by nikarc** [pencilblue/pencilblue#1040]
**Description:**
Both `/admin/content/pages/new` and `/admin/content/articles/new` are calling a library called Rangy that is returning a 404. It seems their google cdn is down.

**Steps to Reproduce:**
visit `/admin/content/pages/new` or `/admin/content/articles/new`
![screen shot 2016-05-12 at 5 00 20 pm](https://cloud.githubusercontent.com/assets/3580396/15230361/413bae3a-1863-11e6-9bd1-5ce3b129705f.png)

**Log Output:**
```
Failed to load resource: the server responded with a status of 404 (Not Found)    http://rangy.googlecode.com/svn/trunk/currentrelease/rangy-core.js
Failed to load resource: the server responded with a status of 404 (Not Found)    http://rangy.googlecode.com/svn/trunk/currentrelease/rangy-selectionsaverestore.js
ReferenceError: rangy is not defined
    at link (http://localhost:8080/js/angular/directives/wysiwyg.js:372:9)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:62:364
    at J (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:52:492)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:59:302
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:70:373
    at H (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:97:5)
    at H (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:97:5)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:98:173
    at h.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:108:40)
    at h.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:105:331) <div layout="layout" media="page.page_media" class="ng-isolate-scope">
```

PencilBlue Version: 0.5.1

Node.js Version: 5.9.0

Environment Description:
OSX, chrome canary

**Comment by brianhyder** [comment]
As a workaround you can run a bower install from the project directory.
Then in the libraries section you can switch to bower.

**Comment by blakecallens** [comment]
Looks like they shut down that CDN endpoint. Putting in the pull request for a hotfix.

**Comment by brianhyder** [comment]
@nikarc The fix has been merged.  You will need to repopulate and save your CDN settings in order to take effect.

**Comment by nikarc** [comment]
@brianhyder Cool, thanks!
