### ISSUE TITLE
validation failure when adding articles or pages

### ISSUE THREAD

**Issue by awb99** [pencilblue/pencilblue#1043]
**Description:**
When trying to save  new article or a new page, message pops up saying validation failure. It is not possible to add any new page or article.

**Steps to Reproduce:**

**Configuration Details:** pecilblue on brand new debian jessie, with ARM.
user language is german or english. Bower components have not been installed.

**Log Output:**
No entry in the log; the console logs 
```
isCreate:true
isCreate:false
```
I am not sure, if this when true and when false is being logged.

PencilBlue Version:  latest

Node.js Version: latest

Environment Description: ARM

**Comment by awb99** [comment]
I had some kerberos warnings on install; I dont think it is relevant though
```
> kerberos@0.0.21 install /data/rutadecenotes/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/data/rutadecenotes/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
../lib/kerberosgss.c:36:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic push
 ^
../lib/kerberosgss.c:37:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic ignored "-Wdeprecated-declarations"
 ^
../lib/kerberosgss.c: In function ‘authenticate_gss_client_wrap’:
../lib/kerberosgss.c:446:19: warning: variable ‘server_conf_flags’ set but not used [-Wunused-but-set-variable]
   char buf[4096], server_conf_flags;
                   ^
../lib/kerberosgss.c: At top level:
../lib/kerberosgss.c:1236:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic pop
 ^
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
  COPY Release/kerberos.node
make: Leaving directory '/data/rutadecenotes/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
http-status-codes@1.0.6 node_modules/http-status-codes
```

**Comment by awb99** [comment]
The same error also occurs on ARCH linux.

**Comment by awb99** [comment]
When I try to do the same with a normal user, I get
```
ReferenceError: where is not defined
    at ManageArticles.render (/home/hoertlehner/Documents/pencilblue/plugins/pencilblue/controllers/admin/content/articles/manage_articles.js:36:13)
    at /home/hoertlehner/Documents/pencilblue/include/http/request_handler.js:1148:79
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by awb99** [comment]
I debbugged the front end issue. 
The error comes from the server. The post sends back a Error...

```
 // Save a new page
                    $http.post('/api/content/pages', pageData)
                    .success(function(result) {
                        $scope.successMessage = pageData.headline + ' ' + loc.admin.CREATED;
                        $scope.saving = false;
                        $window.location = '/admin/content/pages/' + result._id.toString();
                    })
                    .error(function(error, status) {
                        $scope.errorMessage = error.message;
                        $scope.saving = false;
                    });

```

**Comment by awb99** [comment]
the error must occur in
page_service.js   -> cb (null)

**Comment by ramireddypingala** [comment]
I too have the same issue  you told that page_service.js -->cb (null). what modification want to do in this file? Can you help me if it is solved for you..

**Comment by awb99** [comment]
@ramireddypinga: I am having issues, in running the debugger with pencilblue, so currently I dont know.

**Comment by awb99** [comment]
ok,  I am a little further:

The error is in base_object_service:
```
 //check for validation errors
                    var validationErrors = BaseObjectService.consolidateValidationResults(context.validationErrors);
                    if (validationErrors.length) {
                        return cb(BaseObjectService.validationError(validationErrors));
                    }
```
The error that I see in there is:
code: null
field: "page_layout"
message: "The layout is required"

**Comment by blakecallens** [comment]
Are you using CDNs for your JS? If so, pull the latest master branch then
go to the libraries screen in the admin section and reset the fields. This
could be related to #1040.

**Comment by awb99** [comment]
i have commented out this lines; now it is saving.

//        if (!ValidationService.isNonEmptyStr(obj.page_layout, true)) {                                                                                                                   
//            errors.push(BaseObjectService.validationFailure('page_layout', 'The layout is required'));                                                                                   
//        }

**Comment by awb99** [comment]
It is the same error. 
How do I change to a local version?

**Comment by blakecallens** [comment]
You can run a bower install and then switch the libraries over.

**Comment by awb99** [comment]
@blakecallens   What do you mean with "reset the fields"?
I broke it by just chaging on the admin settings from CDN to bower.

**Comment by brianhyder** [comment]
Pull the latest from master. Go to the admin section. Under settings in the admin section click on the libraries section.  Change from CDN to bower save, the change back to CDN and save. That should cause the bad rangy URI to be changed

**Comment by brianhyder** [comment]
Relates to #1040
