### ISSUE TITLE
while inserting media  in articles i am getting the below issue in log file.

### ISSUE THREAD

**Issue by ramireddypingala** [pencilblue/pencilblue#1044]
**Description:**

insert media is not responding while adding articles.

**Log Output:**

![pb2](https://cloud.githubusercontent.com/assets/18442142/15243024/e9620f6a-1916-11e6-90fc-83a843904251.PNG)

PencilBlue Version: latest

Node.js Version: latest

Environment Description:

**Comment by brianhyder** [comment]
Have you pulled the latest from master to fix the change to the rangy CDN?

**Comment by brianhyder** [comment]
This most likely a duplicate of #1040 and fixed in master

**Comment by blakecallens** [comment]
Confirmed rangy issue. If you don't want to upgrade, you can use bower or point the rangy libraries to cdnjs versions.
