### ISSUE TITLE
domain name config question

### ISSUE THREAD

**Issue by awb99** [pencilblue/pencilblue#1046]
I have an ip address as sitename.
```
module.exports = {
    "siteName": "My PencilBlue Site",
    "siteRoot": "163.172.143.20",
    "sitePort": 80,
```

When I access it remotely, I get  this error:
The host (163.172.143.20) has not been registered with a site. In single site mode, you must use your site root (163.172.143.20).

**Comment by awb99** [comment]
When I changed to bower,, it would start to work. However, only for IP adresses. For domain names still it would not work. Ths is the error in the webbrowser:
```
The host (www.rutadecenotes.com) has not been registered with a site. In single site mode, you must use your site root (http://rutadecenotes.com).
```

**Comment by brianhyder** [comment]
I _think_ The site root should be prefixed with ```http://``` or ```https://```.  Does that make a difference for you?

**Comment by awb99** [comment]
@brian  you are right.  The prefixes are important.  I believe that pencil blue is way to strict in this regard.  

I waisted a full day in playing around with different options how to register my site.

When I read the error messages I read then as "you entered mydomain.com  but this pencil blue site only supports mydomain.com.  So I thought this is a joke... 

After some reading -  and most importantly some very fast and good replies here in git -  it became clear that one time it was" www." and in the browser I forgot that.  

I would assume that everyone who tries pb out would wil start by running pb for a single site.  So perhaps you guys want to add a parameter single_site_only_catch_all_domains to make it easier for people to get started. 

I think I had bad luck in trying put pb when does of the CDN references went down..  But the confusion over the simple issues with the domain name is home made. 

I want to stress out this point especially since the whole startup process reallyworks smoothly (starting the first time..  Automatically registering the Admin user...  All this was really smooth).  And the  you have this really unusual blocking of answering http requests.... 

So my ideas are:
1. Make a stupid new user setting to accept all traffic. 
2. Do a regex to accept www. Also if it is is not registered explicitly.  If there is a second JSON entry to define a www.mydomail.com and a mydomain.com. Then you don't do the aromatic regex expansion. 
3. In the website error message put some examples that could go wrong and explain how pb accepts traffic.
