### ISSUE TITLE
Question: page vs article and tag-lists

### ISSUE THREAD

**Issue by awb99** [pencilblue/pencilblue#1047]
I am trying to understand what is a page vs.  What is an article. Perhaps I am just stupid or I don't know too much  how WordPress or other cms handle it. 

I understand the following: Articles are displayed in a list possibly with  infiniscroll vs pages are only displayed entirely. And then I guess the styling can be done differently for both. And also a article has an author vs a page has not.  

When I would go and do my own plug in then the whole question page vs article would get irrelevant as all that would count is a route which would need nothing from page nor from article. 

What I don't understand is how to display lists of articles.

How can I display all articles that have a specific tag? 

How do I layout a list of custom class?

**Comment by blakecallens** [comment]
Your correct about what a page vs article is. For answers to your questions check out the Jennifer theme.
