### ISSUE TITLE
Ideas for pencil blue 

### ISSUE THREAD

**Issue by awb99** [pencilblue/pencilblue#1048]
First I have to stress that it is really amazing what you  2 guys have achieved in one year! I totally agree to your assessment that WordPress and others are built on horrible old technology and nobody should start with old technology for new projects. 

Comments: I "only"  took 2 days to evaluate which technology to use for a new project of mine and I spent one day with looking at all options and one day playing with pencil blue. So I might miss out some things. But nevertheless I want to provide some feedback. 

1. Your target audience are users / site builders.  They are not developers. I know you need to attract developers to get the whole ecosystem going.  But you have to cater to the user group.  Right now all your documentation on github,  your  twitter feed and your YouTube videos are targeted towards developmers.  You should clearly make a section for users and one for developers.  Perhaps even a 2 developers: designers (who would do only themes)  and developers who would do plug-ins.  The reason for this is simple: learning curve.  

2. Demo data. I was really impressed with the speed of pencil blue (pages come up lightening fast so it is a joy to work with) and the clean design of the Admin interface.  But I was not able to make my own prototype good enough so that I could at least show it to a Co worker.  With wordpress any idiot can do this in  2 minutes.  Furthermore one only learns with playing with stuff..  And it is easier to start to modify an existing site than to make a new one. You guys did do a cool technology but it does not matter how good the technology is when you don't get users. 

3. What us pencil blue?  This is a good one.  You think you are a modern wordpress  / typo 3?  Yes but this is not the point.  I look at it more like a developer tool.  Like meteor or like open erp (they have a new name which I forgot)  You focus on making custom classes in the gui.  Meteor focuses on making client side db be equal to server side db.  And openERP allows to do custom classes (inclusive of a really nice query and edit engine and permission in system).  So what would be the niche of pb?  I think it is the maintenance really. Sites can be created by users and extended by developers. But maintenance always is with the users. This is a key advantage. And the benefit relative to a MEAN app with scaffolding tool is also the extensibility by users. Having looked at some of our MEAN projects in the past  which have become quite difficult to maintain / extend due to changes in developers I this this is another pb advantage: you mainly use the out of the box framework and then only very small plug-ins need to be custom made. This has huge implications also for maintenance.  Instead of 90% custom boilerplate one only has 10% custom boilerplate. Hurray!  

I hope this comments are helpful to you guys.

**Comment by blakecallens** [comment]
Thanks for the feedback. To get a sense of where we're see the platform going, check out [this blog post](https://pencilblue.org/article/the-state-of-pencilblue-112015).
