### ISSUE TITLE
Bug: android drag drop of tags not working 

### ISSUE THREAD

**Issue by awb99** [pencilblue/pencilblue#1049]
**Description:**
On Android device with chrome browser the drag-drop of tags that pb has in page and article does not work. 

**Configuration Details:**
Samsung Galaxy 5 with latest update. 

PencilBlue Version: latest 
Node.js Version: latest

**Comment by blakecallens** [comment]
Confirmed drag and drop working. You have to touch the hamburger icon. We're removing this type of drag and drop in 0.6.0, so I'm going to close this issue.

**Comment by awb99** [comment]
I did play around with it some more time. You are right - it works. But only sometimes. When one press too long on the "button", then it selects the text, and dragging does not work. When one only quickly swipes over it, then it has not yet entered the drag/drop mode. I was not able to consistently do the drag-drop.
