### ISSUE TITLE
feature-request access rights (by tag?)

### ISSUE THREAD

**Issue by awb99** [pencilblue/pencilblue#1050]
I think it would make sense to somehow make access rights to view articles/pages  for specific user groups. 

So say you add tags to users, then they could not or could access articles depending on the tag.

**Comment by blakecallens** [comment]
@brianhyder, this will be part of custom roles, right?

**Comment by brianhyder** [comment]
We would most likely provide the ability to do that via plugin but I doubt we would target that as a first pass.
