### ISSUE TITLE
word-press  web-site shift to pencil blue Issues.

### ISSUE THREAD

**Issue by yasirrafiq33** [pencilblue/pencilblue#1065]
@blakecallens @tic2000 @mhussa @ulai @chonghua 
**Description:**
If I import all content from WP then what about the theme that is already running on WP-online> So I want same theme. what I have to do?
**Steps to Reproduce:**

**Configuration Details:**

**Log Output:**

PencilBlue Version: 

Node.js Version:

Environment Description:

**Comment by brianhyder** [comment]
We do not support the migration of themes.
