### ISSUE TITLE
Unable to delete custom objects by type

### ISSUE THREAD

**Issue by dukeofsussex** [pencilblue/pencilblue#1066]
**Description:**

Here's a short code snippet to explain my problem:
```
var cos = new pb.CustomObjectService();
cos.loadTypeByName('background_images', function (err, bgImagesType) {
  if (err) {
    return callback(err);
  }
  cos.deleteForType(bgImagesType, function (err, result) {
    if (err) {
      return callback(err);
    }
    pb.log.info('Cleared background images database');
    ...
  });
});
```
For some reason `deleteForType` doesn't remove all objects with the `background_images` type. I also don't get any errors, the passed type is correct and the custom objects all have the correct type assigned. Did I misunderstand the functionality of this function?

PencilBlue Version: 0.5.1

Node.js Version: 4.4.3

Environment Description: Windows, Dev

**Comment by brianhyder** [comment]
This is a bug.  The function allows for the type object or the string representation of the ID to be passed.  In this particular case, there is a bug that does not properly access the ```_id``` property of the object before calling ```.toString()```.

**Comment by brianhyder** [comment]
The workaround is once you retrieve the type you should pass the string ID instead of the object.

```
var cos = new pb.CustomObjectService();
cos.loadTypeByName('background_images', function (err, bgImagesType) {
  if (err) {
    return callback(err);
  }
  cos.deleteForType(bgImagesType._id, function (err, result) {
    if (err) {
      return callback(err);
    }
    pb.log.info('Cleared background images database');
    ...
  });
});
```

**Comment by dukeofsussex** [comment]
Thanks @brianhyder :+1:
