### ISSUE TITLE
Page show as home

### ISSUE THREAD

**Issue by yasirrafiq33** [pencilblue/pencilblue#1070]
@blakecallens @ulai @chonghua @tic2000 @mhussa 
When I hit the url localhost:8080 I see the first article that present in articles tab(in admin). I want to see the first page from pages tab(in admin).  Can you suggest something?

**Comment by brianhyder** [comment]
Your plugin/theme must override the root route and load the content from the page just as the page controller does.

**Comment by yasirrafiq33** [comment]
Hello thanks for your reply can you give me a little demo I didn't get the actual solution.As from the route controller on '/' call you assign a blog.js which return the article. How can I return page except article?
