### ISSUE TITLE
CDN - Bower version mismatch

### ISSUE THREAD

**Issue by dukeofsussex** [pencilblue/pencilblue#1074]
**Description:**
The CDN and bower versions of the some libraries differ. Nothing major, just a minor nuisance, which can cause confusion when going live and stuff breaks

**Steps to Reproduce:**
Clean PB install

PencilBlue Version: 0.5.1

Node.js Version: 4.4.5

Environment Description: Win, Dev

**Comment by brianhyder** [comment]
@blakecallens can you try and track this one down?

**Comment by blakecallens** [comment]
I'll take this on as part of 0.7.0
