### ISSUE TITLE
301 Redirect

### ISSUE THREAD

**Issue by yasirrafiq33** [pencilblue/pencilblue#1075]
Hi,
We're moving a wordpress site to pencilblue and need 301 redirects. In request handler I'm a bit confused where to put in this logic. Need a suggestion.

**Comment by brianhyder** [comment]
Two options.  You can use the logic as show in the sample plugin: https://github.com/pencilblue/pencilblue/blob/master/plugins/sample/controllers/random_text_view.js#L245

or you can build your own redirect via something like the code shown below.  This code would exist in a controller for a specific route.

```
SomeController.prototype.someRouteHandler = function(cb) {
  
  //do redirect the manual way to Google
  var result = {
    headers: {
      location: 'http://google.com'
    },
    code: 301
  };
  cb(result);
};
```

**Comment by yasirrafiq33** [comment]
I used the doRedirect methode that provide in Requesr.handler is that fine
or not?
