### ISSUE TITLE
Custom Page

### ISSUE THREAD

**Issue by yasirrafiq33** [pencilblue/pencilblue#1077]
Hello,
I want to make custom page like own css and scripts handle animation in page. If I provide div-id in editor then editor not save id in data-base.
I have one div with id because with this id I am manipulating div content.I need help in this sense how can I make custom page?

@blakecallens @brianhyder @mhussa @tic2000 @chonghua @ulai

**Comment by brianhyder** [comment]
The wysiwyg only supports a limited number of elements and attributes.  For more custom pages please read the wiki or watch the tutorial video on building themes.  Additionally, you can look at the source for other plugins such as portfolio to see how other plugins accomplish this custom behavior.

**Comment by yasirrafiq33** [comment]
I just want to implement css and script file on one page that I make from
admin panel page section.
But when I insert id in div this Id miss when you save the page in database.
This is what I am asking how I can apply css script on page?
On Jun 21, 2016 7:45 PM, "Brian" <notifications@github.com> wrote:

The wysiwyg only supports a limited number of elements and attributes. For
more custom pages please read the wiki or watch the tutorial video on
building themes. Additionally, you can look at the source for other plugins
such as portfolio to see how other plugins accomplish this custom behavior.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pencilblue/pencilblue/issues/1077#issuecomment-227462577>,
or mute the thread
<https://github.com/notifications/unsubscribe/AKvvxRmPAtcZzZ-0yKDUoXwI8DMBvogzks5qN_jxgaJpZM4I6abE>
.
