### ISSUE TITLE
Get image path from mediaid

### ISSUE THREAD

**Issue by larskarbo** [pencilblue/pencilblue#1079]
I have created a custom object with some properties containing images.

When retrieving the object, the images are media ids. For example: "576c05c39c7dd0da67f92542"

How can I get the image path from the media id?

(I have looked at ImageMediaRenderer, but can't figure out how it works)

**Comment by brianhyder** [comment]
If you are using version 0.5.1 then you will want to use [MediaService](http://pencilblue.github.io/classes/MediaService.html).  However, next week, we will be releasing 0.6.0 which deprecates the MediaService in favor of [MediaServiceV2](https://github.com/pencilblue/pencilblue/blob/0.6.0/include/service/entities/content/media_service_v2.js).

Either way you can use ```get``` method in MediaService or ```getAll``` in MediaServiceV2.  You will want to build an "in" query ```var options = {}; options.where = pb.DAO.getIdInWhere(arrayOfMediaIds);```.

**Comment by larskarbo** [comment]
Thanks, it works! 

Im exited to test v 0.6.0. Keep up the good work!
