### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ceballos59** [pencilblue/pencilblue#1082]
**Description:**

BUG

**Steps to Reproduce:**

setup  navigation, include a session...
reorder navegation submenu at the site view.

at the screen:

MongoError: bad sort specification
    at Function.MongoError.create (D:\meanproject\today\node_modules\mongodb-core\lib\error.js:31:11)
    at queryCallback (D:\meanproject\today\node_modules\mongodb-core\lib\cursor.js:200:36)
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (D:\meanproject\today\node_modules\mongodb-core\lib\topologies\server.js:116:3)
    at null.messageHandler (D:\meanproject\today\node_modules\mongodb-core\lib\topologies\server.js:291:23)
    at Socket.<anonymous> (D:\meanproject\today\node_modules\mongodb-core\lib\connection\connection.js:285:22)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)

PencilBlue Version:   "version": "0.2.5",
Node versiion: 5.10
Mongodb version: 3.2

{"level":"info","message":"SystemStartup: Log Level is: info","timestamp":"2016-07-07T13:53:29.958Z"}
{"level":"info","message":"System[M]: 1 workers spawned. Listening for disconnects.","timestamp":"2016-07-07T13:53:30.538Z"}
{"level":"info","message":"SystemStartup: Log Level is: info","timestamp":"2016-07-07T13:53:30.844Z"}
{"level":"info","message":"PencilBlue: Ensuring indices...","timestamp":"2016-07-07T13:53:31.946Z"}
{"level":"info","message":"ServerInitializer: HTTP server starting, binding on IP 0.0.0.0 and port: 8080","timestamp":"2016-07-07T13:53:45.587Z"}
{"level":"info","message":"PencilBlue: Ready to run!","timestamp":"2016-07-07T13:53:45.592Z"}
{"level":"warn","message":"RequestHandler: The active theme is not set.  Defaulting to 'pencilblue'","timestamp":"2016-07-07T13:53:55.579Z"}
{"level":"warn","message":"RequestHandler: The active theme is not set.  Defaulting to 'pencilblue'","timestamp":"2016-07-07T13:53:55.603Z"}
{"level":"warn","message":"RequestHandler: The active theme is not set.  Defaulting to 'pencilblue'","timestamp":"2016-07-07T13:53:55.919Z"}
{"level":"warn","message":"RequestHandler: The active theme is not set.  Defaulting to 'pencilblue'","timestamp":"2016-07-07T13:53:55.929Z"}
{"level":"warn","message":"RequestHandler: The active theme is not set.  Defaulting to 'pencilblue'","timestamp":"2016-07-07T13:54:32.811Z"}
{"level":"warn","message":"MediaService is deprecated. Please use MediaServiceV2","timestamp":"2016-07-07T13:55:21.615Z"}
{"level":"warn","message":"MediaService is deprecated. Please use MediaServiceV2","timestamp":"2016-07-07T13:56:02.616Z"}
{"level":"warn","message":"MediaService is deprecated. Please use MediaServiceV2","timestamp":"2016-07-07T13:56:21.370Z"}
{"level":"warn","message":"MediaService is deprecated. Please use MediaServiceV2","timestamp":"2016-07-07T13:56:29.014Z"}
{"level":"warn","message":"PluginService: getServices is deprecated. Use PluginServiceLoader.getAll","timestamp":"2016-07-07T14:00:39.849Z"}
{"level":"warn","message":"Localization: localize is deprecated.","timestamp":"2016-07-07T14:00:53.720Z"}
{"level":"warn","message":"PencilBlue: pb.users is deprecated.  Use new pb.UserService(context) instead","timestamp":"2016-07-07T14:01:07.125Z"}
{"level":"warn","message":"PencilBlue: pb.users is deprecated.  Use new pb.UserService(context) instead","timestamp":"2016-07-07T14:01:25.066Z"}
{"level":"warn","message":"PencilBlue: pb.users is deprecated.  Use new pb.UserService(context) instead","timestamp":"2016-07-07T14:01:55.406Z"}
{"level":"warn","message":"PencilBlue: pb.users is deprecated.  Use new pb.UserService(context) instead","timestamp":"2016-07-07T14:02:25.514Z"}

**Comment by brianhyder** [comment]
@ceballos59 Thank you for submitting the issue.  I wanted to clarify the version of PB that you are using.  The version you listed is from the details.json file of the PB plugin.  If you look in the footer of the admin section what version is displayed?

**Comment by ceballos59** [comment]
I downloaded this version yesterday

"uid": "pencilblue",
    "name": "PencilBlue",
    "description": "The plugin that drives the default core
functionality of PencilBlue",
    "version": "0.2.5",
    "pb_version": "0.5.x",
    "icon": "pencil",
	"author": {
		"name": "PencilBlue",
		"email": "info@pencilblue.org",
		"website": "http://pencilblue.org",
		"contributors": [
			{
				"name": "Blake Callens",
				"email": ""
			},
			{
				"name": "Brian Hyder",
				"email": ""
			}
		]
	},
	"settings": [],
	"permissions": {
        "ACCESS_CANDIDATE": [],
        "ACCESS_USER": [],
		"ACCESS_WRITER": [],
		"ACCESS_EDITOR": [],
		"ACCESS_MANAGING_EDITOR": []
	},
	"main_module": {
		"path": "pencilblue.js"
	},
	"theme": {
		"settings": [],
		"content_templates":
		[
			{
				"file": "index",
				"name": "Default"
			}
		]
	}
}


2016-07-07 16:20 GMT+01:00, Brian <notifications@github.com>:

**Comment by brianhyder** [comment]
@ceballos59 If you change this line:
https://github.com/pencilblue/pencilblue/blob/master/include/service/entities/section_service.js#L379

in your local copy of PencilBlue does it fix your problem, after a restart?
```
order: [['name', pb.DAO.ASC]]
```

**Comment by ceballos59** [comment]
the bug still remains neither order: [['name', pb.DAO.ASC]]

I think happens with sections

2016-07-08 12:48 GMT+01:00, Brian <notifications@github.com>:

**Comment by brianhyder** [comment]
I'm making the assumption that this was a fresh install of version 0.6.0.  We do not officially support MongoDB 3.x.  If you downgrade to v2.x it should eliminate the issue for you.

**Comment by brianhyder** [comment]
I'm assuming you are working off of a fresh install of 0.6.0.  I can't reproduce the issue.  Can you provide more detailed steps to reproduce?

**Comment by ceballos59** [comment]
OK, but your 0.5 works okay in MongoDB 2.x..
....like i will waiting your angular2 updgrade, think that soon will
be pencilblue support MongoDB 3.x..
Thx

2016-07-09 2:46 GMT+01:00, Brian <notifications@github.com>:

**Comment by brianhyder** [comment]
I was actually incorrect in my previous comment, hence deleting it.  I'm using MongoDB 3.x in my local development.  If you can provide detailed step by step instructions to reproduce the error it would greatly appreciated.

**Comment by brianhyder** [comment]
Also ensure you have done, ```npm install``` from the directory where PencilBlue is installed to ensure you have the latest node modules.

**Comment by tomasvarg** [comment]
I've got the same error (`MongoError: bad sort specification`, the same trace) when trying to display a section - just clicking to a nav link of a section. 

Fresh installation, version 0.6.0 (latest commit 07f4f1e), Node 6.3.0, MongoDB 3.2.7, Arch Linux.

I'm new to Mongo, but the problem is fixed when changing this line:
https://github.com/pencilblue/pencilblue/blob/master/plugins/pencilblue/controllers/section.js#L119
from
```
                order: [{'publish_date': pb.DAO.DESC}, {'created': pb.DAO.DESC}]]
```
to either
```
                order: {'publish_date': pb.DAO.DESC, 'created': pb.DAO.DESC}
```
or
```
                order: [['publish_date', pb.DAO.DESC], ['created', pb.DAO.DESC]]
```

**Comment by brianhyder** [comment]
Awesome, thank you for the detail. If you'd like to submit the pull request
I will merge the fix otherwise I can do it tonight. We missed this when we
upgraded the Mongo driver. It was a breaking change in how the order is
specified.
