### ISSUE TITLE
Apps

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#1083]
**Description:**
I propose the integration of apps. In this scenario, Developers can develop apps without worrying about things like url. If app is installed, a url is generated by the system for that app like /apps/E_FsPnZGTZNCF. With  this different kind of apps could be developed by the community and easily plugged into the system. 

Following are examples of what I mean
https://www.jw.org/apps/E_FsPnZGTZNCF
https://www.jw.org/apps/E_SEARCHCONV
https://www.jw.org/apps/E_QBrNGR

**Comment by JahlomP** [comment]
With this a pencilblue platform can be composed of different apps built by developers in a team or from the community. Plug them into the system and you have a powerful platform.

**Comment by brianhyder** [comment]
Thanks for the suggestion but we won't be supporting this features as we intend to continue to iterate on multi-site.
