### ISSUE TITLE
Preview media files

### ISSUE THREAD

**Issue by ceballos59** [pencilblue/pencilblue#1094]
I can't play some video files with the same codec.   I will attach examples in e-mail.

**Comment by ceballos59** [comment]
I can´t sent examples

**Comment by brianhyder** [comment]
Code example or video files?

**Comment by ceballos59** [comment]
video files
2016-07-14 17:42 GMT+01:00, Brian <notifications@github.com>:

**Comment by ceballos59** [comment]
ceballos59@gmail.com
sent you some files

‘Here the examples’

Download:

https://www.wetransfer.com/downloads/678e1dbc3feb03d3cfcce8b092d43e8520160715090826/d54a8b0a721da5715b1662d04495bf0820160715090826/857688

Files (11 MB total)
noshow1.mp4
show.mp4

Will be deleted on
22 July, 2016


Get more out of WeTransfer, get Plus
https://www.wetransfer.com/plus?trk=email-recipient_download


About WeTransfer: https://www.wetransfer.com/about
Contact: https://www.wetransfer.com/contact
Legal: https://www.wetransfer.com/legal

To make sure you can receive our emails, please add noreply@wetransfer.com to your [trusted contacts](http://we.tl/trustedcontacts)

**Comment by brianhyder** [comment]
I downloaded the files and I'm still unsure if it is the way we are streaming the file or if it is an HTML5 video thing.  

I've been tinkering but getting too far.  Here are the items I've been looking at:
Mongo sample: https://gist.github.com/psi-4ward/7099001
FS Sample: http://stackoverflow.com/questions/24976123/streaming-a-video-file-to-an-html5-video-player-with-node-js-so-that-the-video-c
HTML5 Info: http://ronallo.com/blog/html5-video-everything-i-needed-to-know/

Either way we need to make a change or two to ensure that content-type and content length are being sent in the response headers.

**Comment by ceballos59** [comment]
Good, only I may tell you that both file was played in each
media-player than I tried also on  windows explorer media preview. I
finding for two days the problem reason also in Encoder.js but no
found, because it is so ugly that some videos with the same codec show
their preview unlike others. Users will question this.

I will see the material proposed, Be

Thx.

2016-07-18 1:46 GMT+01:00, Brian <notifications@github.com>:
