### ISSUE TITLE
Where are the topics in Pencilblue Blog, How i can set topics

### ISSUE THREAD

**Issue by ceballos59** [pencilblue/pencilblue#1095]

**Comment by brianhyder** [comment]
Can you provide a bit of clarification?  What do you want to set topics on?  Articles?

**Comment by ceballos59** [comment]
I associate topics to articles , but then can not find the way the
topics are displayed in the standard blog. I apologize for my poor
English. Be sure I already know more Pencilblue than English.
Thx


2016-07-19 18:07 GMT+01:00, Brian <notifications@github.com>:

**Comment by brianhyder** [comment]
No worries!  Thank you for the clarification.  The default pencilblue theme does not display topics on the blog.  The portfolio theme does provide this functionality.  I would start looking at https://github.com/pencilblue/pencilblue/blob/master/plugins/portfolio/controllers/blog.js

The code is a bit old.  We now use ArticleRenderer instances to handle most of what that file does but we just haven't had time to go back and update it.  Let me know if I can answer any other questions.

**Comment by ceballos59** [comment]
Thanks, I comment. For the main site I use the portfolio plugin, here,
as you say, the topics are displayed in the blog, but does not work
quite well, I explain where it fails. If you have two sections, and
one of them applies the filter by topics, as a result you will have
all the selected items without verifying the section where I was
topic. For example, two sections, sport and culture, asian topic. If
you are in the sports section and filter by Asians, blog listing all
the items will be displayed in both sections related to the condition
of Asian. It is for this reason that then finding the topics in the
standard of pencilblue.

2016-07-20 11:08 GMT+01:00, Brian <notifications@github.com>:

**Comment by brianhyder** [comment]
This is something that we didn't build in.  You would need a controller that would build out this particular query.  Essentially, you would need to be able to get the requested topic and section.  It would require modifications to the blog filter and/or blog.js controller.  Both are not the easiest things to understand.  I'm honestly not sure the best way to go about that without re-writing your own controller to handle the rendering.

**Comment by ceballos59** [comment]
Thank you for your clarification
