### ISSUE TITLE
customObjects update type?

### ISSUE THREAD

**Issue by larskarbo** [pencilblue/pencilblue#1099]
Is there a function similar to saveType that can update the objects?

I have a file with all custom object definitions and would like the objects to be updated automatically on install without having to delete them first.

**Comment by brianhyder** [comment]
http://pencilblue.github.io/classes/CustomObjectService.html#method_save

**Comment by larskarbo** [comment]
Sorry, I had a typo in my question. 

I meant: Is there a function similar to saveType that can update the type (like updateType)?

**Comment by brianhyder** [comment]
The saveType function will do update and add. It looks for the presence of
the _id field used by Mongo.

**Comment by brianhyder** [comment]
You can also look at the controllers that update the custom object type in
the pencilblue plugin.
