### ISSUE TITLE
some checks do not work properly

### ISSUE THREAD

**Issue by ceballos59** [pencilblue/pencilblue#1103]
Node.js v5.10.1
MongoDB v3.2.4
"pb_version": "0.5.x",

getUsernameAvailability() in user_form.html
resetUsernameAvailability() in sing_up.html
resetUrlAvailability() in article.html and page.html
only works resetAvailability() in type_form.html

you can try with existing records and functions in any way give them as available

**Comment by brianhyder** [comment]
This is a regression and will be fixed in the next couple of days.
