### ISSUE TITLE
Error in Forgot Password issue

### ISSUE THREAD

**Issue by ceballos59** [pencilblue/pencilblue#1106]
**Description:**

System error when you use forgotPassword() funcionality.

**Steps to Reproduce:**

Login - and then you click on "I forgot my password" funcionality, and then the following message is displayed

2016-07-25T09:31:09.760Z - error: [1] RequestHandler: An error occurred during controller execution. URL=[POST:/actions/forgot_password?admin=1] ROUTE={"path":"actions/forgot_password","pattern":"^/actions/forgot_password[/]{0,1}$","path_vars":{},"expression":{},"themes":{"global":{"size":1,"pencilblue":{"POST":{"method":"POST","path":"/actions/forgot_password","access_level":0,"auth_required":false,"inactive_site_access":true,"content_type":"text/html","request_body":["application/x-www-form-urlencoded","application/json"]}}}}}
ReferenceError: settings is not defined
    at /home/guillermo/pb1507/include/email.js:169:43
    at /home/guillermo/pb1507/include/service/simple_layered_service.js:94:17
    at /home/guillermo/pb1507/node_modules/async/lib/async.js:789:30
    at /home/guillermo/pb1507/node_modules/async/lib/async.js:167:37
    at /home/guillermo/pb1507/include/service/simple_layered_service.js:75:21
    at module.exports.DbEntityService.get.callback (/home/guillermo/pb1507/include/service/db_entity_service.js:84:24)
    at /home/guillermo/pb1507/include/dao/dao.js:143:12
    at /home/guillermo/pb1507/include/dao/dao.js:271:17
    at handleCallback (/home/guillermo/pb1507/node_modules/mongodb/lib/utils.js:96:12)
    at /home/guillermo/pb1507/node_modules/mongodb/lib/cursor.js:835:16

PencilBlue Version:  "0.5.x

Node.js Version: v4.4.6

**Comment by brianhyder** [comment]
This does not appear to happen in master (0.6.x).  Additionally, I would check to make sure that you have configured the Settings => Email page in the admin section.

**Comment by ceballos59** [comment]
OK

I can tell you that before I run this functionality, I sent a test
e-mail through the app and this worked correctly, so I presume that I
have properly configured the mail data on the site.

Anyway I show my settings

 "_id" : ObjectId("579225a8f804dc0c0fb50635"),
        "object_type" : "setting",
        "key" : "email_settings",
        "value" : {
                "from_name" : "Biblioteca Digital",
                "from_address" : "no-reply@sample.com",
                "verification_subject" : "Biblioteca Digital Account
Confirmation",
                "verification_content" : "",
                "template" : "admin/elements/default_verification_email",
                "service" : "Gmail",
                "host" : "",
                "secure_connection" : 1,
                "port" : 465,
                "username" : "ceballos59@gmail.com",
                "password" : "********************"
        },
        "site" : "global",
        "created" : ISODate("2016-07-22T13:54:48.521Z"),
        "last_modified" : ISODate("2016-07-22T13:55:18.470Z"),
        "id" : ObjectId("579225a8f804dc0c0fb50635")

Thx

**Comment by ceballos59** [comment]
I do not understand very well that means master of the 0.6.

Anyway I downloaded the 0.6 branch and I tried running forgotpass
functionality, and now an e-mail  sends the user, however, the link
always returns this "error" .- The verification parameters Were
invalid. Please re-enter your email address.

?!?!?.

Regards.

2016-07-25 11:52 GMT+01:00, Brian <notifications@github.com>:

**Comment by brianhyder** [comment]
We follow the typical Git branching strategy.  The "master" branch is always considered stable and will always be the most up-to-date code.  We also have versioned branches (0.6.0, 0.7.0).  This is the code that contains the code from the master branch with the addition of code for our upcoming release.

I'm not seeing the same error when I try to reproduce your issue.  Can you debug a bit and look to see which line in the ```plugins/pencilblue/controllers/actions/user/reset_password.js``` file is causing the issue?

**Comment by ceballos59** [comment]
when you click on link from email, the system show the following message:

in reset_password.js
  line 87              if (!data.passwordReset) {
                     return
self.formError(self.ls.get('INVALID_VERIFICATION'), '/user/login',
cb);
                 }
                 self.passwordResetService.deleteSingle({where:
{verificationCode:  data.passwordReset.verificationCode}}, callback);
            }]


data.passwordReset == null

2016-07-25 22:59 GMT+01:00, Brian <notifications@github.com>:

**Comment by ceballos59** [comment]
all ok,thx
