### ISSUE TITLE
more about forgot password issue

### ISSUE THREAD

**Issue by ceballos59** [pencilblue/pencilblue#1109]
Sorry, I was telling you that everything was working properly but not completely. The email with the link leads us to the change password view, but here, current password is required fields. Obviously I can not go ahead, because I do not remember my password. As a result I can not save new password and then functionality does not reach the end.

pencilblue: v0.6.0",
nodeJs:  v5.10.1
mongodb: v3.2.4

**Comment by brianhyder** [comment]
You are right. This is a bug and an oversight on our part.  @blakecallens Do you think you could could us up a plain view that doesn't require the current password field or the nav menus?

**Comment by ceballos59** [comment]
Please I don´t understand your request

2016-07-28 23:45 GMT+01:00, Brian <notifications@github.com>:

**Comment by blakecallens** [comment]
This is some old code (back before we integrated Angular) and will take some digging into, but I'm on it.

**Comment by blakecallens** [comment]
NM. Found it. There's a session variable called reset_password that gets set and is supposed to hide the current password field, but we missed that when we migrated this page to Angular. Fix incoming.
