### ISSUE TITLE
Question about security

### ISSUE THREAD

**Issue by ceballos59** [pencilblue/pencilblue#1113]
method: 'get',
   path: '/media/*',
   auth_required: false,
   inactive_site_access: true,
   controller: path.join(pb.config.docRoot, 'plugins', 'pencilblue', 'controllers', 'media_content_controller.js')

With this route you can access any media within  website when the url is known ..
My cuestion is, how can you avoid this? 
If I put authentication level or access to this route, the blog does not work properly, but if I release fully open the path /media/*. All media resources are available for everybody without login.

**Comment by brianhyder** [comment]
There isn't a good way of doing this with the current implementation.  We could probably build this into the media API but it would require a lot of changes to the UI to distinguish between protected media and public media.  Meaning, we'd have to ensure that only public media got attached to articles and pages.  

In your case, if you wanted a private media store I would create a service that extended MediaServiceV2.  I think you would need to override ```MediaServiceV2.generateMediaPath``` to create a different URL structure.  You could then modify the service to accept an additional property for role on the media descriptor object.  Lastly, you would need a controller and route to retrieve the media and check for the role before streaming it back out.  This would allow you to send the proper response codes.

**Comment by ceballos59** [comment]
Thanks , I think the same as you

2016-07-29 0:16 GMT+01:00, Brian <notifications@github.com>:
