### ISSUE TITLE
Freezing sites in admin

### ISSUE THREAD

**Issue by JLKM** [pencilblue/pencilblue#1116]
*Nice to experience, how PB 0.6 runs fine on Node 6.X. Good work! Looking forward to Angular 2 in PB, too.*

Next step for me is to make PB co-exist with a static site generator and a forum-system. Nginx has been setup in order to direct different incoming domains to the appropriate localhost:XXXX + kick the awesome PB-multi-tenancy into play with redirections to the subdomains of several sites.
Nginx works like a charm with the two other systems. But I suspect, Nginx might be the problem in the following PB-issue.

I've done a series of clean installations on Linux yesterday and today with various settings, but no luck. I suppose, the code in use is up to date, since I've created the PB-system with > pbctrl install foldername.

Before first launch config.js has been changed in the bottom to:
    "multisite": {
        "enabled": true,
        "globalRoot": "http://node-js.dk"
    },

The value for "globalRoot" being the same as the input-value during setup for "siteRoot".  "sitePort" is 4111, which Nginx redirects to.

No error messages in the console during fireup, and admin user is created without problems. PencilBlue theme is set and activated. But when I add more sites in "Manage Sites", strange things begin to happen, when I deal with more sites. Their domain-name being without port-number and http://. Example: `typescript.node-js.dk`

1. Everything freezes on "Create New Site" - with the following message:
`2016-07-29T14:37:58.139Z:[2] EDIT_SITEf60920be-9f69-4224-97f9-689000e28384: Updating job [f1deb621-52a7-446d-bb90-fe10c30dfdc2:EDIT_SITEf60920be-9f69-4224-97f9-689000e28384] by 50 percent with status:` 

The new site is present, however, after window close and re-login.

2. Same story with "Activate Site" - example-message:
`2016-07-29T14:39:58.469Z:[2] ACTIVATE_SITE_5231ff3d-f917-4474-a4a2-ef85c33586fe: Updating job [b64f4c8a-eaaf-4696-b33a-e574b1e85cb3:ACTIVATE_SITE_5231ff3d-f917-4474-a4a2-ef85c33586fe] by 50 percent with status:`
Still, the site is activated after window close and re-login.

3. A click on each site name link use to lead to the relevant domain and belonging content/settings. But in this case a click leads nowhere. Only a prompt `Authentication token created` shows up.

4. While the left navigation seems intact, the content-section never shows up. A real show stopper.

Here a few "greatest hits" from the log:
```
2016-07-29T16:37:00.551Z - info: [1] PencilBlue: Ready to run!
2016-07-29T16:39:57.614Z - warn: [1] RequestHandler: Failed to close session [5740b3a6-72af-4c8a-8936-b8212bcbfb21]
```
```
2016-07-29T15:04:22.588Z - info: [2] PencilBlue: Ready to run!
2016-07-29T15:04:34.547Z - warn: [2] RequestHandler: The active theme is not set.  Defaulting to 'pencilblue'
```
```
2016-07-29T15:04:07.583Z - info: [1] SystemStartup: Log Level is: info
2016-07-29T15:04:10.077Z - info: [1] PencilBlue: Ensuring indices...
/share/CACHEDEV1_DATA/pbnode/pencilblue.js:81
                throw err;
                ^

Error: A failure occurred while performing tasks across remote processes.  Check the job log for more details: Error: A failure occurred while performing tasks across remote processes.  Check the job log for more details: Error: Failed to publish the command to the cluster
    at /share/CACHEDEV1_DATA/pbnode/include/system/command/command_service.js:372:36
    at /share/CACHEDEV1_DATA/pbnode/include/system/command/command_service.js:472:13
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:726:13
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:52:16
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:269:32
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:44:16
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:723:17
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:167:37
    at /share/CACHEDEV1_DATA/pbnode/node_modules/fakeredis/main.js:184:5
    at Timeout._onTimeout (/share/CACHEDEV1_DATA/pbnode/node_modules/fakeredis/lib/connection.js:343:18)
    at /share/CACHEDEV1_DATA/pbnode/include/service/jobs/cluster_job_runner.js:201:34
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:726:13
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:52:16
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:269:32
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:44:16
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:723:17
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:167:37
    at /share/CACHEDEV1_DATA/pbnode/include/system/command/command_service.js:330:25
    at /share/CACHEDEV1_DATA/pbnode/include/system/command/command_service.js:372:25
    at /share/CACHEDEV1_DATA/pbnode/include/system/command/command_service.js:472:13
    at /share/CACHEDEV1_DATA/pbnode/include/service/jobs/cluster_job_runner.js:201:34
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:726:13
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:52:16
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:269:32
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:44:16
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:723:17
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:167:37
    at Domain.<anonymous> (/share/CACHEDEV1_DATA/pbnode/include/system/command/command_service.js:330:25)
    at emitOne (events.js:96:13)
    at Domain.emit (events.js:188:7)
Override file [/share/CACHEDEV1_DATA/pbnode/config.js] will be applied.
2016-07-29T15:04:17.859Z - info: [2] SystemStartup: Log Level is: info
2016-07-29T15:04:20.443Z - info: [2] PencilBlue: Ensuring indices...
2016-07-29T15:04:22.565Z - info: [2] ServerInitializer: HTTP server starting, binding on IP 0.0.0.0 and port: 4111
```

And the last one from a warning in lightred on the screen:
```
An error occurred while attempting to complete the action: MongoError: not authorized on pencilblue to execute command { find: "job_run", filter: { _id: "a2117e82-f01d-428c-91b5-e364e9d35e40" }, sort: {}, projection: {}, limit: 1 } at Function.MongoError.create (/share/CACHEDEV1_DATA/pbnode/node_modules/mongodb-core/lib/error.js:31:11) at queryCallback (/share/CACHEDEV1_DATA/pbnode/node_modules/mongodb-core/lib/cursor.js:200:36) at bound (domain.js:280:14) at runBound (domain.js:293:12) at Callbacks.emit (/share/CACHEDEV1_DATA/pbnode/node_modules/mongodb-core/lib/topologies/server.js:119:3) at .messageHandler (/share/CACHEDEV1_DATA/pbnode/node_modules/mongodb-core/lib/topologies/server.js:397:23) at Socket.<anonymous> (/share/CACHEDEV1_DATA/pbnode/node_modules/mongodb-core/lib/connection/connection.js:302:22) at emitOne (events.js:96:13) at Socket.emit (events.js:188:7) at readableAddChunk (_stream_readable.js:172:18) 
```
The last one indicates problems with MongoDB. But access to MongoDB has to be OK, since I'm able to get the suggested query in MongoDB for the job_log. Which shows this:
`> db.job_log.find()
{ "_id" : ObjectId("579b70708e4f0aa54b8eeed1"), "object_type" : "job_log", "job_id" : "ab7f5b64-2c1b-4931-8d60-6e83ea78bfbd", "worker_id" : 1, "name" : "EDIT_SITEd15116c3-573b-47d3-a25e-e8e812f59dd0", "message" : "EDIT_SITEd15116c3-573b-47d3-a25e-e8e812f59dd0: Updating job [ab7f5b64-2c1b-4931-8d60-6e83ea78bfbd:EDIT_SITEd15116c3-573b-47d3-a25e-e8e812f59dd0] by 50 percent with status: ", "metadata" : [ ], "created" : ISODate("2016-07-29T15:04:16.957Z"), "last_modified" : ISODate("2016-07-29T15:04:16.957Z") }
{ "_id" : ObjectId("579b70c654a12dc34bfd8c74"), "object_type" : "job_log", "job_id" : "4c39267f-b56a-4750-b4d1-8fe88271256b", "worker_id" : 2, "name" : "ACTIVATE_SITE_d15116c3-573b-47d3-a25e-e8e812f59dd0", "message" : "ACTIVATE_SITE_d15116c3-573b-47d3-a25e-e8e812f59dd0: Updating job [4c39267f-b56a-4750-b4d1-8fe88271256b:ACTIVATE_SITE_d15116c3-573b-47d3-a25e-e8e812f59dd0] by 50 percent with status: ", "metadata" : [ ], "created" : ISODate("2016-07-29T15:05:42.005Z"), "last_modified" : ISODate("2016-07-29T15:05:42.005Z") }
{ "_id" : ObjectId("579b724e54a12dc34bfd8c7e"), "object_type" : "job_log", "job_id" : "827caa9b-39b1-4b6b-8a8b-5f7c0e4c0d89", "worker_id" : 2, "name" : "EDIT_SITE9129f42a-4c93-4ee7-9b09-2cfedf1bdc15", "message" : "EDIT_SITE9129f42a-4c93-4ee7-9b09-2cfedf1bdc15: Updating job [827caa9b-39b1-4b6b-8a8b-5f7c0e4c0d89:EDIT_SITE9129f42a-4c93-4ee7-9b09-2cfedf1bdc15] by 50 percent with status: ", "metadata" : [ ], "created" : ISODate("2016-07-29T15:12:14.334Z"), "last_modified" : ISODate("2016-07-29T15:12:14.334Z") }`

The code seems to be the updated version according to [issue 1082](https://github.com/pencilblue/pencilblue/blob/master/plugins/pencilblue/controllers/section.js#L119). At least my line of code reads:

`order: [['publish_date', pb.DAO.DESC], ['created', pb.DAO.DESC]]`
and not
`order: [{'publish_date': pb.DAO.DESC}, {'created': pb.DAO.DESC}]]`

Please anyone, what am I missing here? Has it nothing to do with Nginx - but rather MongoDB? Somethings with access or the fact, that MongoDB runs inside Docker?

PS: `siteRoot": "http://node-js.dk:4111` adds ":4111" to the url, when clicking links in admin, and this isn't wanted.

Here follows the entire config.js for reference:
```
module.exports = {
    "siteName": "nodejs",
    "siteRoot": "http://node-js.dk",
    "sitePort": 4111,
    "logging": {
        "level": "info"
    },
    "db": {
        "type": "mongo",
        "servers": [
            "mongodb://127.0.0.1:27017/"
        ],
	"authentication": {
		"un": "pencilblue",
		"pw": "****************"
        },
        "name": "pencilblue",
        "writeConcern": 1,
        "query_logging": false
    },
    "cache": {
        "fake": true,
        "host": "localhost",
        "port": 6379
    },
    "settings": {
        "use_memory": false,
        "use_cache": false
    },
    "templates": {
        "use_memory": true,
        "use_cache": false
    },
    "plugins": {
        "caching": {
            "use_memory": false,
            "use_cache": false
        }
    },
    "registry": {
        "type": "mongo"
    },
    "session": {
        "storage": "mongo"
    },
    "media": {
        "provider": "mongo",
        "max_upload_size": 6291456
    },
    "cluster": {
        "workers": 1,
        "self_managed": true
    },
    "multisite": {
        "enabled": true,
        "globalRoot": "http://node-js.dk"
    },
    "siteIP": "0.0.0.0"
};
```

**Comment by brianhyder** [comment]
First off, THANK YOU for submitting a detailed issue.  This is immensely helpful to us.  My apologies for not getting back to you sooner.  My initial reaction is that the mongo registry is the problem.  MongoDB has a minimum TTL of 60 seconds.  This means that if you attempted to install a plugin within 60 seconds of a restart you can run into this issue because the old processes are still in the registry.  

I'd like to test the theory by asking that you switch the the "registry.type" property to "redis".  This should allow for expiration of entries once a second rather than once per minute.  

As a side note.  I'd also like to recommend that with multi-site clusters that you use a real redis instance.  A real redis instance will allow for your servers to spin up and support multiple PB instances across multiple processes and physical/virtual servers.  For more on this read the "Getting Ready for Production" section on our wiki [here](https://github.com/pencilblue/pencilblue/wiki/Quickstart:-Configuration)

**Comment by JLKM** [comment]
Thank you for the suggestion to replace "mongo" with "redis" in this section of config.js:
```
    "registry": {
        "type": "redis"
    }
```

After a clean installation with this setting, I'm now able to actually create new sites (and not only 50 percent...) in my setup with multisite=true. But they don't work!
1. I'm not able to switch from one site to another in the manage sites section. A click on the appropriate links returns a prompt, that authentication token has been created. But I remain in the main site.
2. No content section ever shows up in the left bar.

Some details from the logs may lead wiser people than me closer to the light.

First the log from right after `>npm start`, which shows an error, that might be a low hanging fruit: 

```
[admin@LaeburghNAS pbnode]# npm start

> pencilblue@0.6.0 start /share/CACHEDEV1_DATA/pbnode
> node pencilblue.js

Override file [/share/CACHEDEV1_DATA/pbnode/config.js] will be applied.
2016-08-06T15:40:33.878Z - info: [M] SystemStartup: Log Level is: info
2016-08-06T15:40:35.035Z - info: [M] System[M]: 1 workers spawned. Listening for disconnects.
Override file [/share/CACHEDEV1_DATA/pbnode/config.js] will be applied.
2016-08-06T15:40:35.588Z - info: [1] SystemStartup: Log Level is: info
2016-08-06T15:40:37.711Z - info: [1] PencilBlue: Ensuring indices...
/share/CACHEDEV1_DATA/pbnode/pencilblue.js:81
                throw err;
                ^

TypeError: Cannot read property 'keys' of null
    at RedisRegistrationProviderModule.RedisRegistrationProvider.get (/share/CACHEDEV1_DATA/pbnode/include/system/registry/redis_registration_provider.js:78:15)
    at ServerRegistrationModule.ServerRegistration.getClusterStatus (/share/CACHEDEV1_DATA/pbnode/include/system/server_registration.js:128:23)
    at CommandServiceModule.CommandService.sendCommandToAllGetResponses (/share/CACHEDEV1_DATA/pbnode/include/system/command/command_service.js:299:27)
    at /share/CACHEDEV1_DATA/pbnode/include/service/jobs/cluster_job_runner.js:191:45
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:718:13
    at iterate (/share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:262:13)
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:274:29
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:44:16
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:723:17
    at /share/CACHEDEV1_DATA/pbnode/node_modules/async/lib/async.js:167:37
Override file [/share/CACHEDEV1_DATA/pbnode/config.js] will be applied.
2016-08-06T15:40:45.156Z - info: [2] SystemStartup: Log Level is: info
2016-08-06T15:40:47.287Z - info: [2] PencilBlue: Ensuring indices...
2016-08-06T15:40:49.152Z - info: [2] ServerInitializer: HTTP server starting, binding on IP 0.0.0.0 and port: 4111
2016-08-06T15:40:49.168Z - info: [2] PencilBlue: Ready to run!
2016-08-06T15:41:14.927Z - warn: [2] RequestHandler: The active theme is not set.  Defaulting to 'pencilblue'
2016-08-06T15:41:14.943Z - warn: [2] RequestHandler: The active theme is not set.  Defaulting to 'pencilblue'
2016-08-06T15:41:14.962Z - warn: [2] RequestHandler: The active theme is not set.  Defaulting to 'pencilblue'
2016-08-06T15:41:41.664Z - warn: [2] RequestHandler: The active theme is not set.  Defaulting to 'pencilblue'

```
The problems only show up on my server installation on Linux, Node 6.1, PB 0.6. Everything works perfectly on my local Windows, Node 6.3, PB 0.6 setup using localhost:8080. This has made me dig into the dato stored in the two MongoDB-installations - both v. 3.2. And I managed to find two differences.

```
db.user.find()
Linux:
{ "_id" : ObjectId("57a60535802f6c3533b9b5da"), "first_name" : "Jan", "last_name" : "Larsen", "username" : "admin", "email" : "info@udvandrerne.dk", "password" : "***deleted***", "admin" : 4, "object_type" : "user", **"site" : "global"**, "created" : ISODate("2016-08-06T15:41:41.678Z"), "last_modified" : ISODate("2016-08-06T15:41:41.678Z") }

Windows:
{ "_id" : ObjectId("57a4d7ead61065282c84efd7"), "first_name" : "Jan", "last_name" : "Larsen", "username" : "admin", "email" : "info@udvandrerne.dk", "password" : "***deleted***", "admin" : 4, "object_type" : "user", "created" : ISODate("2016-08-05T18:16:10.180Z"), "last_modified" : ISODate("2016-08-05T19:19:14.124Z"), **"id" : ObjectId("57a4d7ead61065282c84efd7")**, **"site" : "global"** }

```
1. The site-parameter has different locations in the map.
2. The id-parameter is repeated in the Windows setup.

The redirection made by Nginx - from IP:localhost to the real domainname etc. actually works at first login. But at the following logins something strange happens. /admin/login has to be entered manually to get inside. Login only return the domainname with an empty frontpage. Just to remind, that Nginx may still play a role.

Other possible sources of error:
3. My config.js reads `"globalRoot": "http://node-js.dk"` not `"globalRoot": "http://global.node-js.dk"`
4. I haven't setup subdomains on my dns-server for the sites created - example: typescript.node-js.dk. The subdomains are eventually going to be translated into mail-domains in Nginx. Bud is the subdomain route mandatory just to make setup and writing documents from admin?

It seems like, I'm almost there. Just a little push. Anyone...

**Comment by brianhyder** [comment]
From my understanding of the multi-site implementation it all has to be setup as sub-domains, that includes the global root.

**Comment by JLKM** [comment]
Thank you for the input. I'll give it a try and setup pairs like http://node-js.dk" and "http://global.node-js.dk" for handling both at DNS and in Nginx before creating them as sites in PB.

**Comment by JLKM** [comment]
Sub-domains as host names were also my first, second and thirteenth shot for a way to go with the host names in the Manage Sites department. But after a two digit number of hours testing it turns up, that main domain names (host names like pencilblue.org without any prefix) work like a charm, when Nginx takes care of stripping of the port number etc.. I've just made a three site multi-tenant setup with Nginx and PencilBlue 0.6 on Node 6.X on Linux. No freezing. No nothing. It works just perfect both in admin and for the anonymous user. Thank you for your patience. Now it's time to write that danish language pack. Is a pull request needed for that, or what method do you prefer?
