### ISSUE TITLE
WYSWIG editor doesnt translate to html well.

### ISSUE THREAD

**Issue by benag** [pencilblue/pencilblue#1117]
**Description:**
The WYSWIG editor created broken html source

**Steps to Reproduce:**
type two random lines in articles editor

**Configuration Details:**

standart
**Log Output:**

PencilBlue Version: 
latest
Node.js Version:
4.4.7
Environment Description:

**Comment by blakecallens** [comment]
The wysiwyg is a contenteditible div, which means it conforms to the formatting of the way each browser renders contenteditable. For exact HTML, use the HTML editor view.
