### ISSUE TITLE
Wildcard route on root

### ISSUE THREAD

**Issue by larskarbo** [pencilblue/pencilblue#1119]
Is it a way to add a wildcard route on root, check the url and send the request to the next controller if no match is found?

`````
{
    method: 'get',
    path: "/*",
    content_type: 'text/html'
}
````

**Comment by brianhyder** [comment]
Not easily. What exactly are you trying to accomplish?

**Comment by larskarbo** [comment]
I'm sorry, what I meant was:

````
{
    method: 'get',
    path: "/:page",
    content_type: 'text/html'
}
````

Is this possible?

**Comment by brianhyder** [comment]
There is not a good way to hook back into the request handler after a route and controller have been selected.  The only way you can really accomplish this is to create a controller that registers itself as you described.  It would need to check for a matching page.  if found call the page controller.  Then do the same thing checking for each route that is registered just after the route.  This implementation will probably prevent the ability to have localized routes so just beware if you proceed this way.
