### ISSUE TITLE
Could fix some SubNavItem Label in line 176 media_form.js controller

### ISSUE THREAD

**Issue by ceballos59** [pencilblue/pencilblue#1122]
--- plugins/pencilblue/controllers/admin/content/media/media_form.js	
     MediaForm.getSubNavItems = function(key, ls, data) {
         return [{
             name: 'manage_media',
-            title: data[pb.DAO.getIdField()] ? ls.get('EDIT') + ' ' + data.name : ls.get('NEW_MEDIA'),
+            title: data[pb.DAO.getIdField()] ? ls.get('EDIT') + ' ' + data.name : ls.get('MANAGE_MEDIA'),
             icon: 'chevron-left',
             href: '/admin/content/media'
         }, {

**Comment by brianhyder** [comment]
This is by design in the default theme.  The icon indicates you can go back (where the link takes you) and the label shows where you are.  It doesn't provide a great experience but we would have to change it everywhere in the admin UI.  We plan to modify this in our first release of 2017.
