### ISSUE TITLE
Despcription field in custom objects items

### ISSUE THREAD

**Issue by ceballos59** [pencilblue/pencilblue#1127]
**Description:**
When you set custom objects, apparently the id and description fields should be reserved as default by the system. The user could then enter the id, however at no time can not enter the description record, and for that reason, in the view of items of each object, the field always show blank description. This is so ?!? or something I'm not setting well. ?!?!?!?

example:

Name                                         	Despcription                                      	Last Modified 
namesomeitemobject                     <always blank>                                           dd-mm-yy

**Comment by brianhyder** [comment]
The UI makes an assumption that there will be a description field added by the user.  Not a great design but that is how it works.  It is safe to add a description field to the object

**Comment by ceballos59** [comment]
Thanks for your attention.
I 'll tell you how I think: the custom object module has a huge
potential to explore.
Thanks again.

2016-08-15 1:11 GMT+01:00, Brian <notifications@github.com>:
