### ISSUE TITLE
issue with npm start and mongolab (mlab) connection??

### ISSUE THREAD

**Issue by laterdude** [pencilblue/pencilblue#1137]
**Description:**
I can't start pencilblue
I think this is something to do with the my mlab url?? 

**Steps to Reproduce:**
I install pencilblue, run the pbctrl, move to the directory, and then run npm start, and then I get the log output below...

found only this on stackoverflow: http://stackoverflow.com/questions/27455564/mongolab-connecting-to-heroku-with-pencilblue

I tried several variations on the config, the url works with keystone and all my other nodejs/mongoose/mongo applications. By the way the first config I tried is below, I also attempted:
    "db": {
        "type": "mongo",
        "servers": [
            "mongodb://laterdudes:mypassword@dsXXX14.mongolab.com:XXX14/dbname"
        ],
        "name": "dbname",
        "authentication": {
            "un": "laterdudes",
            "pw": "mypassword"
        },
        "writeConcern": 1,
        "query_logging": false
    }....
afterwards.
**Configuration Details:**
"siteName": "gbcc",
    "siteRoot": "8080",
    "sitePort": 8080,
    "logging": {
        "level": "info"
    },
    "db": {
        "type": "mongo",
        "servers": [
            "mongodb://laterdudes:mypassword@dsXXX14.mongolab.com:XXX14/dbname"
        ],
        "name": "dbname",
        "writeConcern": 1,
        "query_logging": false
    },
    "cache": {
        "fake": true,
        "host": "localhost",
        "port": 6379
    },
    "settings": {
        "use_memory": false,
        "use_cache": false
    },
    "templates": {
        "use_memory": true,
        "use_cache": false
    },
    "plugins": {
        "caching": {
            "use_memory": false,
            "use_cache": false
        }
    },
    "registry": {
        "type": "mongo"
    },
    "session": {
        "storage": "mongo"
    },
    "media": {
        "provider": "mongo",
        "max_upload_size": 6291456
    },
    "cluster": {
        "workers": 1,
        "self_managed": true
    },
    "multisite": {
        "enabled": false,
        "globalRoot": "http://global.localhost:8080"
    }
};

**Log Output:**
{"level":"info","message":"SystemStartup: Log Level is: info","timestamp":"2016-09-06T00:38:19.957Z"}
{"level":"info","message":"System[M]: 1 workers spawned. Listening for disconnects.","timestamp":"2016-09-06T00:38:21.378Z"}
{"level":"info","message":"SystemStartup: Log Level is: info","timestamp":"2016-09-06T00:38:22.065Z"}
{"level":"error","message":"System[1]: uncaught Exception detected : Error: no hostname or hostnames provided in connection string\n    at module.exports (C:\\Users\\rtippetts\\Desktop\\Documents\\pencilBlue\\gbcc\\node_modules\\mongodb\\lib\\url_parser.js:24:11)\n    at connect (C:\\Users\\rtippetts\\Desktop\\Documents\\pencilBlue\\gbcc\\node_modules\\mongodb\\lib\\mongo_client.js:159:16)\n    at Function.MongoClient.connect (C:\\Users\\rtippetts\\Desktop\\Documents\\pencilBlue\\gbcc\\node_modules\\mongodb\\lib\\mongo_client.js:110:3)\n    at DBManager.getDb (C:\\Users\\rtippetts\\Desktop\\Documents\\pencilBlue\\gbcc\\include\\dao\\db_manager.js:110:19)\n    at PencilBlue.initDBConnections (C:\\Users\\rtippetts\\Desktop\\Documents\\pencilBlue\\gbcc\\pencilblue.js:171:16)\n    at C:\\Users\\rtippetts\\Desktop\\Documents\\pencilBlue\\gbcc\\node_modules\\async\\lib\\async.js:718:13\n    at Immediate.iterate [as _onImmediate] (C:\\Users\\rtippetts\\Desktop\\Documents\\pencilBlue\\gbcc\\node_modules\\async\\lib\\async.js:262:13)\n    at tryOnImmediate (timers.js:543:15)\n    at processImmediate [as _immediateCallback] (timers.js:523:5)","timestamp":"2016-09-06T00:38:23.549Z"}

PencilBlue Version: 
0.6.1
Node.js Version:
6.2.2
Environment Description:
{ pencilblue: '0.6.1',
  npm: '3.9.5',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.2.2',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.52',
  zlib: '1.2.8' }

**Comment by laterdude** [comment]
I tried several variations on the config, the url works with keystone and all my other nodejs/mongoose/mongo applications

**Comment by brianhyder** [comment]
We have a site that uses MongoLabs.  We setup our config.js file as follows:
```javascript
"db": {
        "servers": [
            "ds000000-ax.mongolab.com:45655"
        ],
        "name": “my-pb-db“,
        "authentication": {
            un: "someusername",
            pw: "abc123"
        },
        "options": {
            "replSet": {
                "replicaSet": "rs-ds000000"
            }
        },
        "writeConcern": 1
    }
```

If you don't have a replica-set just leave out that options block.  Let me know if that doesn't work.

**Comment by laterdude** [comment]
Thank you for your help. Up and running. Looking forward to checking it out,
