### ISSUE TITLE
only one comment

### ISSUE THREAD

**Issue by ceballos59** [pencilblue/pencilblue#1162]
There are currently no plugin to work properly and I 
and I would like to work filtering by topics and jennifer plugin does not work either

pencilblue version: "version": "0.7.0"

Jennifer plugin:  "version": "0.2.0",

**Comment by dukeofsussex** [comment]
All plugins shipped with PB are on the lastest version. For the other plugins it's up to their respective maintainers to keep them up-to-date.

You can always check whether the outdated plugin will work on your version of PB by changing the PB version in the plugin's `details.json`. I've done this with a few and not had any problems so far (which also resides in the fact that PB hasn't had many (any?) breaking changes :relieved: )

**Comment by brianhyder** [comment]
We've done our best to no break things.  Sometimes it slips through the cracks.  We also try to mark (documentation wise) any deprecated functions.
