### ISSUE TITLE
How to browse my project via EC2 public ip

### ISSUE THREAD

**Issue by owlzage** [pencilblue/pencilblue#1168]
**Description:**
I just installed PB on an AWS EC2 ubuntu instance. The project is running on port 8080 no firewal issues and I am trying to access my site on my browser like: https://[public_IP]:8080
There is nothing in the logs, configuration is default

**Steps to Reproduce:**

**Configuration Details:**

**Log Output:**

PencilBlue Version: 

Node.js Version:6.9.1

Environment Description:ubuntu 14

**Comment by dukeofsussex** [comment]
Have you tried creating a copy of the `sample.config.js` file found in PB's root directory, naming it `config.js` and setting the `siteRoot` to your public IP address + port? Not sure you can run PB under `localhost` on AWS.

**Comment by owlzage** [comment]
Hi dukeofsussex! Thanks for your answer, that solved the issue. I was under the impression that by using https://[public_IP]:8080 that would get localhost (it has worked that way on other projects).

**Comment by dukeofsussex** [comment]
Glad it worked :relieved:
