### ISSUE TITLE
Duplicate Error when clicking on Forgot password Multiple Times

### ISSUE THREAD

**Issue by iamakimmer** [pencilblue/pencilblue#1174]
**Description:**
Clicking on the forgot password twice attempts to reinsert the password reset, with the same user id giving a duplicate error. Also, I think the password reset on a multitenancy site should be coming from the global site's email settings. Otherwise if the subdomain did not do the email setup, the reset password email would not be able to send

**Steps to Reproduce:**
On a subdomain, click on Forgot Password http://subdomain.localhost:8080/admin/login

**Configuration Details:**
Multitenancy is on

**Log Output:**
There was an error saving: E11000 duplicate key error index: mydb.password_reset.$userId_1 dup key: { : "582ddc743a089b2e70d19aab" }

PencilBlue Version: 
0.7.0 with multitenancy
Node.js Version:
4.2
Environment Description:

**Comment by dukeofsussex** [comment]
@iamakimmer I opened a PR with fixes for your issues, would be great if you checked it out to see whether I missed anything. Here's a guide on checkout out PRs locally if you need it: https://help.github.com/articles/checking-out-pull-requests-locally/
