### ISSUE TITLE
Login page "I forgot my password" fails if there is already a pending password reset

### ISSUE THREAD

**Issue by Denal10** [pencilblue/pencilblue#1178]
**Description:**
Query to check for a pending reset does not find any results. Using MongoDB.

**Steps to Reproduce:**
Go to login page click "I forgot my password". Then click again after email was sent. Get error failed to save due to duplicate key.

password_reset_service line 99 userObj.id needs to be userObj.id.toString()

**Configuration Details:**

**Log Output:**

PencilBlue Version: 

Node.js Version:

Environment Description:

**Comment by dukeofsussex** [comment]
Duplicate of #1174

**Comment by brianhyder** [comment]
See #1176
