### ISSUE TITLE
404 error following wiki link to tutorials

### ISSUE THREAD

**Issue by wu-lee** [pencilblue/pencilblue#1179]
**Description:**

The wiki navigation menu has a broken link to the tutorials, leads to a 404 not found.

**Steps to Reproduce:**

* Go to this page: https://github.com/pencilblue/pencilblue/wiki
* Click "Tutorial articles" in the menu on the right.

https://pencilblue.org/section/tutorials
**Configuration Details:**

**Log Output:**

N/A

PencilBlue Version: 

N/A

Node.js Version:

N/A

Environment Description:

N/A

**Comment by dukeofsussex** [comment]
Funny enough, clicking on the `Tutorials` navbar item leads you here: https://github.com/pencilblue/pencilblue/wiki/Quickstart-Guide

**Comment by brianhyder** [comment]
I updated the link to point back to the quick start guide to mimic site behavior

**Comment by wu-lee** [comment]
Just to let you know, there's still a broken link to https://pencilblue.org/section/tutorials in the menu on that page (right hand panel).

**Comment by brianhyder** [comment]
Thank you!  This has now been fixed
