### ISSUE TITLE
Multitenancy documentation clarification request

### ISSUE THREAD

**Issue by wu-lee** [pencilblue/pencilblue#1180]
**Description:**

Following instructions here: https://github.com/pencilblue/pencilblue/wiki/Multi-Tenancy

I'm running into trouble with multitenancy config, possibly because I can't work out exactly what to set in the config. The site settings are (full version attached):

    siteName: "I think this is my root site name",
    siteRoot: "http://example.com:8700",
    sitePort: 8700,
    siteIP: "127.0.0.1",
    multisite: {
        enabled: true,
        globalRoot: 'http://example.com:8700'
    }

My intent is to use Apache to forward connections to the nodejs server listening on localhost:8700.  (I've redacted my actual host and used example.com here, but I can confirm the domain name I used does map to the server IP, and obviously the IP is not 127.0.0.1).

With this I get an error in the log when connecting to the site with 'wget http://localhost:8700':

    "The host (localhost:8700) has not been registered with a site. In single site mode, you must use your site root (http://example.com:8700)."

That the error mentions 'single site' makes me wonder if the 'multisite: true' config is being ignored, but then again the user comments in issue #949 make me think that might be a red herring.

The reason I am confused by the instructions for multisite ([here](https://github.com/pencilblue/pencilblue/wiki/Multi-Tenancy)) are:

* I am setting up a multisite install from scratch - therefore I have no existing sites. I wonder if that is supported, since the wiki page says it: "requires a small amount of prep work before changing the configuration of your PencilBlue installation."
* Assuming the multisite is genuinely enabled (logs don't seem to indicate even in debug level), the config has (apparently mandatory) siteRoot, siteName etc. attributes, with an additional globalRoot defined in the multisite section.  Neither of these specfiy localhost, except indirectly via siteIP: 127.0.0.1.  So I am not sure which settings must match up.

Possibly I could work this out with some more trial and error, but if you could clarify this I'm sure it would help future users.

**Steps to Reproduce:**

* Install as per quickstart instructions.
* Config as given in the multi-tenant page's example, modifications as described above
* Run with npm start. 
* Attempt to wget index page: no content.
* Check error log, to see the error as described

**Configuration Details:**

As described above, otherwise as given in the multi-tenant page's example.

[config.js.txt](https://github.com/pencilblue/pencilblue/files/618649/config.js.txt)

**Log Output:**

[snippet.log.txt](https://github.com/pencilblue/pencilblue/files/618646/snippet.log.txt)

PencilBlue Version: 0.7.0-RC1

Node.js Version: v4.6.2

Environment Description: Debian Wheezy

**Comment by dukeofsussex** [comment]
`multisite.globalRoot` is the url for the global administration. I'd recommend setting it to a subdomain of your site (in this case `http://example.com:8700`)

If you want to access your site via `localhost`, then you also have to set the host part of both `siteRoot` and `globalRoot` to `localhost`

**Comment by wu-lee** [comment]
Thanks, and good to hear there's no need to transition to multi-site via a single-site config.

Just to be clear, I want the nodejs server to listen on 127.0.0.1:8700, but I actually want the website to appear on a public domain, in this example 'example.com', on ports 80/443, via an Apache reverse proxy. The port 8700 will be firewalled, but I'd prefer to listen only on the loopback interface.

I also want to configure this via some automation (in this case, Ansible), so I want avoid needing to use the admin panel to do any of the basic set-up steps (as the guide seems to assume would be normal).  Editing config files or some other command-line interface are preferable.

Anyway, presumably a config including the following settings would get the basic nodejs side working (setting up the reverse proxy being the next step)?

    siteName: "My site name",
    siteRoot: "http://example.com",
    sitePort: 8700,
    siteIP: "127.0.0.1",
    multisite: {
        enabled: true,
        globalRoot: 'http://admin.example.com' // or perhaps http://example.com/admin also works?
   }

If so, am I right in thinking the the siteName/siteRoot attributes here are ignored and/or only visible in the global admin panel, and that the attributes of other sites are configured elsewhere?

**Comment by dukeofsussex** [comment]
> // or perhaps http://example.com/admin also works?
Feel free to try it, but I'm not sure it will.

> If so, am I right in thinking the the siteName/siteRoot attributes here are ignored and/or only visible in the global admin panel, and that the attributes of other sites are configured elsewhere?
`siteName` I'm not sure about, maybe the global site uses it. The `siteRoot` is probably used later on when adding more sites/can be it's own site.

My config file is nearly identical to yours, the only difference is that I didn't bother setting the `siteIP`, as localhost is the default setting. Setting up the proxy can be a bit tricky at times, but otherwise you should be good to go.

Considering automation, here's the standard routine:
* Configure config.js
* Visit `<globalRoot>/setup`
* Create admin account
* Login
* Manage sites
* Do your stuff

Most of this can either be done directly in the DB or calling the endpoints with your data directly, so you should be able to automate most (if not all) of these steps 👍

**Comment by wu-lee** [comment]
I've managed to get something running.

In brief, I conclude:
* siteName is cosmetic, and used to identify the site in the admin panel
* siteRoot is used by the NodeJS virtual host routing, may be used in rendering self-referring URLs
* siteIP/sitePort are what the NodeJS server actually listen on
* globalRoot is used by the virtual host routing... I think

All the *Root settings seem to need URLs with no path.  They shouldn't include port numbers unless that's how you want the public to access these sites.

There will be a single site listed in the panel initially.  This is defined by the siteName/siteRoot settings in the config. I wonder if this site modifiable in the admin panel, although I have some problems with my admin panel and can't yet verify it isn't, perhaps a developer could comment.

The globalRoot can be something like localhost:8700 if you want to access the NodeJS server directly (over an ssh tunnel in my case), and not via a reverse proxy.

However, the "manage sites" admin panel appears to  be visible in *all* my sites, so I'm not certain that's necessary if the default site can be accessed.

Comments welcome. Given more time I may look into a documentation patch, although IIRC pull requests aren't possible with Github wikis.

**Comment by dukeofsussex** [comment]
* Yep, but not only that. It's also the name of the site displayed in the browser tab and attached to the `^site_name^` template flag
* Yep
* Yep
* Yes, but it's mainly the route/url to the global admin panel

The `manage sites` panel is visible on all sites, as it links to the global admin dashboard, which you set under `globalRoot` and which (as the name suggests) manages the sites. Though I'm not sure a single site admin can access the global administration, whilest I know that the inverse works fine.
