### ISSUE TITLE
Can You implement some search tag by headline or subheading on the frontend blog (enhancement)

### ISSUE THREAD

**Issue by ceballos59** [pencilblue/pencilblue#1191]

**Comment by brianhyder** [comment]
Are you asking for a search bar on the blog page for a specific theme?

**Comment by ceballos59** [comment]
Yes. Specific article.headline or authores or some word in
article.description or in article.layout

2016-12-23 12:23 GMT, Brian <notifications@github.com>:

**Comment by brianhyder** [comment]
Search capabilities won't be part of the default themes. However, adding it to your own theme can be accomplished by utilizing the article API. It allows for providing key words to filter down articles by specific properties.
