### ISSUE TITLE
Simplest setup doesnt work

### ISSUE THREAD

**Issue by parliament718** [pencilblue/pencilblue#1199]
**Description:**
Im successfully able to npm start and it tells me 
```ServerInitializer: HTTP server starting, binding on IP 0.0.0.0 and port: 8080```

When I go to 0.0.0.0:8080 am I able to see a pencilblue error message:

The host (0.0.0.0:8080) has not been registered with a site. In single site mode, you must use your site root (http://localhost:8080).

However, going to http://localhost:8080 loads nothing (localhost didn’t send any data)

**Steps to Reproduce:**
pbctrl install [name]
cd [name]
npm start

**Configuration Details:**

```
    "siteRoot": "http://localhost:8080",
    "sitePort": 8080,   
```

**Log Output:**

PencilBlue Version: 0.3.1

Node.js Version: 6.7.0

Environment Description:

**Comment by dukeofsussex** [comment]
Why are you on PB version 0.3.1 or was that a typo?

**Comment by parliament718** [comment]
That's not a typo.  ```pbctrl -v```  gives 0.3.1. 
I assume this is what was install when I did npm install -g pencilblue-cli.
I didn't install any specific versions manually.

What do I need to do to fix this?

**Comment by dukeofsussex** [comment]
Ah yes, the pbctrl package's version is indeed 0.3.1. Sadly I have never used it, so my recommendation would be to just clone pencilblue's master branch directly and work with that.

**Comment by brianhyder** [comment]
I'm looking at it now and seeing something similar.  If you open your config and change it to:

```
{
    "siteRoot": "http://localhost:8087",
    "sitePort": 8087,
}
```

Then navigate to your ```siteRoot``` in your browser does it forward you along to the setup page?

**Comment by brianhyder** [comment]
I tested this on a mac and ran into the same issue.  Not sure what the deal but when I change my siteRoot to "http://127.0.0.1:8080" or "http://localhost:8087" it works fine.  My best guess is that something with the combination of localhost as the host and the port 8080 is causing something funky on at least one of my laptops.  I'm going to attempt to recreate it again tonight on another.

**Comment by parliament718** [comment]
Yeah that worked. Thanks :)

**Comment by brianhyder** [comment]
Glad it worked.  I tested it on another mac this morning and couldn't replicate it.  Would you mind providing a few more details about your environment so we can be on the lookout?

**Comment by parliament718** [comment]
Sure, what info would you like. Im using El Capitan 10.11.6

Come to think of it, I just realized I might have had rethinkdb up at the time, which runs its web interface on 8080. I'd be surprised that it didn't just say "port in use", but I may be wrong and maybe rethink wasn't actually running. I'll test it tonight after work.

**Comment by parliament718** [comment]
Yeah it seems that pencilblue and my rethinkdb service can seemingly both run on 8080 without being aware of each other. In any case rethinkdb always "wins over" the port, and 8080 loads its admin panel and neither is aware the port is already in-use. However, that's not the original issue, as I can stop rethinkdb but pencilblue still dont run on 8080  ¯\_(ツ)_/¯
