### ISSUE TITLE
A cuestion about the Pencilblue Blog limits

### ISSUE THREAD

**Issue by ceballos59** [pencilblue/pencilblue#1201]
Sorry, I have a question that may be obvious: What is the maximum number of articles that can be supported in the pencilblue blog? The system always polls all the published records at once or has a margin. Even in my poor experience, I have not reached a ceiling, but I fear that I have not yet found the mechanism of deferring reading of published articles, in the case of having a considerable number of publications.....And then, I can setup articles per page blog at front-end ?

**Comment by dukeofsussex** [comment]
From a quick look it seems the blog also uses infinitescroll, so there shouldn't be a limit to the amount of articles you have.

**Comment by ceballos59** [comment]
Sorry I did not understand very well, my question is: I do not see that pencilblue reads a subset of articles from the total set of articles ... my question is: do not you ever overflow the blog? That is if I have 10,000 articles, how many will read pencilblue in the first load, as and when I read the following and so on until the end. Also can be configured so that the number of articles "per page" of the blog is a constant? For example the 12 most recent, and that the user can poll the next twelve only on demand?

**Comment by dukeofsussex** [comment]
Have a look at https://github.com/pencilblue/pencilblue/blob/master/plugins/portfolio/controllers/blog.js#L90 You can set the amount of articles per page in the admin panel (default is 5), so it should only load the specified amount. According to the comment, **all** articles are loaded, but only the first *x* are displayed, so you might run into issues later on. But by then we should have PB 1.0 and this will have been fixed.

>Also can be configured so that the number of articles "per page" of the blog is a constant? For example the 12 most recent, and that the user can poll the next twelve only on demand?

Yes, you can find this on `<your-site-root>/admin/site_settings/content`
