### ISSUE TITLE
Custom objects on Multi Tenancy

### ISSUE THREAD

**Issue by LeandroZacarias** [pencilblue/pencilblue#1205]
**Description:**

*When I install the contact form plugin it generates the custom object pb_contact as "global" even when installed with a selected site.*

**Steps to Reproduce:**

*Installing the contact form plugin in a multi tenancy instance of pencilblue, the custom objects management screen stops working, and all contacts are written as global, even if the plugin is installed site by site.*

**Configuration Details:**

*Multi Tenancy*
*Plugin:* https://github.com/pencilblue/contact-pencilblue

**Log Output:**

n/a

PencilBlue Version: 
v0.8.0
Node.js Version:
v7.4.0
Environment Description:
Windows, Linux

**Comment by brianhyder** [comment]
Please file this against the repository for the contact form plugin: 
https://github.com/pencilblue/contact-pencilblue

**Comment by LeandroZacarias** [comment]
Ok, thanx!
