### ISSUE TITLE
Middleware Index out of Bounds

### ISSUE THREAD

**Issue by lgenet** [pencilblue/pencilblue#1209]
**Description:**
I was working on a personal project using PB Saturday/Sunday and I encountered another error, that I was not able to recreate since them.  However, this is not the first time I have ran into this error.  (enough so that I added a small 'patch' to the afflicted area.)

What happened is on line 111 of router.js _handle function (inside the domain.error bit.)  I added the 'UNKNOWN' and might have broken it out into a separate line to accomplish this.   
```
var middleWareName = Router.middleware[self.index] ? Router.middleware[self.index].name : 'UNKNOWN';
```  

Somehow, this error block was called when index was out of bounds of the middleware array.  The steps help to shed a little bit of light on the situation, but not much.

**Steps to Reproduce:**
I hit a route that I defined.  It makes an api call and should get back an array that I would do processing on.  I did not validate the input (That is my bad, this was just a quick prototype.)  Anyway, after calling .length on null, the error above occurred.  

***Supporting Information***
This "programmer error" was caught by the domain's error block in all cases.  Which is the desired behavior, the only part that weirded me out was the fact that on Saturday/Sunday I was getting into a state such that `Router.middleware[self.index]` was not defined, and thus defaulted to 'UNKNOWN'  (without my little 'UNKNOWN' fix, we get a 'can not access name of undefined' error.)

***Impact and possible resolutions***
The impact of this particular error in the capacity that I hit it is low, as it was in the domain's error block which is only called when something else with the request has gone horribly wrong.  

I brought it up mainly due to the worry of "what if it happens elsewhere"  and the underlying cause could be a potential problem later.

As I said, a possible fix is to just default the middleware name to unknown as I showed above, but again that is more so masking this problem as opposed to solving it.  

***Further Questions***
With all of this said, I do have a question on design choice.  I noticed that when Pencilblue 'catches' something in the domain.error bit, it just lets the request (from the client perspective) hang.  On the back end, the error is logged and the promise is rejected.  However, nowhere up the chain do you/we do anything with that rejected promise (like serve an error page to the user.)  

Just wondering why this choice was made.  Again, this type of error only happens when we get an uncaught exception (like when I tried to call the length function on a null variable) so the user impact should be relatively low.  (most of these offending errors, again, should be caught in testing)

**Configuration Details:**
Multi-site, running locally. 

**Log Output: (NEW DATA)**
This is the error that caused me to get dumped into the catch block.  
```
Error: Either plugin [cloudfront] or the service [ManageSSLCertService] does not exist for site [global]
    at Function.module.exports.PluginService.getService (/Users/logenet/Documents/Node Projects/CMSPencilblue/include/service/entities/plugin_service.js:1203:15)
    at /Users/logenet/Documents/Node Projects/CMSPencilblue/plugins/pencilblue_cloudfront/controllers/create_cert.js:21:64
    at /Users/logenet/Documents/Node Projects/CMSPencilblue/include/service/entities/plugin_setting_service.js:173:24
    at /Users/logenet/Documents/Node Projects/CMSPencilblue/include/service/simple_layered_service.js:95:17
    at /Users/logenet/Documents/Node Projects/CMSPencilblue/node_modules/async/lib/async.js:789:30
    at /Users/logenet/Documents/Node Projects/CMSPencilblue/node_modules/async/lib/async.js:167:37
    at /Users/logenet/Documents/Node Projects/CMSPencilblue/include/service/simple_layered_service.js:76:21
    at module.exports.DbEntityService.get.callback (/Users/logenet/Documents/Node Projects/CMSPencilblue/include/service/db_entity_service.js:85:24)
    at /Users/logenet/Documents/Node Projects/CMSPencilblue/include/dao/dao.js:144:12
    at /Users/logenet/Documents/Node Projects/CMSPencilblue/include/dao/dao.js:272:17
    at handleCallback (/Users/logenet/Documents/Node Projects/CMSPencilblue/node_modules/mongodb/lib/utils.js:96:12)
    at /Users/logenet/Documents/Node Projects/CMSPencilblue/node_modules/mongodb/lib/cursor.js:835:16
    at handleCallback (/Users/logenet/Documents/Node Projects/CMSPencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
    at setCursorNotified (/Users/logenet/Documents/Node Projects/CMSPencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:490:3)
    at /Users/logenet/Documents/Node Projects/CMSPencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:561:16
    at Cursor._find.queryCallback (/Users/logenet/Documents/Node Projects/CMSPencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:241:5)
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Callbacks.emit (/Users/logenet/Documents/Node Projects/CMSPencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:116:3)
    at messageHandler (/Users/logenet/Documents/Node Projects/CMSPencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:291:23)
    at Socket.dataHandler (/Users/logenet/Documents/Node Projects/CMSPencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:285:22)
    at emitOne (events.js:77:13)
```

The next problem is that index is currently at 24, which is beyond the end of the middleware loop.  I know this error occurred in InitilizeController which is middleware step 18.  

I am not sure why I suddenly got thrown all the way to step/index 24, (which again, is not a thing since the middleware stack ends at principle close which is step/index 23)

Just thought I would include this new data.

PencilBlue Version: 0.8.0

Node.js Version: 4.2.2

Environment Description:  Mac OSX

**Comment by lgenet** [comment]
I updated the post above with additional data now that I have been able to recreate the issue.

**Comment by lgenet** [comment]
I would also like to not that I tried to recreate this, and got the index out of bounds ONLY when I was not signed into the admin panel and tried to hit an admin panel route.  It took me to the admin panel and then ran into this problem.  When i signed in and tried it when I was already authenticated, I still got hte error but it reflected correctly (step 18 instead of step 24)  

Since UNKNOWN only occurs when we are not authenticated, and have to go to the login page and then get thrown back to our desired admin page with a redirect.  This feels like it is going to be another problem like that one mentioned perviously around the handlers getting overwritten.

**Comment by brianhyder** [comment]
@lgenet I'm working on reproducing this bug.  I'm not having much luck.  I'm curious about one of the pieces of info you passed along.  When you say step 18 is the InitilizeController middleware, how did you determine that?  Looking at the default middleware, index 18 would be the render step.  I'd like to verify that piece of info because my first theory is that maybe your controller's "init" function is calling back before it has completed all of its async function calls.

**Comment by lgenet** [comment]
So i just went back and tried to reproduce this and was able to.  I will include the steps I used this time.  I am inside of a callback when the error is thrown from getService so maybe that is part of the problem?

***Steps to reproduce:***
1.)Create an admin controller with an init.  Inside of that init, include a getService call that fails
```self.myService = new (pb.PluginService.getService('myServiceName', 'giberish', self.site))(self.settings)```
2.) Make sure you are logged out of the admin panel.
3.) Hit the route for your controller (without logging into the admin panel.)
4.) Sign in when you get redirected to login.
5.) This is when the error occurs for me, similar to the issues we fixed a bit ago with the handler getting overwritten, but this time we get an index out of bounds on the middleware stack.

***My Init Function***
```
   util.inherits(MyController, pb.BaseController);

    MyController.prototype.init = function (props, cb) {
        var self = this;
        pb.BaseController.prototype.init.call(self, props, function () {
            var pluginService = new pb.PluginService({site: self.site});
            pluginService.getSettingsKV('myPluginName', function (err, settings) {
                if (pb.util.isError(err)) {
                    return self.reqHandler.serveError(err);
                }

                self.settings = settings || {};

                self.myService = new (pb.PluginService.getService('myServiceName', 'giberish(not my plugin name)', self.site))(self.settings);
                cb();
            });
        });
    };
```

***Middleware Stack***
```‌[{"name":"startTime"},{"name":"urlParse"},{"name":"checkPublicRoute"},{"name":"principal"},{"name":"deriveSite"},{"name":"deriveRoute"},{"name":"deriveActiveTheme"},{"name":"deriveRouteTheme"},{"name":"emitRouteThemeRetrieved"},{"name":"inactiveAccessCheck"},{"name":"systemSetupCheck"},{"name":"requiresAuthenticationCheck"},{"name":"authorizationCheck"},{"name":"derivePathVariables"},{"name":"localizedRouteCheck"},{"name":"instantiateController"},{"name":"parseRequestBody"},{"name":"initializeController"},{"name":"render"},{"name":"writeSessionCookie"},{"name":"writeResponse"},{"name":"responseTime"},{"name":"principalClose"}]
```
In addition
```
Printing self.index yields 23, which is the length of the middleware stack.
‌23
```

**Comment by brianhyder** [comment]
@lgenet Just in case I need it, what version of Node.js are you running?

**Comment by lgenet** [comment]
Node Version: 4.2.2

**Comment by brianhyder** [comment]
@lgenet, just a heads up that I'm having a hard time reproducing.  I'm able to get the controller to error but the domain's error handler doesn't fire.  Instead, the error is picked up by the uncaught exception handler.

I thought the domain behavior might be based on the version of Node.js that was running but it doesn't appear to be.  Are you running off of the CB fork or pure PB?  This one way may need to sync up on a video call to figure out what is going on.

**Comment by lgenet** [comment]
Interesting.  This is running on the CB Fork, but I am doing my best to return us to "Vanilla" as I can :)  0.8.0 has been helping with that.  

Regardless, I have one question for you.  Where is the "uncaught Exception handler?"  Is that just something built into node?  or something that is part of the platform somewhere.  That might be a dumb question but hey ;)

I am fine to do a video call to see whats going on.  Fortunately, this is the least... worrisome?  of the errors thus far :) since it is hard to reproduce and usually caused by developer error, and ya.

**Comment by brianhyder** [comment]
Look in /system/system.js
Node allows you to have a global exception handler that we take advantage
of as a last resort.

Let me try a couple of different things here and if I can't make headway we
can schedule something for next week.

**Comment by brianhyder** [comment]
@lgenet I wasn't able to ever reproduce this one.  Please let me know if you are still bumping up against this one and we can setup a call otherwise I will close out for now.

**Comment by lgenet** [comment]
@brianhyder I am still getting this, but I have to force it.  I do not get this durring normal work flows which is fortunate.  

The only time I get it is when I try to load a service in the init stage of a controller that is for an admin route.  and it only happens when I try and hit the admin page without being signed into the admin panel.  

If I am signed into the admin panel, I get the same error, but the middleware correctly says that I came from the initController step.  If I had to guess, this is an issue where the stack gets out of place because we 401 and then go to login and then get back to this page and the stack doesnt reset properly but that is just a guess.

Like I said, I can only get this when I have a "developer bug"  so it doesnt seem to (at least in this capacity) effect production ready code.  I am not sure if we want to dig further into this at this time or if we want to close out this issue for now.  But I do find it odd that you can not reproduce it but I can.  I will spend some time today to see if I can replicate with a clean install.

**Comment by lgenet** [comment]
I have confirmed that I can not reproduce this error on a vanilla install.  That feels very strange to me.  I assume it probably has something to do with the fact that my custom solution is using a "500.js" error controller (similar to the 401 and 404.js controllers) and that it might be the source of this strange action.  Since it is not directly related to core you can go ahead and close this.  Still think there is something odd going on but I will dig in on my end.  Just wanted to give you that heads up.

Logan
