### ISSUE TITLE
Question/Bug: Init Order

### ISSUE THREAD

**Issue by lgenet** [pencilblue/pencilblue#1210]
**Description:**
This is more so a question that I am very confused by than an out-right bug/issue.  The init stack is as follows.

```            
            util.wrapTimedTask(this, this.initModules, 'initModules'),
            util.wrapTimedTask(this, this.initRequestHandler, 'initRequestHandler'),
            util.wrapTimedTask(this, this.initDBConnections, 'initDBConnections'),
            util.wrapTimedTask(this, this.initDBIndices, 'initDBIndices'),
            util.wrapTimedTask(this, this.initServerRegistration, 'initServerRegistration'),
            util.wrapTimedTask(this, this.initCommandService, 'initCommandService'),
            util.wrapTimedTask(this, this.initSiteMigration, 'initSiteMigration'),
            util.wrapTimedTask(this, this.initSessions, 'initSessions'),
            util.wrapTimedTask(this, this.initPlugins, 'initPlugins'),
            util.wrapTimedTask(this, this.initSites, 'initSites'),
            util.wrapTimedTask(this, this.initLocales, 'initLocales'),
            util.wrapTimedTask(this, this.initLibraries, 'initLibraries'),
            util.wrapTimedTask(this, this.registerMetrics, 'registerMetrics'),
            util.wrapTimedTask(this, this.initServer, 'initServer')
```

So, the initServer is the very last thing that runs in the stack.  Inside of InitServer is when the Middleware stack is built out.  This is after the plugin's get a chance to run their "onStartupWithContext" functions.  In your example code, you suggest swapping out middleware in these blocks.  However, I do not have access to the middleware set at this point.  

Was this the intent?  Based on your blog post (https://gist.github.com/brianhyder/f011cdea8a6cce1128ba6ff86e9a10a1#file-minify-js) with examples of using the new feature I would say that it is not.  Thus I am wondering if I am missing something. 

**Steps to Reproduce:**
N/A

**Configuration Details:**
Multisite, running locally.

**Log Output:**
N/A

PencilBlue Version: 0.8.0

Node.js Version: 4.2.2

Environment Description: OSX

**Comment by brianhyder** [comment]
@lgenet You are correct.  PR coming shortly
