### ISSUE TITLE
Support both www and non-www hostnames simultaneously

### ISSUE THREAD

**Issue by dukeofsussex** [pencilblue/pencilblue#1216]
**Description:**
I know this has been brought up multiple times, but I've now run into this issue when porting our site over to PB. Currently a redirect in our proxy is needed, but my colleagues and I think this should be handled by PB natively.

PencilBlue Version: 0.7.1

Node.js Version: 4.4.5

Environment Description: Win, Linux

**Comment by lgenet** [comment]
This came up a number of times at my work as well where we have the need for site.com to redirect to www.site.com and we ended up in some cases having to build redirect servers that stand on a different stack to do this before they hit PB.  I think it would be a nice feature addition.

**Comment by markbaird** [comment]
The standard way most people do this is to have an Nginx reverse proxy running on the same server as PencilBlue (or any other NodeJS app) that handles redirects like this, as well as static file caching, gzip compression, etc.

**Comment by dukeofsussex** [comment]
@brianhyder I saw you closed this one, but I don't know what the status is. Are there plans on supporting this natively?

**Comment by brianhyder** [comment]
Short answer is maybe. For now, there are workarounds so it won't be
implemented as a patch release. It would be part of 1.0 as a lower
priority. My hope is that it is as easy as adding hostname aliases. Then
the changes are limited to site service and site lookup Middleware.
