### ISSUE TITLE
Address is showing ID instead of page name.

### ISSUE THREAD

**Issue by wasifale** [pencilblue/pencilblue#1219]
I have added pages to navigation and when I click on some page it redirects correctly but the issue is that it shows the ID in address link instead of page name.
![screen shot 2017-02-08 at 1 50 54 pm](https://cloud.githubusercontent.com/assets/15184858/22729772/02cb3908-ee06-11e6-9bb0-3e63abffec49.png)

In the image attached after "**/page/** " there is ID of the page.

**Comment by dukeofsussex** [comment]
This is intended and not a bug/issue as such.

**Comment by wasifale** [comment]
@dukeofsussex Can you guid me a little how to make it work the way I want?

**Comment by dukeofsussex** [comment]
Instead of choosing the `page` option in the navigation panel, you could select `link` and enter it manually (`/page/my-page-name`)

**Comment by wasifale** [comment]
Done .. Thank for your help.
