### ISSUE TITLE
uncaught Exception detected : TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by damo78** [pencilblue/pencilblue#1220]
**Description:**
(Apologies in advance, this is my first GIT issue raising)
PencilBlue, which was started with node forever (sudo forever start pencilblue.js), has stopped working and will not restart.  This is on an AWS Linux instance and since it was working 2 days ago I haven't checked back until today.

**Steps to Reproduce:**
I cannot figure out why it stopped, but when I try to start again I get the same startup error - see log output below.

I have a cloned local dev environment running the exact same code and MongoDB setup which is fully working.  It is only my AWS install that is not working.  I set this up directly on AWS and cloned to local, restoring the MongoDB to a local replica set so everything is/was completely in sync and nothing has changed.

**Configuration Details:**
My app GIT repo is here:
https://github.com/damo78/damo78

`
module.exports = {
    "siteName": "myApp",
    "siteRoot": "myAWSHost",
    "sitePort": 8080,
    "logging": {
        "level": "info"
    },
    "db": {
	"type": "mongo",
        "servers": [
            "mongodb://myMongoDBHost:27000"
        ],
	"name": "clusterdb",
        "writeConcern": 1,
        "query_logging": false
    },
    "cache": {
	"fake": true,
        "host": "localhost",
        "port": 6379
    },
    "settings": {
        "use_memory": false,
        "use_cache": false
    },
    "templates": {
        "use_memory": true,
        "use_cache": false
    },
    "plugins": {
        "caching": {
            "use_memory": false,
            "use_cache": false
        }
    },
    "registry": {
        "type": "redis"
    },
    "session": {
        "storage": "mongo"
    },
    "media": {
	"provider": "mongo",
        "max_upload_size": 6291456
    },
    "cluster": {
        "workers": 1,
        "self_managed": false
    },
    "multisite": {
        "enabled": false,
        "globalRoot": "http://global.localhost:8080"
    }
};
`

**Log Output:**
`
forever -a start pencilblue.js 
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: pencilblue.js
`

The above provide same log output as below in forever.log

```
pbctrl start
The start command is deprecated. Use `npm start` instead.
Override file [/home/ec2-user/myApp/config.js] will be applied.
2017-02-09T23:45:05.474Z - info: [M] SystemStartup: Log Level is: info
2017-02-09T23:45:48.640Z - info: [M] PencilBlue: Ensuring indices...
2017-02-09T23:45:48.887Z - error: [M] System[M]: uncaught Exception detected : TypeError: Cannot read property 'length' of null
    at Function.Util.getTasks (/home/ec2-user/myApp/include/util.js:162:30)
    at /home/ec2-user/myApp/include/dao/db_manager.js:312:34
    at handleCallback (/home/ec2-user/myApp/node_modules/mongodb/lib/utils.js:95:56)
    at /home/ec2-user/myApp/node_modules/mongodb/lib/db.js:916:28
    at handleCallback (/home/ec2-user/myApp/node_modules/mongodb/lib/utils.js:95:56)
    at /home/ec2-user/myApp/node_modules/mongodb/lib/cursor.js:849:22
    at handleCallback (/home/ec2-user/myApp/node_modules/mongodb-core/lib/cursor.js:171:5)
    at /home/ec2-user/myApp/node_modules/mongodb-core/lib/cursor.js:586:22
    at queryCallback (/home/ec2-user/myApp/node_modules/mongodb-core/lib/cursor.js:212:16)
    at /home/ec2-user/myApp/node_modules/mongodb-core/lib/connection/pool.js:455:18
2017-02-09T23:45:49.214Z - info: [M] System[M]: Shutdown complete
Successfully kicked off PencilBlue
```

PencilBlue Version: 
0.3.1
(edit: I cannot seem to find a way to upgrade to a new version, if available, or what versions are available)

Node.js Version:
7.5.0

Environment Description:
AWS linux
MongoDB 3.4.2

**Comment by brianhyder** [comment]
The offending line is just after a call to retrieve the collections available in the DB. That call does not do an error check. My guess is that the call is failing to retrieve the collections. This is usually indicative of the DB user not having sufficient rights to retrieve the list of collections. My suggestion would be to add a line just before to test this theory. The line could be as simple as outputting the error from the call to the console. That would prove whether or not the error was occurring or of there is another issue at play.

**Comment by brianhyder** [comment]
Also, thank you for taking the time to follow the guidelines for submitting issues. It really does make it easier to provide support. So a big thank you for reporting your issue!

**Comment by damo78** [comment]
Thanks for your quick response Brian.  I'll add a line to see what happens (once I've figured out how to :-))

This maybe related to an issue I originally had connecting to MongoDB.  My original connection string was something like:
mongodb://mongo_user:mongo_password@127.0.0.1:27018

I am using MongoDB Atlas/Cloud Manager which has created a replica set on AWS, which is local to my EC2 instance where my app is installed.  I spent many hours trying to get this to work but it wouldn't until I removed the mongo_user:mongo_password from the connection string, after which it worked; probably very insecurely.

Installing PB on AWS is very difficult!

I will try steps to see if this is a MongoDB user access problem as you've suggested, and report back.  If there's any advice you can point me to on how best to connect using my install config then it would be very much appreciated.

Thanks again

**Comment by brianhyder** [comment]
In the current version of PB the connection configuration is not the most
intuitive. We're changing that in the next major version.

When you have questions about configuration you can look at
/include/config.js

It has in line documentation. The "db" section describes how to setup an
authenticated Mongo connection. Essentially, you'll want to provide the
connection string without the credentials. Then in the authentication block
provide the username and password.

On Feb 9, 2017 7:39 PM, "damo78" <notifications@github.com> wrote:

Thanks for your quick response Brian. I'll add a line to see what happens
(once I've figured out how to :-))

This maybe related to an issue I originally had connecting to MongoDB. My
original connection string was something like:
mongodb://mongo_user:mongo_password@127.0.0.1:27018

I am using MongoDB Atlas/Cloud Manager which has created a replica set on
AWS, which is local to my EC2 instance where my app is installed. I spent
many hours trying to get this to work but it wouldn't until I removed the
mongo_user:mongo_password from the connection string, after which it
worked; probably very insecurely.

Installing PB on AWS is very difficult!

I will try steps to see if this is a MongoDB user access problem as you've
suggested, and report back. If there's any advice you can point me to on
how best to connect using my install config then it would be very much
appreciated.

Thanks again

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pencilblue/pencilblue/issues/1220#issuecomment-278823150>,
or mute the thread

**Comment by damo78** [comment]
Excellent, thank you Brian.  This is incredibly helpful.  Given the stage you're at I'm super impressed at the progress so far in terms of documentation and code stability.

I've tried entering the following:
`
"db": {
	"type": "mongo",
        "servers": [
            "mongodb://my_mongodb_host:27000"
        ],
	"name": "clusterdb",
        "writeConcern": 1,
        "query_logging": false,
        "authentication": {
                "un":"my_user",
                "pw":"my_password",
        }
`

I get the same error output.  Do I need to specify any of the options?

Sorry I'm relatively new to JS/node development so haven't figured out how to write the console/trace output you suggested earlier in case that helps.

**Comment by brianhyder** [comment]
I would suggest creating a new line on line 312 of
/include/dao/db_manager.js. Add console.log(err);

This is the file I'm thinking you should modify to check the error.
https://github.com/pencilblue/pencilblue/blob/master/include/dao/db_manager.js#L312

On Feb 9, 2017 8:16 PM, "damo78" <notifications@github.com> wrote:

Excellent, thank you Brian. This is incredibly helpful. Given the stage
you're at I'm super impressed at the progress so far in terms of
documentation and code stability.

I've tried entering the following:
"db": { "type": "mongo", "servers": [ "mongodb://my_mongodb_host:27000" ],
"name": "clusterdb", "writeConcern": 1, "query_logging": false,
"authentication": { "un":"my_user", "pw":"my_password", }

I get the same error output. Do I need to specify any of the options?

Sorry I'm relatively new to JS/node development so haven't figured out how
to write the console/trace output you suggested earlier in case that helps.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pencilblue/pencilblue/issues/1220#issuecomment-278829403>,
or mute the thread

**Comment by damo78** [comment]
(I think I need to upgrade my T2.micro; this is a very slow process :-()

Thanks, I've added the console out at lines 312, 314, 316 (overkill maybe!) 

`
pbctrl start
The start command is deprecated. Use `npm start` instead.
Override file [/home/ec2-user/apps/damo78/config.js] will be applied.
2017-02-10T01:40:20.592Z - info: [M] SystemStartup: Log Level is: info
2017-02-10T01:41:35.991Z - info: [M] PencilBlue: Ensuring indices...
{ MongoError: not master and slaveOk=false
    at Function.MongoError.create (/home/ec2-user/myApp/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/home/ec2-user/myApp/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /home/ec2-user/myApp/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  name: 'MongoError',
  message: 'not master and slaveOk=false',
  ok: 0,
  errmsg: 'not master and slaveOk=false',
  code: 13435,
  codeName: 'NotMasterNoSlaveOk' }
2017-02-10T01:41:36.709Z - error: [M] System[M]: uncaught Exception detected : TypeError: Cannot read property 'length' of null
    at Function.Util.getTasks (/home/ec2-user/myApp/include/util.js:162:30)
    at /home/ec2-user/myApp/include/dao/db_manager.js:313:34
    at handleCallback (/home/ec2-user/myApp/node_modules/mongodb/lib/utils.js:95:56)
    at /home/ec2-user/myApp/node_modules/mongodb/lib/db.js:916:28
    at handleCallback (/home/ec2-user/myApp/node_modules/mongodb/lib/utils.js:95:56)
    at /home/ec2-user/myApp/node_modules/mongodb/lib/cursor.js:849:22
    at handleCallback (/home/ec2-user/myApp/node_modules/mongodb-core/lib/cursor.js:171:5)
    at /home/ec2-user/myApp/node_modules/mongodb-core/lib/cursor.js:586:22
    at queryCallback (/home/ec2-user/myApp/node_modules/mongodb-core/lib/cursor.js:212:16)
    at /home/ec2-user/myApp/node_modules/mongodb-core/lib/connection/pool.js:455:18
2017-02-10T01:41:37.619Z - info: [M] System[M]: Shutdown complete
Successfully kicked off PencilBlue
`

In addition to this I've been trying to connect to 

`mongo` -u mongo_user -p mongo_password'

from the AWS shell, and I'm not able to apply.  So I think your first root cause is probably correct.  I will continue to try figure out why this isn't working.  I hope the above affirms your finding so I know I'm on the right track.

**Comment by brianhyder** [comment]
Im now convinced that I was on the right track but I still don't know root
cause. I've never seen that Mongo error before. I'm also not that familiar
with dealing with replica sets.

Either way I'm interested in what you find out. It will be helpful for
other users.

**Comment by damo78** [comment]
Phew.... it's not just my newbieness.  Ironically, I've been using my AWS PB install to document the 'process as I go' to help other 'not-so-expert' users of all of this, and was going well until it died.  I'll report back my findings and once my PB install is back up (it will happen!!!!), and I'll continue to document; I hope this will help (the AWS/mongoDB bit is a nightmare challenge!).

**Comment by damo78** [comment]
[some sort of] break through:

From the AWS shell, I tried this....

input:
`mongo -u mongo_user -p mongo_password`

result:
`MongoDB shell version v3.4.2
connecting to: mongodb://my_mongo_host:27000/
MongoDB server version: 3.4.2
2017-02-10T01:26:32.882+0000 E QUERY    [thread1] Error: Authentication failed. :
DB.prototype._authOrThrow@src/mongo/shell/db.js:1459:20
@(auth):6:1
@(auth):1:2
exception: login failed`

input:
`mongo my_mongo_host -u mongo_user -p mongo_password`

result:
`
MongoDB shell version v3.4.2
connecting to: mongodb://my_mongo_host:27000/my_mongo_host:27000
2017-02-10T02:12:28.810+0000 E QUERY    [thread1] Error: Failed to parse mongodb:// URL: mongodb://my_mongo_host:27000/my_mongo_host:27000 :
connect@src/mongo/shell/mongo.js:237:13
@(connect):1:6
exception: connect failed`

(worth a try)

Then I tried this....

'
mongo clusterdb -u mongo_user -p mongo_password
'

And I connected via the AWS, which is the first time I've managed to do this.  This is a major success for me regardless of my working with PB.

The clue before the above was in trying this:

input:
'mongo my_mongo_host/clusterdb -u mongo_user -p mongo_password'

result:
`MongoDB shell version v3.4.2
if a full URI is provided, you cannot also specify host or port`

This has led me to thinking my user access is correct and working as it should, and that it may be something within the config that needs to compensate for this type of connection.  At this point I think I'm also out of my depth......

**Comment by damo78** [comment]
Last findings...

In the replica set I have, my connection was to 27000 which I saw in Cloud Manager as secondary.  I changed the PB config.js so that it pointed to the primary 27001, and this is the output I get:
'
pbctrl start
The start command is deprecated. Use `npm start` instead.
Override file [/home/ec2-user/myApp/config.js] will be applied.
2017-02-10T02:43:22.594Z - info: [M] SystemStartup: Log Level is: info
2017-02-10T02:44:54.563Z - info: [M] PencilBlue: Ensuring indices...
null
null
null
null
null
null
...
'

I'm guessing I should try a single instance mongodb and not a replica set.  This will take time so will report back later.

**Comment by damo78** [comment]
I now really cannot explain this.  Since my last post I haven't done anything, but now the PB site is working.  I haven't restarted it since it failed (multiple times 2 days ago).  I presume the node forever daemon has somehow restarted it (I don't know its capabilities).

I can only think this is either some slow MongoDB Cloud Manager deployment and now the authentication has kicked in sometime since 2 days ago, or that the AWS T2.micro has had a breather and can cope again.

I promise I haven't touched it!
