### ISSUE TITLE
Redirection

### ISSUE THREAD

**Issue by wasifale** [pencilblue/pencilblue#1222]
I need to put a redirection login in my code but I don't exactly know where to put it. I want to do something like, when someone enters or hit a url like "https://mystie.com/page1/page2/page3" then it should be redirected automatically to "https://mystie.com/page/page3".
Examples,
"https://mystie.com/page1/page2/page3" to "https://mystie.com/page/page3"
"https://mystie.com/home/page1/" to "https://mystie.com/page/page1"

means the last level of the link should be hitted automatically with a parent "/page/".

**Comment by brianhyder** [comment]
While it is possible it isn't something that the platform currently supports, easily.  Changes to navigation and the removal of the ```/article/``` and ```/page/``` prefixes are slated for our 1.0 release sometime this year.

I would ask your question in our Gitter.im chat: https://gitter.im/pencilblue/pencilblue

Other users might have already made an attempt at something similar.
