### ISSUE TITLE
Plugin Sync Settings

### ISSUE THREAD

**Issue by lgenet** [pencilblue/pencilblue#1223]
**Description:**
On startup, I added a new setting to my details.json file.  I also remove a setting from another details.json file (so two plugins, one had a setting added, the other had a setting removed.)  

It does not appear to be functioning correctly.  My first thought was incorrect and was an issue with my debugger.  I will update this Issue when I get more concrete evidence on what is going on.

**Steps to Reproduce:**

**Configuration Details:**
multi-tenant solution, running on my local box

**Log Output:**
N/A

PencilBlue Version: 0.8.0

Node.js Version: v6.9.1

Environment Description: Mac OSX

**Comment by brianhyder** [comment]
Tried this with the following:

* installed sample to global site (multi-site enabled)
* modified to add a setting
* restarted
* new setting appeared
* removed setting
* restarted 
* setting disappeared as expected

Questions:
* were the plugins installed against the global site and/or child site?
* is the plugin installed against more than 1 site?

**Comment by brianhyder** [comment]
@lgenet Don't have a minute to test it but I had a thought.  If the plugin is installed to a child site then the plugin service instance would need to be scoped to the site.  I *think* that the plugin service instance is shared during plugin initialization at startup.  If this is the case then it is probably scoped to the global site.  That might be why I didn't see it in my test.

**Comment by lgenet** [comment]
There are nearly ten child sites and the plugin is installed one each of the child sites.  I set a breakpoint in webstorm and set it to "fire only when self.site !== 'global' "  The breakpoint did not hit.  It did previous to me adding that condition so I think that might be our culprit.  Great thought!  @brianhyder

**Comment by lgenet** [comment]
Just wanted to say thank you!  This appears to be working again.  I have other bugs on my side now but they are not your worry.  Thank you for the quick turn around.

**Comment by brianhyder** [comment]
Not a problem. Thank you for the report.
