### ISSUE TITLE
Question: Inactive Plugin

### ISSUE THREAD

**Issue by lgenet** [pencilblue/pencilblue#1227]
**Description:**
What causes a plugin to go inactive?  I am having issues where plugins are going inactive and I am not sure as to what causes this or in what all occurrences this can happen. 

PencilBlue Version: 0.8.0

Node.js Version: 6.9.1

Environment Description:

**Comment by brianhyder** [comment]
Plugins will show as inactive if:
* fail to initialize at startup
* fail in the middle of an install
* fail in the middle of an install

Setting the log level to silly should allow you to monitor the initialization sequence for the plugin and site combination. An error should be present in the logs if something happened

**Comment by lgenet** [comment]
Thank you for that tip!  This was an interesting issue that I will record here.  I do not know if this is an 'aws' issue, a 'me' issue, or a 'platform' issue but I will mention it.

We had a package in a plugin called jwt-simple, it required version ^0.3.1 that was in both details.json for that plugin as well as the package.json for that plugin.  At the top level, we had the same dependency listed, but requiring version ^0.4.1 

On deployment, it could install 0.4.1 for it was in the top level, however when the server tried to install the 0.3.1 dependency that was required by the plugin it did not have permission to write to a tmp folder during the npm install and failed. This failure appears to have knocked the plugin inactive.  

I solved the problem by updating all of the dependencies (both in the plugin and the top level) to be version ^0.4.1 so there would not be a version mis-match.  

I don't think this is as much a platform issue as the instances in aws not being able to support the installation that was happening but thought I would at least let you know.

Thank you for your help as always.  I will go ahead and close this question.
