### ISSUE TITLE
Plugin Initisalization

### ISSUE THREAD

**Issue by wasifale** [pencilblue/pencilblue#1228]
Hello Brian,

I'm using "adsense-pencilblue" Plugin, when it goes to the live site it is showing an error message while I'm configuring it. Attaching the screenshot of error.

![screen shot 2017-02-17 at 10 31 18 am](https://cloud.githubusercontent.com/assets/15184858/23053984/f848a95c-f4fe-11e6-9d0e-bedf6bd4953a.png)

I've seen the logs (using log level silly on local), it shows the error 

"2017-02-17T05:12:02.931Z - error: [M] PluginInitializationService:[adsense-pencilblue] failed to initialize: Error: ENOENT: no such file or directory, open '/plugins/adsense-pencilblue/details.json'
    at Error (native)"

Need your help to make it work.
 Thanks.

**Comment by brianhyder** [comment]
does the referenced directory and file exist at the referenced path?

**Comment by wasifale** [comment]
Thanks for your help,
The problem was that when I cloned the plugin it had its own repository, so doing " rm -rf .git " in the plugin directory solved the problem.
