### ISSUE TITLE
Plugin Setting AutoSync

### ISSUE THREAD

**Issue by lgenet** [pencilblue/pencilblue#1229]
**Description:**
Plugins get new settings now and this appears to work correctly.  The problem now is the fact that it does not take into account if a setting has had any modification (ie groups were added to it)  So with the advent of 0.7.0, we can add groups and display names.  I went to add them to my details.json file and it does not effect any pre-existing site.  

```            discrepancy = discrepancy || (details.settings.length !== Object.keys(settings).length);``` 
It appears to be the case due to the fact that this line is the one that determines if there should be any actual syncing.  

Also, I noticed it is odd for us to do all of the work to detect new settings and then not reference it in this check to see if we should sync settings.  

I modified the code as follows

```            
details.settings.forEach(function(setting) {
                var settingName = setting.name;
                var val = settings[settingName];
                if (typeof val === 'undefined') {
                    discrepancy = true;
                    val = setting.value;
                    formattedSettings.push({name: settingName, value: val, displayName: setting.displayName, group: setting.group});
                }
                else {
                    val.group = val.group || setting.group;
                    val.displayName = val.displayName || setting.displayName;
                    formattedSettings.push(val);
                }
            });
```
Thus adding in the new fields on startup if they have been changed since last run.  

Just a thought, I will also keep playing with this and see if I can get a PR open for it. 

**Steps to Reproduce:**
Build a site with the sample plugin
give it settings values (visit that page in the admin panel)
Shut down server, add groups to details.json
start server, and check to see if groups appeared.

**Configuration Details:**
0.8.0 running locally in multisite mode

**Log Output:**
N/A

PencilBlue Version:  0.8.0

Node.js Version: 6.9.1

Environment Description:

**Comment by lgenet** [comment]
I just ended up adding a block to the details.settings.forEach to check for group name changes and displayName changes. 

```                        if(setting.group !== val.group){
                            val.group = val.group || setting.group;
                            discrepancy = true;
                        }
                        else if(settings.displayName !== val.displayName){
                            val.displayName = val.displayName || setting.displayName;
                            discrepancy = true;
                        }```

**Comment by brianhyder** [comment]
@lgenet a big thanks for the report and fix.

**Comment by lgenet** [comment]
Thank you for merging me!
