### ISSUE TITLE
How can I read data From MongoDB

### ISSUE THREAD

**Issue by ArturVasques** [pencilblue/pencilblue#1231]
Hello! I´m a Junior Programmer from Portugal and Im developing a webSite to a large company.
I need to write news and then I need to get the News from MongoDB and show them in a content.
I can´t understand the "Jennifer" Tutorial where that is done.
 I´m using the latest version of PencilBlue.

**Comment by brianhyder** [comment]
There are a couple of ways to interact with the DB.  The first is through the ```SiteQueryService```.  It is an extension of the ```DAO``` prototype that allows for in depth access to the DB for reading and writing data.

The second way is through an individual service.  Some collections such as articles, pages, and topics, to name a few, have their own services that abstract the interaction with the DB.  These services are named after the collection.  For example, ```ArticleServiceV2``` or ```TopicService```.  This is how the themes get at the data.  Documentation for the prototypes can be found [here](https://pencilblue.github.io)

Once the data is retrieved you can include it in the rendering process.  See our youtube video on building themes for that bit.
