### ISSUE TITLE
SEO import

### ISSUE THREAD

**Issue by wasifale** [pencilblue/pencilblue#1238]
Hello,

The question is that is there any automated plugin or possibly some guide to import the meta tags from Wordpress and insert in Pencilblue?

I need all the tags I've used to be set automatically in PB site.

**Comment by brianhyder** [comment]
It might be possible if they are exported as part of the export XML.  Then the wp_import plugin would need to be modified.  To the best of my knowledge there isn't a process or plugin that does this.
