### ISSUE TITLE
Local media upload needs to manually create folders (breaking on Windows)

### ISSUE THREAD

**Issue by DaveAuld** [pencilblue/pencilblue#228]
I tried creating a new article this morning and attempted to upload new image (from media tab). However, it isn't working.

I came out of the article editor, went to the main Media Manager and attempted to upload the images from there, again didn't work.

The console output is throwing out the following error;
{"level":"error","message":"RequestHandler: An error occurred during controller execution. URL=[POST:/actions/admin/content/media/upload_media] ROUTE={\"path\":\"actions/admin/content/media/upload_media\",\"pattern\":\"^/actions/admin/content/media/upload_media[/]{0,1}$\",\"path_vars\":{},\"expression\":{},\"themes\":{\"pencilblue\":{\"POST\":{\"method\":\"POST\",\"path\":\"/actions/admin/content/media/upload_media\",\"access_level\":1,\"auth_required\":true,\"content_type\":\"text/html\"}}}}\nError: ENOENT, open 'C:\Users\Administrator\desktop\node_projects\pb-dma\public\media\2014\9\540ae62ebc6b451825000010-1410000430988.jpg'","timestamp":"2014-09-06T10:47:10.988Z"}

Any ideas?

**Comment by AnibalFlores** [comment]
If you try to add a user´s photo BEFORE any media in a fresh pencilblue installation the buttons "Link to image..." and "Upload image..." open dialogs simply don´t work

**Comment by JahlomP** [comment]
Check the browser's console to check if you are getting an angular
photocontroller  error or something.
