### ISSUE TITLE
SEO Improvements suggestion

### ISSUE THREAD

**Issue by northonnet** [pencilblue/pencilblue#392]
Hi guys, I´m new on node and mongo and still can´t know how to create plugins (I´m doing changes with hard coding, but studying to create plugins and do the things on right way), but I have suggestions for SEO improvements (I´m SEO of a big Brazillian agency (CASA - JWT Group)).

1 - Remove keywords meta tag, isn´t not effective for rankings, long time.
2 - Alt tag option for all the images.
3 - Canonical field option for the articles, pages and section.
4 - Title and descriptions for sections (currently the description comes from the first article)
5 - Add a robots.txt (root directory)
6 - Add a dynamic xml sitemap

robots sample:
User-agent: *
Disallow: 
Disallow: /admin
Sitemap: http://{root-url}/Sitemap.xml

http://www.sitemaps.org/protocol.html

Thanks for pencilblue Blake and company, it´s awesome.

**Comment by blakecallens** [comment]
Removed keywords, added alt tag, section titles and descriptions are now correct, and added a robots.txt file.

Canonical URLs are something we'll tackle later on.

**Comment by northonnet** [comment]
Great improvements.


If you need any help on SEO questions, please, let me know.

Thanks =)

**Comment by ticidesign** [comment]
Did you know how to add a robots.txt (root directory)? I couldn't find anything about this topic in the documentation.

**Comment by brianhyder** [comment]
There is not a built in way to provide a robots.txt file.  The suggested way to do it would be to create a controller that registers the route ```/robots.txt``` and provides the response that way.  The controller can either read in an actual robots.txt file and pipe it out as the response or it can provide some hard coded values.
