### ISSUE TITLE
[PluginFramework] Plugins do not specify what versions of PB they are compatible with

### ISSUE THREAD

**Issue by brianhyder** [pencilblue/pencilblue#41]

**Comment by brianhyder** [comment]
Plugins should be able to specify what versions of PB they are compatible with by specifying a property in details.json.  

If a property is not specified it should be assumed to work with any version.  
When a property is specified it should be validated as a valid semantic version expression by the validation code in the plugin validator.  
A check should exist at startup to ensure that when a plugin is being initialized at startup it is still compatible with the current version of PB.

**Comment by brianhyder** [comment]
The UI should not allow for a plugin to be installed if the version is not compatible.  
The install plugin API call should send a 400 status when an attempt to install a plugin is made that is not compatible with the current system core.

**Comment by JahlomP** [comment]
can it be closed?
