### ISSUE TITLE
Font-Awesome icons extension 

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#415]
I'm creating a theme plugin and I've created a top level Admin nav like its showcased in the sample plugin.

I have an icon font of the company's logo and to use it, I just have to drop this, ``<i class="icon-8783893"></i>`` onto the page.

I want to use this icon in the admin section for the icon that appears on the top level Admin nav for the theme plugin I've created. 

Since this feature only supports font-awseome's icons like this,
       `` icon: "cogs"`` OR `` icon: "home"``, I was wondering if there is a way around to use a custom made icon font

**Comment by blakecallens** [comment]
You could have your plugin override the admin/head.html template where font-awesome is being loaded and add your added CSS there.

**Comment by JahlomP** [comment]
ok, thanks.
