### ISSUE TITLE
Custom Objects admin page: Forms failing validation don't always tell the user what's going on

### ISSUE THREAD

**Issue by iv597** [pencilblue/pencilblue#418]
>Note: The server in question is currently running the latest commit from PB master that we've tested, 9b74129 (which was somewhere near the release of 0.3, maybe a bit later if I recall), meaning if this was fixed at any point in December, this is likely invalid and we'll need to investigate updating the release being run on the server.

We have a Custom Object structure that has a column `old_id` for the id of the object in the old database (before migration to PencilBlue). Newly-created objects will not have this field as they were not imported. This is causing the newly-created objects to be unable to be modified (saved), because the form is expecting a value in this field of some variety, but the field is blank. The UI never tells the user that this field is expected, and therefore clicking the Save button silently fails and the user is confused as to why they cannot save the object.

Discovering the culprit field is thankfully simple for us developers: `$(".ng-invalid")` returns the following on the page in question:

```
$(".ng-invalid")
[<form name=​"objectForm" ng-submit=​"saveObject()​" novalidate class=​"ng-pristine ng-invalid ng-invalid-number">​…​</form>​,
<input type=​"number" class=​"form-control ng-pristine ng-invalid ng-invalid-number" ng-model=​"customObject[field.name]​">​]
```

On a page with a valid `old_id` column entry, there are no DOM objects classified as `ng-invalid` (the jQuery request returns a blank array), meaning those Custom Objects are passing validation.

Workaround for the time being would be to tell users to input some ridiculous and unused value (999999999, perhaps) in the `old_id` column, but ideally form validation should pick up on this.

**Comment by blakecallens** [comment]
Weird that the entry is tripping form validation, since only the name field is supposed to be required. I'll take a look. As for your specific issue, do you still need old_id to be there at this point? Deleting it from the object definition should be the quickest way to solve this.

**Comment by iv597** [comment]
For the site in question I removed the definition; this bug report was mostly for completeness' sake.

**Comment by blakecallens** [comment]
I'm unable to reproduce this error with the latest version of PB. I created an object type with a number field called old_id. I can create objects with and without that field filled out.
