### ISSUE TITLE
Parent Navigation Item Dropdown not displaying any pages

### ISSUE THREAD

**Issue by caseyctg** [pencilblue/pencilblue#421]
I've added items to my navigation and am trying to set a parent nav item. However, the dropdown is blank and doesn't seem to be working. I'm able to add regular nav items, but cannot set a parent for them as needed. 

![screen shot 2015-01-06 at 4 04 33 pm](https://cloud.githubusercontent.com/assets/4631889/5637074/7ea20096-95bd-11e4-8fd0-f30683107a48.png)

**Comment by caseyctg** [comment]
My mistake, I didn't realize I had to use a parent container. Sorry, I'm a noob w/ pencilblue! Still learning...

**Comment by brianhyder** [comment]
No worries. We're happy to help. Let us know of you have any other issues.

**Comment by caseyctg** [comment]
I did have one other bug I will detail in another issue. I imported content from wordpress. The import went smooth, however after the import, pages will no longer delete. I'll provide screens tomorrow and open a new issue.

**Comment by yasirrafiq33** [comment]
can you just explain how to make parent of page?So that our link become parent/child ..
Thanks

**Comment by brianhyder** [comment]
@yasirrafiq33 Navigation is only 2 levels deep. You must add a container nav item and then put the page inside of it.  You cannot create a hierarchy of pages with the current navigation framework.

**Comment by yasirrafiq33** [comment]
Good!
Can you just tell me about how can I manage custom CSS HTML means front-view according to me.
