### ISSUE TITLE
Question about Media/Proxy

### ISSUE THREAD

**Issue by weaverhe** [pencilblue/pencilblue#424]
Hey guys,

So another question. Here's how I've got our site set up:
- on a server with IP address xx.xxx.xx.xxx
- site root is http://xx.xxx.xx.xxx:4321
- site port is 4321
- in the config file, "siteIP" is 0.0.0.0

With this config, you can view the site directly at the IP xx.xxx.xx.xxx:4321, in order to log into the admin panel. However, the place we'll actually be sending traffic to is domain.com/pbsite/ .. I've got a location block in my nginx.conf file for the server to proxy the content:
     location /pbsite {
         proxy_pass http://0.0.0.0:4321
     }

I've been able to get all of the content to load correctly, except for the /media folder which means all images are broken in the posts. Do you know a work-around that I can implement to achieve the desired results, getting the images to load at domain.com/pbsite/? It would be ok if images were broken at the IP address, as long as they load correctly in the customer-facing content.

Thanks!

**Comment by blakecallens** [comment]
This is @brianhyder 's domain, so I'll defer to him on this one.

**Comment by brianhyder** [comment]
I'm not that familiar with nginx but I think I can ask a few questions to maybe get things moving.  

If you use all zeros it means the HTTP server is binding to any address (will accept connections from any IP address used by the server).  I would try a couple of things.

1. Try binding to 127.0.0.1 and updating the nginx config accordingly. 
2. What media provider do you have configured?
3. What URL is being requested from the browser for the media?
4. What response code and headers are being returned if you hit the URL through the proxy vs. hitting the PB instance directly?  Do they differ?

My guess is that we aren't properly handling the URLs back to media properly but I can't be certain just yet.  

Hopefully some of the above helps.

**Comment by weaverhe** [comment]
Hey Brian,

1 - If I bind to 127.0.0.1, I can no longer access the backend for the site. I'm accessing admin via the server IP, rather than at the proxied domain. Leaving it at 0.0.0.0 keeps the admin available.

2 - The default media provider, whatever is out of the box.

3 - The request URL on the domain is domain.com/media/2014/12/~.png .. It's not nested under the subdirectory, just under the parent domain, but even if I change the url to /pbsite/media/2014/12/~.png it doesn't work.

4 - 

Headers via proxy - 

content-encoding:gzip
content-type:text/html
date:Wed, 07 Jan 2015 22:16:36 GMT
server:NetDNA-cache/2.2
status:404 Not Found
version:HTTP/1.1

Headers via pb instance - 

accept-ranges:bytes
cache-control:max-age=604800
content-length:1196
content-type:image/png
date:Wed, 07 Jan 2015 22:21:30 GMT
expires:Wed, 14 Jan 2015 22:21:30 GMT
last-modified:Wed, 07 Jan 2015 16:48:11 GMT
server:NetDNA-cache/2.2
status:200 OK
version:HTTP/1.1
x-cache:HIT

**Comment by brianhyder** [comment]
Ok, one more thing to try for me to get a bit more info.  In your config.js file set the:
```
log_level: "debug"
```
and then restart PB.
Hit the URL for the media again through the ngix proxy and then look in the logs for a statement that looks like (obviously you'll be looking for "media" in the path instead): 
```
2015-01-07T03:02:06.935Z - debug: [M] Response Time: 20ms URL=[DELETE]/actions/admin/content/pages/54924b6658aabe0000f3b8de CODE=200
```
See if it matches what you would expect for the incoming URL.

**Comment by weaverhe** [comment]
Hey, so we ended up hosting our images elsewhere, and hard-coding the links to them, so that we can always just keep the same links regardless of how the site is modified in the future. Thanks for looking into this with me!

**Comment by blakecallens** [comment]
@weaverhe let us know when the site's up. We'd really like to see what you've accomplished with the platform!

**Comment by weaverhe** [comment]
Hey there! Phase 1 is live at https://www.maxcdn.com/one/

On January 9, 2015 at 9:45:31 AM, Blake Callens (notifications@github.com) wrote:

@weaverhe let us know when the site's up. We'd really like to see what you've accomplished with the platform!

**Comment by blakecallens** [comment]
Wow! Great work, Heather!

If you're company doesn't mind, we'd love to feature this on the site.

**Comment by blakecallens** [comment]
Oh, and as your team works with the admin section, be sure to let us know how we can improve it.

**Comment by weaverhe** [comment]
Thanks guys!

So I will ask my boss about featuring our site on your site and let you know - hit me up about it again if I never get back to you ;)

Feature wise, here are some things we’d like to see:

1 - Image previews. It’s really confusing to add media to posts the way it is, having image previews would make that a LOT easier.

2 - The ability to change the post author. So we have a content editor, who typically adds the posts. However it would be nice if he could give the author-ship credit to the appropriate user. A simple dropdown in the article page to change the author would be awesome!

3 - Topic links - instead of sending the topic links to the topic id, it would be awesome to send them to /topic/topic-name/ .. That way the URLs make a bit more sense. Perhaps this is already possible and I just don’t know how?

Also, another question. Somehow I’ve managed to break the 404 page showing up under /tutorial/ on our site. I replaced /article/ with /tutorial/ in our controllers, but now if I go to https://www.maxcdn.com/one/tutorial/tutorial-does-not-exist/ I get this error:

Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters - VALUE=['asdf’]

I’ve just got our site running on a heavily modified version of the portfolio theme, and can provide whatever code might help troubleshoot. Thanks guys!

On January 9, 2015 at 12:06:09 PM, Blake Callens (notifications@github.com) wrote:

Oh, and as your team works with the admin section, be sure to let us know how we can improve it.

**Comment by weaverhe** [comment]
Oh, one more thing. The admin panel can get a bit … freezy sometimes. Usually it happens when I try to copy and paste in a long article, or edit a really long article. Happy to provide more info as needed about that.

On January 9, 2015 at 5:08:18 PM, Heather Weaver (heather@hweaver.com) wrote:

Thanks guys!

So I will ask my boss about featuring our site on your site and let you know - hit me up about it again if I never get back to you ;)

Feature wise, here are some things we’d like to see:

1 - Image previews. It’s really confusing to add media to posts the way it is, having image previews would make that a LOT easier.

2 - The ability to change the post author. So we have a content editor, who typically adds the posts. However it would be nice if he could give the author-ship credit to the appropriate user. A simple dropdown in the article page to change the author would be awesome!

3 - Topic links - instead of sending the topic links to the topic id, it would be awesome to send them to /topic/topic-name/ .. That way the URLs make a bit more sense. Perhaps this is already possible and I just don’t know how?

Also, another question. Somehow I’ve managed to break the 404 page showing up under /tutorial/ on our site. I replaced /article/ with /tutorial/ in our controllers, but now if I go to https://www.maxcdn.com/one/tutorial/tutorial-does-not-exist/ I get this error:

Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters - VALUE=['asdf’]


I’ve just got our site running on a heavily modified version of the portfolio theme, and can provide whatever code might help troubleshoot. Thanks guys!

On January 9, 2015 at 12:06:09 PM, Blake Callens (notifications@github.com) wrote:

Oh, and as your team works with the admin section, be sure to let us know how we can improve it.

**Comment by brianhyder** [comment]
Whenever you see the error about ```Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters - VALUE=['asdf’]``` it means that an invalid ID string was passed into query that attempts to load by ID.  This is Mongo's ObjectID prototype that rejects the string value that was passed to its constructor.  

You can avoid the error by inspecting the ID string value before it is passed off in a query by doing: 

```
if (!pb.validation.isIdStr(value, true)) {
  //send 400 or 404 here
}
```

**Comment by blakecallens** [comment]
Thanks, Heather! Obviously, having you guys on board is *huge* for a nascent platform like ours. :)

1. Are you using "Link to Media" to add your images as media objects? Since you're hosting them on another server, you can just paste in the URL and you should get previews just fine.
2. We've had several people ask for the ability to change authors. Expect it in the not too distant future. It'll probably be limited to EDITOR access and above.
3. You can modify the theme to handle topics by name, just like we do articles and pages by url or UID. Here's a quick crack at modifying [blog_filter.js starting at line 21](https://github.com/pencilblue/pencilblue/blob/master/plugins/portfolio/controllers/blog_filter.js#L21). I'm going to try running this later today, but if you get to it first, let me know if this works, and I'll merge it into portfolio.

```JavaScript
    var fieldToMatch = 'url';
    var objectType = 'section';

    if(self.req.url.indexOf('/preview/') > -1) {
        self.req.pencilblue_preview = this.pathVars.id;
        if(self.req.url.indexOf('/article/') > -1) {
            self.req.pencilblue_article = this.pathVars.id;
        }
        else if(self.req.url.indexOf('/page/') > -1) {
            self.req.pencilblue_page = this.pathVars.id;
        }

        BlogFilter.super_.prototype.render.apply(self, [cb]);
        return;
    }
    else if(self.req.url.indexOf('/article/') > -1) {
        objectType = 'article';
    }
    else if(self.req.url.indexOf('/page/') > -1) {
        objectType = 'page';
    }
    else if(self.req.url.indexOf('/topic/') > -1) {
        fieldToMatch = 'name';
        objectType = 'topic';
    }
```

As for the freezy part, I'll try to reproduce. If not, I'll be back with some questions. Thanks again!

**Comment by weaverhe** [comment]
Ok, got the topics loading at the name instead of string. Worked as is. Thanks! As a future improvement, it would be nice to have in addition to the name and id for each topic, to also have a field for the topic slug. For SEO purposes (and usability purposes), I'd say you should load each topic with the name in the URL by default but then that requires a specific type of validation. Having a separate slug would be great, and allow whatever display names I might want for the topics.

For the image preview, yeah now that we're hosting them on a separate server it's easy enough to get the previews. However, what I was specifically talking about was where you associate media with the post, and where you add the media to the post. It's confusing, especially if the image name isn't clear, and it would be a lot easier to find and associate media if there were some sort of preview. Not a huge priority, but a definite nicety.

@brianhyder Can you help me out a bit more with the 404 thing? Mostly I'm just unsure of when I'm supposed to run that validation, and in which file that would be? Could you give me an example with the portfolio theme perhaps?

**Comment by brianhyder** [comment]
@weaverhe Sure.  So if you look at [this](https://github.com/pencilblue/pencilblue/blob/master/plugins/pencilblue/controllers/actions/admin/content/articles/delete_article.js#L32) controller you can see how we used the validation check to ensure that the ID that was passed was a valid object id.  

In your case you would want to put the check in the controller that is triggering the error.

**Comment by blakecallens** [comment]
We used to have a preview link on the media items for association but, when we moved to an AngularJS drag and drop library, it overrode anchor tags in draggable items. I'll see if I can find a workaround, because I'd like that back too.

**Comment by weaverhe** [comment]
@blakecallens - Cool, I'm gonna build out that slug plugin hopefully in the near future. I've got one irksome tag I'd really like it for haha.

@brianhyder  Thanks for that example - is there validation built in to check if it's a valid custom-url value? I'm not loading the articles via the object id, I'm loading them via the custom-url.

**Comment by brianhyder** [comment]
Not necessarily a validation but we do have a service that checks for that sort of thing.  Check out the [UrlService's](https://github.com/pencilblue/pencilblue/blob/master/include/service/entities/url_service.js#L64) ```existsForType``` function.

**Comment by weaverhe** [comment]
Hm. For some reason I'm getting an error:

TypeError: Object function UrlService() {} has no method 'existsForType'

If I print out a variable set to pb.UrlService, I get:

{ [Function: UrlService]
  exists: [Function],
  urlJoin: [Function],
  getCustomUrl: [Function],
  isExternalUrl: [Function],
  isFullyQualifiedUrl: [Function] }

Which is every function associated with UrlService except the one I'm going for :(

**Comment by brianhyder** [comment]
```existsForType``` is a prototype function.  Try this:

```
var urlService = new pb.UrlService();
urlService.existsForType('SOME TYPE HERE', function(err, exists) {
  
//continue code here
})
```
