### ISSUE TITLE
Ability to associate a Custom Object with an Article?

### ISSUE THREAD

**Issue by iv597** [pencilblue/pencilblue#427]
I'm aware this is probably far out in wishlist territory for most people, but this would be useful for, for example looking up all articles associated with a city, company, or any other use of Custom Objects

**Comment by brianhyder** [comment]
You can setup a child relationship between a custom object and an article
now. Do you mean that you'd like an easier way to create that relationship
from the other side?

**Comment by iv597** [comment]
Correct, so that when an article is authored you can quickly associate the object with that article.

**Comment by brianhyder** [comment]
This is something that would need to be a custom Article and/or page template and controller because we wouldn't know which custom object to associate.
