### ISSUE TITLE
sidenav help

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#428]
@brianhyder, Is something wrong with the code below? because it seems not to register the sidenav directive. because its not displaying in the template

```
News.prototype.render = function(cb) {
    var self = this;

    //determine and execute the proper call
    var section = self.req.pencilblue_section || null;
    var topic   = self.req.pencilblue_topic   || null;
    var article = self.req.pencilblue_article || null;
    var page    = self.req.pencilblue_page    || null;

    pb.content.getSettings(function(err, contentSettings) {
        self.gatherData(function(err, data) {
            ArticleService.getMetaInfo(data.content[0], function(metaKeywords, metaDescription, metaTitle) {
                self.ts.registerLocal('meta_keywords', metaKeywords);
                self.ts.registerLocal('meta_desc', data.section.description || metaDescription);
                self.ts.registerLocal('meta_title', data.section.name || 'Company Name');
                self.ts.registerLocal('page_name', 'News');
                self.ts.registerLocal('company_name', 'Company Name');
                self.ts.registerLocal('meta_lang', localizationLanguage);
                self.ts.registerLocal('current_url', self.req.url);
                self.ts.registerLocal('navigation', new pb.TemplateValue(data.nav.navigation, false));
                self.ts.registerLocal('account_buttons', new pb.TemplateValue(data.nav.accountButtons, false));
                self.ts.registerLocal('infinite_scroll', function(flag, cb) {
                    if(article || page) {
                        cb(null, '');
                    }
                    else {
                        var infiniteScrollScript = pb.js.includeJS('/js/infinite_article_scroll.js');
                        if(section) {
                            infiniteScrollScript += pb.js.getJSTag('var infiniteScrollSection = "' + section + '";');
                        }
                        else if(topic) {
                            infiniteScrollScript += pb.js.getJSTag('var infiniteScrollTopic = "' + topic + '";');
                        }

                        var val = new pb.TemplateValue(infiniteScrollScript, false);
                        cb(null, val);
                    }
                });
                self.ts.registerLocal('articles', function(flag, cb) {
                    var tasks = pb.utils.getTasks(data.content, function(content, i) {
                        return function(callback) {
                            if (i >= contentSettings.articles_per_page) {//TODO, limit articles in query, not through hackery
                                callback(null, '');
                                return;
                            }
                            self.renderContent(content[i], contentSettings, data.nav.themeSettings, i, callback);
                        };
                    });
                    async.parallel(tasks, function(err, result) {
                        cb(err, new pb.TemplateValue(result.join(''), false));
                    });
                });
                self.ts.registerLocal('page_name', function(flag, cb) {
                    var content = data.content.length > 0 ? data.content[0] : null;
                    self.getContentSpecificPageName(content, cb);
                });

                self.getSideNavigation(data.content, function (sideNavTemplate, sideNavItems) {
                    self.ts.load(sideNavTemplate, function (err, sideNavTemplate) {
                        // if there is an error loading template, assign an 
                        // empty string to sideNavTemplate
                        if(util.isError(err)) {
                            sideNavTemplate ='';
                        }  

                        // register a directive for side_nav
                        self.ts.registerLocal('side_nav', new pb.TemplateValue(sideNavTemplate, true));
                    });

                    

                    self.getTemplate(data.content, function(err, template) {
                        if (util.isError(err)) {
                            throw err;
                        }

                        self.ts.registerLocal('angular', function(flag, cb) {

                        var objects = {
                            trustHTML: 'function(string){return $sce.trustAsHtml(string);}',
                            sideNavItems: sideNavItems
                        };
                        var angularData = pb.js.getAngularController(objects, ['ngSanitize']);
                            cb(null, angularData);
                        });
                            
                        self.ts.load(template, function(err, result) {
                            if (util.isError(err)) {
                                throw err;
                            }

                            cb({content: result});
                        });
                    });
                });
            });
        });
    });
};

**Comment by brianhyder** [comment]
It looks ok accept for: ```self.ts.registerLocal('side_nav', new
pb.TemplateValue(sideNavTemplate, true));```. You probably want to change
the second parameter to false. You might also want to ensure that the
"side_nav" template flag is actually in the templates getting pulled. You
can look in the templates or set the log_level in config.js to "silly". It
will print out all template flags that it encounters while rendering the
page.

On Mon, Jan 12, 2015 at 3:29 AM, Precious Jahlom Agboado <
notifications@github.com> wrote:

> @brianhyder <https://github.com/brianhyder>, Is something wrong with the
> code below? because it seems not to register the sidenav directive. because
> its not displaying in the template
>
> ```News.prototype.render = function(cb) {
> var self = this;
>
> //determine and execute the proper call
> var section = self.req.pencilblue_section || null;
> var topic   = self.req.pencilblue_topic   || null;
> var article = self.req.pencilblue_article || null;
> var page    = self.req.pencilblue_page    || null;
>
> pb.content.getSettings(function(err, contentSettings) {
>     self.gatherData(function(err, data) {
>         ArticleService.getMetaInfo(data.content[0], function(metaKeywords, metaDescription, metaTitle) {
>             self.ts.registerLocal('meta_keywords', metaKeywords);
>             self.ts.registerLocal('meta_desc', data.section.description || metaDescription);
>             self.ts.registerLocal('meta_title', data.section.name || 'Company Name');
>             self.ts.registerLocal('page_name', 'News');
>             self.ts.registerLocal('company_name', 'Company Name');
>             self.ts.registerLocal('meta_lang', localizationLanguage);
>             self.ts.registerLocal('current_url', self.req.url);
>             self.ts.registerLocal('navigation', new pb.TemplateValue(data.nav.navigation, false));
>             self.ts.registerLocal('account_buttons', new pb.TemplateValue(data.nav.accountButtons, false));
>             self.ts.registerLocal('infinite_scroll', function(flag, cb) {
>                 if(article || page) {
>                     cb(null, '');
>                 }
>                 else {
>                     var infiniteScrollScript = pb.js.includeJS('/js/infinite_article_scroll.js');
>                     if(section) {
>                         infiniteScrollScript += pb.js.getJSTag('var infiniteScrollSection = "' + section + '";');
>                     }
>                     else if(topic) {
>                         infiniteScrollScript += pb.js.getJSTag('var infiniteScrollTopic = "' + topic + '";');
>                     }
>
>                     var val = new pb.TemplateValue(infiniteScrollScript, false);
>                     cb(null, val);
>                 }
>             });
>             self.ts.registerLocal('articles', function(flag, cb) {
>                 var tasks = pb.utils.getTasks(data.content, function(content, i) {
>                     return function(callback) {
>                         if (i >= contentSettings.articles_per_page) {//TODO, limit articles in query, not through hackery
>                             callback(null, '');
>                             return;
>                         }
>                         self.renderContent(content[i], contentSettings, data.nav.themeSettings, i, callback);
>                     };
>                 });
>                 async.parallel(tasks, function(err, result) {
>                     cb(err, new pb.TemplateValue(result.join(''), false));
>                 });
>             });
>             self.ts.registerLocal('page_name', function(flag, cb) {
>                 var content = data.content.length > 0 ? data.content[0] : null;
>                 self.getContentSpecificPageName(content, cb);
>             });
>
>             self.getSideNavigation(data.content, function (sideNavTemplate, sideNavItems) {
>                 self.ts.load(sideNavTemplate, function (err, sideNavTemplate) {
>                     // if there is an error loading template, assign an
>                     // empty string to sideNavTemplate
>                     if(util.isError(err)) {
>                         sideNavTemplate ='';
>                     }
>
>                     // register a directive for side_nav
>                     self.ts.registerLocal('side_nav', new pb.TemplateValue(sideNavTemplate, true));
>                 });
>
>
>
>                 self.getTemplate(data.content, function(err, template) {
>                     if (util.isError(err)) {
>                         throw err;
>                     }
>
>                     self.ts.registerLocal('angular', function(flag, cb) {
>
>                     var objects = {
>                         trustHTML: 'function(string){return $sce.trustAsHtml(string);}',
>                         sideNavItems: sideNavItems
>                     };
>                     var angularData = pb.js.getAngularController(objects, ['ngSanitize']);
>                         cb(null, angularData);
>                     });
>
>                     self.ts.load(template, function(err, result) {
>                         if (util.isError(err)) {
>                             throw err;
>                         }
>
>                         cb({content: result});
>                     });
>                 });
>             });
>         });
>     });
> });
>
> };
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/428>.
>



-- 
Brian P. Hyder

**Comment by JahlomP** [comment]
why false? since true means registered successfully according to the docs

**Comment by brianhyder** [comment]
The second parameter should be false. The return value from the function
should be true.

**Comment by JahlomP** [comment]
```
 dao.q('article', opts, function(err, relatedArticles) {
            if(relatedArticles.length === 0) {

                opts = {
                    where: pb.DAO.ANYWHERE,
                    order: {name: 1}
                };
                dao.q('topic', opts, function(err, topicObjects) {
                    var articleTopics = [];
                    for(var i = 0; i < topics.length && articleTopics.length < 20; i++) {
                        for(var j = 0; j < topicObjects.length; j++) {
                            if(ObjectID(topics[i]).equals(topicObjects[j]._id)) {
                                articleTopics.push(topicObjects[j]);
                                topicObjects.splice(j, 1);
                                break;
                            }
                        }
                    }

                    for(i = 0; i < topicObjects.length && articleTopics.length < 20; i++) {
                        articleTopics.push(topicObjects[i]);
                    }

                    cb('elements/side_nav/topics', articleTopics);
                    console.log(articleTopics)
                });
                return;
            }

            cb('elements/side_nav/related_articles', relatedArticles);
```

the articleTopics here: ```cb('elements/side_nav/topics', articleTopics);``` seems to be an empty array

**Comment by JahlomP** [comment]
I found a way to get what I want. thanks for the help.
