### ISSUE TITLE
Error with standalone templates

### ISSUE THREAD

**Issue by tangledpixel** [pencilblue/pencilblue#431]
To recreate: 

1. Install portfolio plugin
2. Create page
3. Select Portfolio:Blog standalone template
4. attempt to load page. 

Error: Failed to find a matching template for location: portfolio

**Comment by brianhyder** [comment]
Confirmed and looking into it

**Comment by brianhyder** [comment]
@tangledpixel  This issue has been fixed and merged to master.  You will need to uninstall and reinstall plugin and then reselect the template for the page and save it.

**Comment by tangledpixel** [comment]
I was also having that same issue on my own plugin template. What is the fix?

**Comment by brianhyder** [comment]
Here is a [link](https://github.com/pencilblue/pencilblue/pull/433) to the PR.  You shouldn't have the issue in your theme unless you override the ```page_form.html``` template.
