### ISSUE TITLE
Topics not load into the frontend

### ISSUE THREAD

**Issue by ivanbtrujillo** [pencilblue/pencilblue#434]
Hi guys, it seems that topics are not loading properly to frontend. I see them on Dashboard and i create and delete it perfectly. Also, i have checked that topics are correctly stored on MongoDB.

But on the main page, the topics array is empty. There are no errors on browser console or on the console from backend. 

I created an empty project of pencilblue and the problem also occurs.

Thanks!,

**Comment by blakecallens** [comment]
What theme are you using?

**Comment by JahlomP** [comment]
Are you referring to the default pencilblue theme or portfolio?

**Comment by ivanbtrujillo** [comment]
A custom theme following Blake tutorial. Now i installed jennifer theme and it works so its a problem on my theme. I will check it.

Sorry for the issue :-/
