### ISSUE TITLE
WYSIWYG editor in custom objects sanitizes id attribute when in HTML view

### ISSUE THREAD

**Issue by tangledpixel** [pencilblue/pencilblue#437]
To recreate
1. create a custom object
2. add WYSIWYG field
3. create object
4. go to HTML view
5. type in an HTML tag with an id attribute
6. save
7. reopen custom object for editing, id attribute has been sanitized

(I'm not sure if other attributes are affected by this, it only seems to occur in the custom objects and not in pages)

**Comment by blakecallens** [comment]
You can allow for any type of HTML tags by overriding getSanitizationRules in the new and edit custom objects controllers. Here's why we take them out by default:

Probably the only reason you would need an *id* attribute is to also add JavaScript inside the WYSIWYG to manipulate the element. Allowing JS in the WYSIWYG would open your site up to XSS attacks.

We suggest creating a controller and template to drive pages that need this type of functionality.
