### ISSUE TITLE
VideoMediaRenderer.getName() and ImageMediaRenderer.getName() returns 'ImageMediaRenderer'

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#445]
Both the VideoMediaRenderer and ImageMediaRenderer returns ImageMediaRenderer when their getName method is called.

https://github.com/pencilblue/pencilblue/blob/master/include/service/media/renderers/image_media_renderer.js#L116

https://github.com/pencilblue/pencilblue/blob/master/include/service/media/renderers/video_media_renderer.js#L116

Is it intentional or a typo?

**Comment by brianhyder** [comment]
Typo. You mind submitting the change and I'll pull it in?
