### ISSUE TITLE
thumbnail picture

### ISSUE THREAD

**Issue by rogr** [pencilblue/pencilblue#452]
Select a File from media to add thumbnail image of the article.

**Comment by JahlomP** [comment]
can you be a little more expressive?

**Comment by blakecallens** [comment]
I think he wants a thumbnail meta tag for submitting to social media.

**Comment by JahlomP** [comment]
ok

**Comment by rogr** [comment]
Yeah, something like WordPrees have: http://codex.wordpress.org/Post_Thumbnails

I want to upload a photo and add it to the article.
Any ideas of how can I make this?

**Comment by blakecallens** [comment]
You could use the media service to pull the first associated media of the article to use as the thumbnail image. The [Jennifer Theme](https://github.com/pencilblue/jennifer/blob/master/controllers/index.js#L361) uses this to set header images. You could pretty much copy and paste this code and change the html to use the url for the meta tag.

I think this is something we should add to PB, though.

**Comment by JahlomP** [comment]
Yeah. @Brain?
