### ISSUE TITLE
[Safari] Datetimepicker date is not being converted for post

### ISSUE THREAD

**Issue by blakecallens** [pencilblue/pencilblue#458]
Looks like the [date conversion](https://github.com/pencilblue/pencilblue/blob/master/plugins/pencilblue/templates/angular/admin/content/articles/article_form.html#L102) in the Angular controller for datetimepickers isn't working in Safari.

There's no console output, the getTime() date is just UTC 0.

**Comment by blakecallens** [comment]
Safari only takes certain date formatted strings. We'll have to convert to a format that all browsers accept:

```JavaScript
new Date('2015-02-04T12:23-05:00')
```

**Comment by brianhyder** [comment]
The date you have shown above. Is that what we currently use or what you would like to change to?

**Comment by blakecallens** [comment]
That's what we'll need to change it to in Angular for Safari to convert it to a date object. I don't want to change how it appears to the user. There are supposedly some JS libraries to do this, but I'd like to avoid adding another one to the mix if it's not that much work to write a conversion service of our own.
