### ISSUE TITLE
"This field is required" when creating a new navigation item

### ISSUE THREAD

**Issue by dcromster** [pencilblue/pencilblue#466]
1. Create new navigation item
2. Fill fields: type=Page, Nsme,Description,Parent navigation item
3. Try to save. I got "This field is required" under "Content field". k. Fill it some text. (What I must to write here?) Press "Save" and "This field is required"...

Video: http://www.youtube.com/watch?v=_r2AbUy4AuI&feature=youtu.be

**Comment by blakecallens** [comment]
start typing the name of a page you've created and it'll become a dropdown element you can select.

**Comment by brianhyder** [comment]
The information tool tip does not appear to be working. @blakecallens can
you confirm that?

**Comment by blakecallens** [comment]
Yes, confirmed. I'm going to wrap that into another bug/issue. I want to revisit this whole input style. @dcromster isn't the first to be confused by it.
