### ISSUE TITLE
Improve the UI/UX of the page/article input on new navigation items

### ISSUE THREAD

**Issue by blakecallens** [pencilblue/pencilblue#467]
This input is confusing to users. We need a simpler way to choose a page or article. The tooltip needs to be fixed too.

**Comment by dcromster** [comment]
Ya! I forgot about tooltip :(

**Comment by blakecallens** [comment]
New pull request in. Using same UI, but now it defaults to latest 10 articles/pages. So, focusing on the element will give you a list of options, right off the bat.

**Comment by blakecallens** [comment]
Also fixed the tooltip. :)
