### ISSUE TITLE
Link to quickly navigate to the site's home page '/' in Admin

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#473]
It will make navigation a little easier if there was a link to click to navigate to the site's home page '/'.

**Comment by blakecallens** [comment]
Agreed. I'll figure out where this is best placed and have it in for 0.4.0.

**Comment by JahlomP** [comment]
OK

**Comment by blakecallens** [comment]
Added in 0.4.0-blake branch.
