### ISSUE TITLE
question: How do you easily add AngularJS to a template

### ISSUE THREAD

**Issue by alexcurtis** [pencilblue/pencilblue#478]
Hi.
Currently if I was to put together a reusable drop-in widget template, that was self contained. I would create a template html file and embed it onto a page with something like `^tmp_widget^`.

I am finding it quite hard to create an AngularJS widget. This is because most of the non-admin pages by default attach the Angular Module snippet at the very bottom of the document, after the HTML tag. So I can't reference the `pencilblueApp` module at the correct time, without using some crazy defer attribute like `<script src="/public/.../widget.js" defer></script>`.

There is probably an easy way of doing this that I'm not seeing. Could someone please point me in the right direction. Many Thanks.

**Comment by JahlomP** [comment]
Checkout this article,
https://github.com/pencilblue/pencilblue/wiki/Quickstart:-HTML-Templates.
Let me know if its helpful.

**Comment by alexcurtis** [comment]
@JahlomP Thanks for your response.
It looks like that is tailored around routed pages. How could I do this for drop-in AngularJS widgets.

**Comment by blakecallens** [comment]
On my phone, so I can't get in depth, but you're going to want to follow the method we used for the admin section. Create the main controller as a template and then you can inject widgets and their subcontrollers with templates too. An example of this is the topics drag and drop on article and page forms.

Let me know if you need more help and I'll jump on with clearer examples when I'm at a computer.

**Comment by alexcurtis** [comment]
@blakecallens Thanks. I think I might need some examples. Ideally id like to create a template that people can insert into their existing pages without too much trouble. A bit like the calendar plugin, but with Angular bits.

**Comment by blakecallens** [comment]
I would suggest making a traditional Angular directive for something like
that and putting both the JS and HTML in the public folder of your plugin.
That way you're not locking other users into using your way of loading
angular.

**Comment by blakecallens** [comment]
@alexcurtis also keep in mind that not everyone who uses PencilBlue will use AngularJS on the frontend. That's why we stick to jQuery and the PB template service for plugins that inject widgets/elements.

**Comment by alexcurtis** [comment]
@blakecallens Ah. Ok. I didn't realise that AngularJS was an optional thing. I think you are right. Keep it simple, keep it jQuery. Thanks for your help.

**Comment by JahlomP** [comment]
I like your quote "Keep it simple, keep it jQuery"
