### ISSUE TITLE
Media GridFS/File Clean Up

### ISSUE THREAD

**Issue by alexcurtis** [pencilblue/pencilblue#479]
Is there currently a task runner that cleans up uploaded media files that are cancelled before saving?
Currently I have 2 cancelled files in my GridFS store that have not yet been destroyed. Also seems to be an issue with File System approach.
Thanks.

Replicate:
New Article
Upload Media File,
Cancel On Media Modal Window

**Comment by blakecallens** [comment]
Nothing in the system, but I think that would make an awesome plugin. It could also have a function to remove any media that isn't associated with articles and media.

**Comment by alexcurtis** [comment]
@blakecallens Neat. Shall I give it a crack?

**Comment by blakecallens** [comment]
Sure, man! I'll close this issue, but we can still use it if you have technical questions.

**Comment by alexcurtis** [comment]
@blakecallens Hi. How do I attach the debugger to PencilBlue?
The usual `node --debug ./pencilblue.js` is throwing failed to open socket issues. Is it cluster related?

**Comment by blakecallens** [comment]
Potentially cluster related. @brianhyder will have a better idea than me.

**Comment by brianhyder** [comment]
In your configuration file set the cluster.self_managed to false.

Install node-inspector globally
Run using: node-debug -p 8082 pencilblue.js

Let me know if that doesn't work. Going off of memory since I don't have my
laptop.

**Comment by alexcurtis** [comment]
@brianhyder Awesome. the self_managed was the trick. It might be worth adding this to the wiki.
Mega thanks for the help.

**Comment by brianhyder** [comment]
You are correct. I've been meaning to do a blog post on how to debug.

Glad it worked.

**Comment by alexcurtis** [comment]
@blakecallens Hi. I've made a start on putting together a plugin: https://github.com/alexcurtis/clean-pencilblue

Currently it supports clean up of:
unreferenced media files. Files that don't have a media object associated.
unassociated media. Media files + objects that are not referenced in an article, page or custom object.

I'm sure there is lots to build on here. But it would be awesome if you could please take a look and let me know what you think / give me some pointers. Many Thanks.

**Comment by blakecallens** [comment]
This looks great from my end, but I would defer to @brianhyder on all things file system.

**Comment by brianhyder** [comment]
@alexcurtis There is a blog post that will surface Wednesday describing the process for debugging.  Thank you for the feedback.  It was spot on.

I tool at a look at the code you linked above.  Amazing job on it.  I made a couple of comments but nothing major.  I do have a couple of questions:

1.  I saw you used the job runner.  This triggers the same operation to be ran on every worker process.  Is that what you intended?
2. I'm curious to get your feedback on the job runner and how easy it was to understand and work with.  It is something I've been targeting to lean heavier on for the distributed tasks but I want to make sure it is easy to follow how it works.

**Comment by alexcurtis** [comment]
@blakecallens Thanks for the feedback.

In terms of the job runner:
* Yes, good point. I probably don't want to be running this per worker, as it would just be repeating on the same file system + db wouldn't it? Is the best way to turn this off, to just inherit from `AsyncJobRunner` rather than `ClusterJobRunner`? 

*How easy it was to work with? Yes, it was pretty straight forward. The plugin system provided a great how-to, and I basically emulated a lot of the boilerplate from there. One thing that did have me stumped was the initiator command loop back catch, that was in the `plugin_service`. It wasn't immediately obvious why it was calling the same handler twice, until I looked at the options it passed in.

In terms of the front end (possibly one for @blakecallens)  -- what would be really nice is to have a console/log service. At the moment, I had to rip a lot of the boilerplate found in the plugin angular code. It would be awesome to have a service/controller to call that handled all the logs + job bits, as they are quite generic if interfacing with the job runner. What do you think?

**Comment by brianhyder** [comment]
@alexcurtis That is correct, the change to inheritance to AsyncJobRunner should do the trick.  Thank you for the feedback.

**Comment by alexcurtis** [comment]
@brianhyder There were a couple of different callbacks required too, but the AsyncRunner code was nice and easy to follow, so it was easy to change the handler names. -- Great work on making it easy to follow, its much appreciated! Taking out the cluster stuff has also really cut down the job logic, which is always a plus.

Suppose, the next question is... What else do we need to clean up? -- Maybe a complete clear of content (articles, pages, etc) -- a bit like a factory reset? Any ideas guys?
