### ISSUE TITLE
Feature Request: Read More

### ISSUE THREAD

**Issue by tangledpixel** [pencilblue/pencilblue#483]
Feature Request: 

We need to have an excerpt feature for articles. There should be a read more button in the WYSIWYG editor so when users go to the article page, the list of all the articles should only display up to the read more line.

**Comment by blakecallens** [comment]
Agreed. Currently, you can set the number of paragraphs to auto-break on (and ad a Read More link) in Settings->Site Settings->Content.

This should be overridable with a read more entry. This will probably get put on the backlog for after 0.4.0 is released.

**Comment by JahlomP** [comment]
Can't the excerpt feature be added in 0.3.x since it has no significant effect on the pb api?

**Comment by JahlomP** [comment]
read more can be added later.

**Comment by JahlomP** [comment]
@blakecallens what to you think.

**Comment by blakecallens** [comment]
@JahlomP it would be 0.4.0, but I'll look into adding it. If not that release, then 0.4.1.

**Comment by JahlomP** [comment]
Ok
