### ISSUE TITLE
Plugin install glitch

### ISSUE THREAD

**Issue by misbahneo** [pencilblue/pencilblue#486]
When trying to install a custom plugin whilst trying to follow the tutorial, pencilblue recognises my plugin 

but when it comes to installation gets stuck here is a copy of the status

```
2015-03-03T17:02:56.108Z:[1] INSTALL_PLUGIN_misdigest: Verifying that plugin misdigest is not already installed
2015-03-03T17:02:56.242Z:[1] IS_AVAILABLE_misdigest: Updating job [54f5e940f179deb83d60eac3:IS_AVAILABLE_misdigest] by 0 percent with status: undefined
2015-03-03T17:02:56.305Z:[1] IS_AVAILABLE_misdigest: Updating job [54f5e940f179deb83d60eac3:IS_AVAILABLE_misdigest] by 16.666666666666664 percent with status: undefined
2015-03-03T17:02:56.345Z:[1] IS_AVAILABLE_misdigest: Inspecting plugin on disk at: /Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/plugins/misdigest/details.json
```

**Comment by brianhyder** [comment]
I'm going to need a bit more information.  Can you send us the details.json file?  Also, provide your config.js file.

**Comment by misbahneo** [comment]
Hey brian here is my details.json

```
{
    "uid": "misdigest",
    "name": "misdigest Theme",
    "description": "a new theme for misdigest",
    "version": "0.1.0",
    "author": {
        "name": "Misbah Anjum-James",
        "email": "misbah@misdigest.co.uk",
        "website": "http://misdigest.co.uk",
        "contributors": [
            {
                "name": "Misbah Anjum-James",
                "email": "misbah@misdigest.co.uk"
            }
        ]
    },
    "settings": [],
    "permissions": {
        "ACCESS_USER": [],
        "ACCESS_WRITER": [],
        "ACCESS_EDITOR": [],
        "ACCESS_MANAGING_EDITOR": []
    },
    "main_module": {
        "path": "misdigest.js"
    },
    "theme": {
        "settings": [],
        "content_templates":[]
    }
}
```

also i thought i understood the instruction to mean that if you are using a config.json file you shouldn't need a config.js file?

i've just reinstalled pencilblue to another directory to get another config.js file should i put my details into this aswell and include it in my current project?

```
{
    "siteName": "misdigest",
    "siteRoot": "http://127.0.0.1:8080",
    "sitePort": 8081,
    "log_level": "info",
    "db": {
        "type":"mongo",
        "servers": [
          "127.0.0.1:27017"
        ],
        "name": "pencilblue",
        "writeConcern": 1
    },
    "cache": {
        "fake": true,
        "host": "localhost",
        "port": 6379
    },
    "settings": {
        "use_memory": false,
        "use_cache": false
    },
    "templates": {
        "use_memory": true,
        "use_cache": false
    },
    "plugins": {
        "caching": {
            "use_memory": false,
            "use_cache": false
        }
    },
    "registry": {
        "type": "mongo"
    },
    "session": {
        "storage": "mongo"
    }
}
```

**Comment by brianhyder** [comment]
Headlines need to be unique.  It appears that some of the articles that you
are importing do not have headlines.  Check the XML files that you are
importing to ensure that each post has a headline.  I'll also try to push a
fix to the import plugin that provides a default headline if not provided.

On Tue, Mar 3, 2015 at 9:42 AM, misbahneo <notifications@github.com> wrote:

> Wordpress import is installed successfully into pencil blue however
> everytime i try to import the XML file I get this error
>
>  MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: pencilblue.article.$headline_1 dup key: { : "" } at Object.toError (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/utils.js:114:11) at /Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/collection/core.js:114:29 at /Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/db.js:1166:7 at b (domain.js:183:18) at /Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/db.js:1874:9 at b (domain.js:183:18) at Server.Base._callHandler (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/base.js:453:41) at /Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_
>  modules/mongodb/lib/mongodb/connection/server.js:481:18 at MongoReply.parseBody (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5) at null. (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/486>.
>



-- 
Brian P. Hyder

**Comment by brianhyder** [comment]
You can use a config.json instead of a config.js file but it is being phased out in 0.4.0.  

If you change the port you also need to update your site root to reflect the change.  The descrepency is probably causing you to redirect to a site that doesn't exist because you are listening on 8081 but your site root is configured for 8080.  

You should also ensure that the name of the directory that contains that your custom plugin must match the "uid" value included in your details.json file

**Comment by rohitkumargupta** [comment]
I have a problem with install plugin . I remove plugin by mistake after that i cannot install plugin



2015-07-23T12:47:09.236Z:[1] INSTALL_PLUGIN_my_theme: Verifying that plugin my_theme is not already installed
2015-07-23T12:47:09.269Z:[1] IS_AVAILABLE_my_theme: Updating job [cc7052f5-6c4b-4ff2-87d3-b9359ff0e5c9:IS_AVAILABLE_my_theme] by 0 percent with status: 
2015-07-23T12:47:09.368Z:[1] IS_AVAILABLE_my_theme: Updating job [cc7052f5-6c4b-4ff2-87d3-b9359ff0e5c9:IS_AVAILABLE_my_theme] by 25 percent with status: 
2015-07-23T12:47:09.430Z:[1] IS_AVAILABLE_my_theme: Inspecting plugin on disk at: c:\Bitnami\meanstack-2.6.4-0\CW-Project\cw\plugins\my_theme\details.json

**Comment by brianhyder** [comment]
Hey, happy to help but will need a bit more information.

To help us quickly identify issues the following information is helpful:
Step by step instructions to reproduce
Configuration overrides (minus any credentials)
Environment details: Linux, windows, hosting provider, local, etc.
Log output. Set your logging.level configuration property to "silly".
