### ISSUE TITLE
using services from another plugin does not work as suggested

### ISSUE THREAD

**Issue by bitterulf** [pencilblue/pencilblue#494]
I tried to access the service from the sample plugin as suggested inside the wiki

var textCreator = pb.plugins.getService('textService', 'sample');
textCreator.getText(function(err, text) {
  console.log(text);
});

wich results in
TypeError: Object function TextService() {} has no method 'getText'
The sample plugin is installed and the service init was also executed by pencilblue.

**Comment by brianhyder** [comment]
The documentation is incorrect, it has been updated.  In this case, the sample text creator service has both functions directly off of the prototype and some that are prototype functions.  ```getText``` is a prototype function so a *new* instance of the service must be created before accessing the function. 

Great catch and thank you for reporting.
