### ISSUE TITLE
Feature Request: Gzip all output

### ISSUE THREAD

**Issue by tangledpixel** [pencilblue/pencilblue#495]
I would like to request all output to be gzipped, this will increase page rendering speed and potentially SEO on all Pencilblue sites.

**Comment by blakecallens** [comment]
We wouldn't want set this as default behavior, but let's see about how a plugin could be built for this. I know that it wouldn't be much to add it on a per theme level.

Another possibility is to add it as a content setting and have the template service use the gzip node module if the setting is on.

**Comment by brianhyder** [comment]
It isn't possible to modify this behavior via plugin. It will need to be
part of the core.  The setting route is the best way to go. It wouldn't be
a hard change to make.

Basic flow:
Check setting, if on then...
Check request header accept to ensure it is supported by the client
When supported set the content-encoding header
Finally, call zlib package to encode the stream

**Comment by blakecallens** [comment]
@tangledpixel, would you be willing to fork the [0.4.0 branch](https://github.com/pencilblue/pencilblue/tree/0.4.0) make that change and submit a pull request? We'd be on hand to answer any questions you have on how to make that change.

**Comment by tangledpixel** [comment]
When is 0.4.0 branch due? I wouldn't mind creating a plugin for this,
however at the present moment I have 3 contracts that need to be out the
door in the next 6 weeks. :O

On Fri, Mar 13, 2015 at 8:46 AM, Blake Callens <notifications@github.com>
wrote:

> @tangledpixel <https://github.com/tangledpixel>, would you be willing to
> fork the 0.4.0 branch
> <https://github.com/pencilblue/pencilblue/tree/0.4.0> make that change
> and submit a pull request? We'd be on hand to answer any questions you have
> on how to make that change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/495#issuecomment-79062770>
> .
>



-- 
Jonathan Eustace
CEO | *Tangled*Pixel | 604.782.6662


*WARNING: CONFIDENTIALITY NOTICE*
This message may contain confidential or privileged material or information
which is exempt from disclosure under applicable law. Any use,
dissemination, distribution or copying of this information by anyone other
than the intended recipient is prohibited. If you are not the intended
recipient, or have received this message in error, please immediately reply
to or telephone the sender, permanently destroy any hard copies and delete
this information from your computer. Thank you.
