### ISSUE TITLE
Flags for custom objects

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#496]
I have two custom objects: `pb_amazon_slide` and` pb_amazon_slider`.

The `pb_amazon_slider` contains child objects of `pb_amazon_slide` custom object.

I want a way to just insert flags for different `pb_amazon_slider` objects inside templates so that the appropriate `pb_amazon_slider` appears where I want them (the places I placed their flags).

Is there a way to generate different flags for the different pb_amazon_slider objects and use them.
Is there a way to achieve this.

**Comment by brianhyder** [comment]
If I understand what you are asking for then yes, there is a way to do that.  Are the slides static or dynamic?  Meaning, do you know ahead of time which pb_slide_objects go where?

**Comment by JahlomP** [comment]
No.

this is the module code:

``Sample.onInstall = function(cb) {
  var self = this;
  var cos = new pb.CustomObjectService();

  this.setupAmazonSliderType = function() {
    cos.loadTypeByName('pb_amazon_slider', function(err, amazonSliderType) {
     if(!amazonSliderType) {
     var sliderValues = {
        name: 'pb_amazon_slider',
        fields: {
         name: {field_type: 'text'},
           slide: {field_type: 'child_objects', object_type:
'custom:pb_amazon_slide'}
        }
      };

      cos.saveType(sliderValues, function(err, amazonSliderType) {
        cb(null, true);
      });
     } else {
     cb(null, true);
     }
    });
  }

  this.setupAmazonSlideType = function() {
  cos.loadTypeByName('pb_amazon_slide', function(err, amazonSlideType) {
    if(!amazonSlideType) {
      var slideValues = {
        name: 'pb_amazon_slide',
        fields: {
          name: {field_type: 'text'},
          image: {field_type: 'peer_object', object_type: 'media'},
          width: {field_type: 'text'},
          height: {field_type: 'text'},
          link: {field_type: 'text'}
        }
      };

      cos.saveType(slideValues, function(err, amazonSlideType) {
       self.setupAmazonSliderType();
      });
    }
    else {
      cb(null, true);
    }
});
  }

  this.setupAmazonSlideType()
};``


So I want away to pull every slide inside ``pb_amazon_slider`` and generate
flags for them.
Will display them in the admin so that the user will just copy the flag for
the slide he wants to display and insert that inside the template.
Like its done in wordpress if I'm right.

**Comment by blakecallens** [comment]
@brianhyder this makes me think a good feature addition would be passing parameters with custom directives. Maybe something like ```^directive:parameter:parameter^```

**Comment by brianhyder** [comment]
You are correct.  We need a way to register custom template directives like we do with media.

For now, the only solution I can think of is to retrieve them all for the DB at startup and create individual registrations for each.  The only issue with that is that you would have to redo them when the a custom object is saved.  That would be a real pain to have to do that.  I'll definitely add this feature to the back log.

**Comment by JahlomP** [comment]
Ok

**Comment by brianhyder** [comment]
So apparently, many months ago, I had some forethought into this.  @JahlomP, can you try something for me?  Pull the latest code from master:

in your module's ```onStart``` function try something like this:
```
Sample.onStart = function(cb) {

  pb.TemplateService.setGlobalUnregisteredFlagHandler(Sample.unregisteredFlagHandler);
};

Sample.unregisteredFlagHandler = function(flag, cb) {

  if (flag.indexOf('pb_amazon_slide_') !== 0) {
    return cb(null, '^' + flag + '^');
  }

  //if it gets to here you know it is at your flag.  You can generate what ever content you want here including DB calls to get content and generate HTML.
  var html = '<div>hello world</div>';
  cb(null, html);
  
};

**Comment by JahlomP** [comment]
OK. Was away for sometime. Will do it and give u feedback tonight

On Saturday, March 14, 2015, Brian <notifications@github.com> wrote:
> So apparently, many months ago, I had some forethought into this.
@JahlomP, can you try something for me? Pull the latest code from master:
>
> in your module's onStart function try something like this:
>
> Sample.onStart = function(cb) {
>
>
pb.TemplateService.setGlobalUnregisteredFlagHandler(Sample.unregisteredFlagHandler);
> };
>
> Sample.unregisteredFlagHandler = function(flag, cb) {
>
> if (flag.indexOf('pb_amazon_slide_') !== 0) {
> return cb(null, '^' + flag + '^');
> }
>
> //if it gets to here you know it is at your flag. You can generate what
ever content you want here including DB calls to get content and generate
HTML.
> var html = '<div>hello world</div>';
> cb(null, html);
>
> };
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci6.googleusercontent.com/proxy/UoGeRvIKlyjz0d_Gf5fqPz6xOxfkJL1ArEgaeQl22MVNh1ypp6sSW84WRzBWmjjsSsbhs_9C4UlPww2KJCBUx3-1mRo9zM9wRWUwlhWu_s1HW8TvZwRhb7dG_UvCVh5dpMSvgKqnKeJWo7QtbYozV-3M8ckfRg=s0-d-e1-ft#https://github.com/notifications/beacon/AEhtD3T0_bv_OaLt91ZZO_iXpFB005Ozks5n1GB_gaJpZM4DuuU_.gif
>

-- 
Best Rregards,
Precious Jahlom Agboado,
NibbleIT,
www.twitter.com/jahlomp
+233 54 0915 108.

**Comment by JahlomP** [comment]
I understand the code but I don't get the endgame. What are u trying to
teach me?

On Sunday, March 15, 2015, Jahlom Agboado <jahlomp@gmail.com> wrote:
> OK. Was away for sometime. Will do it and give u feedback tonight
>
> On Saturday, March 14, 2015, Brian <notifications@github.com> wrote:
>> So apparently, many months ago, I had some forethought into this.
@JahlomP, can you try something for me? Pull the latest code from master:
>>
>> in your module's onStart function try something like this:
>>
>> Sample.onStart = function(cb) {
>>
>>
pb.TemplateService.setGlobalUnregisteredFlagHandler(Sample.unregisteredFlagHandler);
>> };
>>
>> Sample.unregisteredFlagHandler = function(flag, cb) {
>>
>> if (flag.indexOf('pb_amazon_slide_') !== 0) {
>> return cb(null, '^' + flag + '^');
>> }
>>
>> //if it gets to here you know it is at your flag. You can generate what
ever content you want here including DB calls to get content and generate
HTML.
>> var html = '<div>hello world</div>';
>> cb(null, html);
>>
>> };
>>
>> —
>> Reply to this email directly or view it on GitHub.<
https://ci6.googleusercontent.com/proxy/UoGeRvIKlyjz0d_Gf5fqPz6xOxfkJL1ArEgaeQl22MVNh1ypp6sSW84WRzBWmjjsSsbhs_9C4UlPww2KJCBUx3-1mRo9zM9wRWUwlhWu_s1HW8TvZwRhb7dG_UvCVh5dpMSvgKqnKeJWo7QtbYozV-3M8ckfRg=s0-d-e1-ft#https://github.com/notifications/beacon/AEhtD3T0_bv_OaLt91ZZO_iXpFB005Ozks5n1GB_gaJpZM4DuuU_.gif
>
>
> --
> Best Rregards,
> Precious Jahlom Agboado,
> NibbleIT,
> www.twitter.com/jahlomp
> +233 54 0915 108.
>
>

-- 
Best Rregards,
Precious Jahlom Agboado,
NibbleIT,
www.twitter.com/jahlomp
+233 54 0915 108.

**Comment by brianhyder** [comment]
It demonstrates how you can copy and paste a custom directive/flag into a page or article and have it render.

The code in the custom ```Sample.unregisteredFlagHandler``` can parse the directive and figure out what custom object to go look up.  Once retrieved you can build HTML to display it.
