### ISSUE TITLE
inserting media elements cause wysiwyg editor to break

### ISSUE THREAD

**Issue by bitterulf** [pencilblue/pencilblue#498]
If you insert a media element, save, add a second media element, save again the old layout with only one element is is sent to the server even if you also see the second media element in the editor.

Browser is FF 36

**Comment by blakecallens** [comment]
This is a known issue with the wysiwyg. What's happening is that the extra media elements are being added inside the preview div and only that parent div is getting parsed out when the article or page is saved. Until we figure out a fix, we suggest creating the paragraphs before adding media to ensure that they're separated.
