### ISSUE TITLE
content is required only at the creation of a page

### ISSUE THREAD

**Issue by bitterulf** [pencilblue/pencilblue#499]
After trying to create a page without any content i only get a general validation error and have to guess what is wrong.
And after the creation i can empty the content and get not validation problem.

Since i sometimes want to create empty pages for other people to fill i would be happier if the content could be empty at any time.

**Comment by JahlomP** [comment]
You can override this by writing a controller for it and excluding layout
from the required fields

**Comment by JahlomP** [comment]
Check
https://github.com/pencilblue/pencilblue/blob/master/plugins/pencilblue/controllers/actions/admin/content/articles/new_article.js

**Comment by JahlomP** [comment]
Check this portion of the code
``
NewArticlePostController.prototype.getRequiredFields = function() {
	return ['url', 'headline', 'article_layout'];
};``

**Comment by blakecallens** [comment]
Thanks, @JahlomP. That is correct.
