### ISSUE TITLE
Logout referrer 

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#504]
Wouldn't it be best if a user is referred back to where he was before signing out? This should be applied on to a normal users(users without admin privileges)

**Comment by brianhyder** [comment]
Yes, you are correct. What is the current behavior?

**Comment by JahlomP** [comment]
When you logout, instead of signing out and bringing you back to the page
you were when you signed out, it send you to the home page.
I this feature is corrected, it should not be applied to admin pages. The
reason is it will bring the user back to the admin page where he or she was
which cannot be accessed any longer now that the user is logged out. For
admin pages i suggest he is redirected to admin login page.
If the page the user was on before logging out was a page requiring
authentication, then I think it is OK to send the user to the home page.

These are my thoughts.

**Comment by brianhyder** [comment]
This is now implemented in 0.4.0

**Comment by JahlomP** [comment]
Ok
