### ISSUE TITLE
image media renderer does not support gif images

### ISSUE THREAD

**Issue by bitterulf** [pencilblue/pencilblue#505]
Gif animations are still useful so they should be supported by default.

**Comment by blakecallens** [comment]
GIFs are supported. You can upload or link to them just like any other image. I confirmed this working on my local installation. Perhaps the file size of the image was too large. The default is 2MB, but you can change that in the max_upload_size setting under media in your [config.js](https://github.com/pencilblue/pencilblue/blob/master/include/config.js#L538).

**Comment by bitterulf** [comment]
file size is not the problem (used a 4kb file)

still getting
{"level":"warn","message":"MediaService: No media renderer could be found for URI [/media/2015/3/5513c087478de5cc08e3734f-1427357831770.gif]","timestamp":"2015-03-26T08:17:11.795Z"}

and in the current master branch inside 'image_media_renderer.js' under 'The list of supported extensions' gif is definitely missing.

**Comment by blakecallens** [comment]
Did you add .gif and see if it works?

**Comment by bitterulf** [comment]
yeap adding it works fine
i created a pull request.

**Comment by blakecallens** [comment]
Thanks! I wonder why I had no issue when I did it. At least we know it
works across the board now.

**Comment by bitterulf** [comment]
brianhyder allready fixed this bug in 0.4.0 so everything will be fine after release
