### ISSUE TITLE
WP Import Plugin doesn't import posts

### ISSUE THREAD

**Issue by rhekkers** [pencilblue/pencilblue#506]
Hi,
I tried to import about 360 posts in a fresh install of pencilblue but it doesn't seem to work; nothing happens after I select the import xml file and click the 'open' button. Nothing; no error, no progress bar, nothing in the logs. 

Everything else seems to work without a problem - I can create new articles, pages and so on. 

One thing I noticed is that during startup I see a warning in the log saying "PluginService: The plugin, WordPress Import does not specify pb version."?

**Comment by brianhyder** [comment]
Hey, thank you for the report.  I haven't had a chance to look at it yet but I'll be checking it on the 0.4.0 branch.  

We recently introduced the ability to ensure that plugins are compatible with the current version of the system.  The warning just indicates that a version wasn't set.  This has been corrected in 0.4.0. 

I'll try and take a look at this tonight and let you know what I find.  

Any chance you would be willing to email me the file you were attempting to import?

**Comment by rhekkers** [comment]
Thanks, I'll send you the file I used for the import.

**Comment by brianhyder** [comment]
@rhekkers Did you get a chance to send the import file?

**Comment by rhekkers** [comment]
Yep, same day. Sent it to the email address listed @ the Plugin information page.
Subject: For Brian Hyder, WP import file for pencilblue issue #506 on GitHub.

**Comment by brianhyder** [comment]
Found it.  Thank you.  I'll dive into this today.

**Comment by brianhyder** [comment]
Hey, just wanted to give you an update.  The problem was that a few of the posts did not have the "title" or "wp:post_name" tags set so the import code was not happy about it.  For these posts it will now generate a unique name and keep on trucking.  I want to run a couple more tests but I have pushed up the current changes to branch ```issue/506``` if you want to take a look.

**Comment by brianhyder** [comment]
Finally found the real issue.  There are a few posts references content on the local system.  I'll put in some checks and safe guards and then push up a fix.

**Comment by rhekkers** [comment]
All posts were successfully imported, thank you!
