### ISSUE TITLE
tags navigation

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#512]
If navigation for tags is not yet available, I suggest something similar be introduced. It will not appear in the main nav.

**Comment by JahlomP** [comment]
@blakecallens @brianhyder any thoughts

**Comment by blakecallens** [comment]
Take a look at the [Jennifer Theme](https://pencilblue.org/plugins/view/54ce47d124b1a6e40fe21983). It has a side navigation based on topics. You could build a plugin to render a unordered list (ul) element and then it could be styled any way you want.

**Comment by JahlomP** [comment]
OK. Will work on it tomorrow and publish it
