### ISSUE TITLE
Admin Navigation collapse  button 

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#515]
having a collapse button to collapse  the navs to the left will bring more space when writing an article.

**Comment by blakecallens** [comment]
There's already a fullscreen button in the wysiwyg. Do we really need a collapse button for the nav?

**Comment by bitterulf** [comment]
Is there a way to save a article in fullscreen without leaving it?

**Comment by JahlomP** [comment]
@bitterulf No. @blakecallens, can such a feature be added?

**Comment by JahlomP** [comment]
@blakecallens thinking of it again, having a collapse button does not solve any particular problem. Please ignore it.
