### ISSUE TITLE
Trailing slashes in URLs causing 404 (0.4.0)

### ISSUE THREAD

**Issue by blakecallens** [pencilblue/pencilblue#516]
http://localhost:8080/admin/content/navigation

will load fine

http://localhost:8080/admin/content/navigation/

returns a 404

**Comment by brianhyder** [comment]
You need to update the references to not include the trailing slash. This
is due to the change for static routes.

**Comment by blakecallens** [comment]
Ah. Ok. I'll close this but let's discuss soon. I think this could cause confusion and we'll need to document it thoroughly.
