### ISSUE TITLE
Multiple Instances of PB on windows

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#519]
having this config
`"cluster": {
        "workers": "auto",
        "self_managed": true
    }` 

in my config file, I tried install a plugin. The installation get stack on the way without any error but just this

![2](https://cloud.githubusercontent.com/assets/4746511/6917766/54c30e3e-d797-11e4-84c6-4ab71c2ae8f0.png)

But when I remove the cluster part from the config file, everything works.

I'm using and 8Gb memory, i5 windows machine running Windows 8.1.

**Comment by brianhyder** [comment]
Can you tell me what command broker type and registry provider type you are
using in your configuration?

**Comment by JahlomP** [comment]
this is the registry,
`"registry": {
        "type": "mongo"
    },`

i did not specify it so i it uses the default which is redis which i think is the problem

**Comment by brianhyder** [comment]
It sounds like the issue is that the command service is using Redis and the
"fake" property is set to true. This doesn't work with multiple workers
because each worker has its own fake Redis instance and they are not
shared. You need to stick with one instance or change the command broker to
a real Redis instance.

**Comment by brianhyder** [comment]
@JahlomP Did that answer your question?

**Comment by JahlomP** [comment]
Yes. thanks.

On Wed, Apr 1, 2015 at 1:25 AM, Brian <notifications@github.com> wrote:

> @JahlomP <https://github.com/JahlomP> Did that answer your question?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/519#issuecomment-88292662>
> .
>



-- 
Best Rregards,
Precious Jahlom Agboado,
NibbleIT,
www.twitter.com/jahlomp
+233 54 0915 108.
