### ISSUE TITLE
config.json no longer works in 0.4.0

### ISSUE THREAD

**Issue by btidwell** [pencilblue/pencilblue#522]
When trying to upgrade our system to 0.4.0 we noticed our config.json files are no longer being recognized.  Is this something that is intended for 0.4.0?

**Comment by brianhyder** [comment]
Yes, it is intended.  I screwed up and forgot to mention this as part of the "What's coming" blog post.  

You can easily convert it over by: 
* Change the extension to ```.js```
* prefix the JSON block with:
```
module.exports = {
...
};
```

**Comment by btidwell** [comment]
So can I make a case to keep it?  Since a config is unique between environments (dev, staging, and production), it doesn't make sense to make it a .js file.  For our setup we would have to put config.js on ignore and then during deployment chef would have to write json into a js file instead of simply converting json to json.

**Comment by brianhyder** [comment]
That is one benefit to the ```.js``` file.  You can decide what values to use in your configuration based on your environment at runtime.  For example, the difference between dev and prod might be a the host for connecting to MongoDB.  You could have chef simply set the environment variables for the server based on the deployment it is performing.  In your config.js you simply read in the environment variable to populate the configuration.  The environment variable could be a single value or JSON that represents all of the values needed to build out your configuration.

This blog post demonstrates what I'm talking about: http://connorhindley.com/2014/11/25/pencilblue-on-openshift/

Using the ```process.env``` command will allow you to access any variables you need.

thoughts?

**Comment by btidwell** [comment]
ahhh yes.  That makes sense.  I always seem to forget about using process.env.  Thanks for clarifying.

**Comment by brianhyder** [comment]
Hopefully, that helps.  If there is another use case just let us and I'm happy to talk through it.
