### ISSUE TITLE
Ajax admin api/content/search with status 404 

### ISSUE THREAD

**Issue by vqoph** [pencilblue/pencilblue#525]
Hi,

in file ./public/js/admin/elements/content_search.js at line 23 

    $(document).ready(function() {
        var input = $('#content_search');
        input.autocomplete({
            source: function( request, response ) {
                $.ajax({
                    url: "/api/content/search/",

ajax request is responding with code 404 when i try to add navigation item.

I've solved this issue as removing the last slash of the url, but i don't know if it's the right way to do this. 

Could you confirm that's a real issue or if i have a misconfugration anywhere ?

**Comment by blakecallens** [comment]
This is correct and another good catch. We added the ability for static routes to take precedence in 0.4.0, so trailing slashes don't work anymore. Would you mind putting in a pull request for this?

**Comment by brianhyder** [comment]
As @blakecallens said, thank you for the fix
