### ISSUE TITLE
Unable to use preview function in pencilblue default theme

### ISSUE THREAD

**Issue by vqoph** [pencilblue/pencilblue#527]
solved as changing  the name of the function from **PreviewModule** in **PageModule**
in plugins/pencilblue/controllers/page.js

**Comment by blakecallens** [comment]
Great catch. Would you mind putting a pull request in for that change?

**Comment by vqoph** [comment]
it's done, i think ... it's my first github pull request, so if i've done something wrong please tell me ;)

**Comment by brianhyder** [comment]
I think there is still an issue with preview.  See my comments on #523

**Comment by blakecallens** [comment]
#523 was a popup blocked issue, so I'm closing this one.
