### ISSUE TITLE
Cannot Change My Password in Admin Console

### ISSUE THREAD

**Issue by cchatham** [pencilblue/pencilblue#542]
I cannot change my password in the admin console for my personal user. We have tested in our production environment, our test environment, and our local environment. All return an error message of invalid current password (we copy/pasted our current password in).

Thanks!

**Comment by blakecallens** [comment]
The check isn't comparing the hashed password in the DB to a hashed version of the one in the post. I'll have a fix up ASAP.

**Comment by cchatham** [comment]
Thank you so much!! :D

**Comment by blakecallens** [comment]
Fix is up in master.
