### ISSUE TITLE
Draft Saved message when it didn't actually save

### ISSUE THREAD

**Issue by markbaird** [pencilblue/pencilblue#552]
If you create a new article, leave the Content blank, and click Save Draft, you will get a message below the button saying "Draft Saved", while also getting an error message at the top of the page that "The form is incomplete". The draft isn't actually saved in this scenario.

If you've had to scroll the page down at all to get to the save button, then you probably won't even see that error message at the top of the page.

Some combination of the following would make this better:
- Use fixed positioning on the error message container to make sure it is always visible.
- Don't show a message below the save button on error, or show an error message instead of the incorrect success message.
- The error text "The form is incomplete" could be more descriptive
- Apply an error CSS style to the Content field when this happens, so that it's apparent that the error is with the Content field.

**Comment by blakecallens** [comment]
Agreed. I'll work out an Angular error with the wysiwyg if it's empty. That would put it inline with the other required input elements.
