### ISSUE TITLE
HTML modifications to img elements that were inserted with "Insert Media" are not persisting.

### ISSUE THREAD

**Issue by andparker** [pencilblue/pencilblue#555]
If you are editing a page's content and use the "Insert Media" feature to insert an image, and then try to make modifications to the <img> element, the changes are not persisting on save. I had to remove the parent <div> with the media-tag/preview data to get any of my changes to <img> to persist. Is this an issue or intended behavior with images that have been inserted with "Insert Media"?

**Comment by blakecallens** [comment]
This is intended behavior. Media element renderings is handled by [rederers](https://github.com/pencilblue/pencilblue/blob/master/include/service/media/renderers/image_media_renderer.js). If you want to change the way images render, you'll need to create a plugin that overrides the default image renderer. You can always hard code an img tag into the post, if it's a one off thing.

**Comment by andparker** [comment]
Thank you Blake for the very quick response! Sounds like this could be what we want to do so that we can add custom css classes to these images on insert.

**Comment by blakecallens** [comment]
@andparker let us know if you need any direction in creating that plugin.

@brianhyder we've been getting a lot of questions around adding and modifying media renderers. I think this would be a good topic for a Google Hangout tutorial.

**Comment by andparker** [comment]
@blakecallens Absolutely. I sure do appreciate that.
