### ISSUE TITLE
Is it possible to integrate pencilblue into an existing MEAN site?

### ISSUE THREAD

**Issue by shawn-simon** [pencilblue/pencilblue#556]
I'm wondering if I can just inject it into an existing site... host just the content in my own angular app, and use my existing user system. I know this would be a little crazy, wondering if it's remotely possible. I am pretty confident in my abilities to code it if it's feasible. Sorry if this is the wrong place to ask.

**Comment by blakecallens** [comment]
Probably no to "injection", but you could run it as a separate API for content. You'd just have to create the controllers to deliver the data with a plugin.

**Comment by shawn-simon** [comment]
Thanks! In that case, is there any way to use our existing user system? I want to allow them to comment on articles.

**Comment by blakecallens** [comment]
It's theoretically possible, but I'm not sure of the security implications. If you'd just be using PB for the blog content, why not run it as its own application under blog.yourdomain.com?

**Comment by shawn-simon** [comment]
Thank you so much for your replies. Designing a pretty large video streaming app, and would love to use pencilblue for the blog, faq, about, etc. I could just toss it at myapp.com/blog but would lose out on all the shared styles, and navigation, themes etc. and stuff like seeing youre logged in as a user, any notifications. I'm running on angular / angular material for styles so it would be nice to find a way to share as much code base as possible since I'm doing this mostly on my own, and need it yesterday : )

**Comment by blakecallens** [comment]
No prob. That's why were here. 

You could create an API call to PB to get the current logged in user info and display that in your app, but there's really no simple way of combining any two individual, complete platforms built in Node. They're designed to be freestanding entities.

**Comment by shawn-simon** [comment]
Thanks... I was thinking maybe I could get creative by having them connect to the same db and modifying the table structure slightly... then seeing where I could go from there. But looks like it might be too difficult

**Comment by blakecallens** [comment]
Btw, we have plugins for Disqus and Facebook comments in the plugin repository on our website that will allow users to comment without having to log in to PB.
