### ISSUE TITLE
ignoring node_modules does not work for me

### ISSUE THREAD

**Issue by bitterulf** [pencilblue/pencilblue#566]
node_modules is not ignored with the current .gitignore settings.

Do we really need to use double stars?
I quick search lead me to things like:
 " don't use / with **  "

I am using windows by the way.

**Comment by markbaird** [comment]
It works fine for me, on Windows. If you clone the project fresh, run "npm install", and then run "git status" is it saying you have untracked or uncommitted files? 

I just tried that and it says "nothing to commit".

**Comment by brianhyder** [comment]
@bitterulf Are you still having issues?

**Comment by bitterulf** [comment]
@brianhyder i did a clean clone from the repo with the same result
but after updating git to 1.9.5 everything works as expected.
Funny that after working with so much other node modules pencilblue was the first one i encounter wich uses double star syntax.

**Comment by brianhyder** [comment]
I know at some point I was having issues with nested node_modules
directories showing up. I kept fiddling with it until I got the result I
was looking for. The setup could probably be optimized.
