### ISSUE TITLE
Theme Settings do not persist.

### ISSUE THREAD

**Issue by tratnayake** [pencilblue/pencilblue#573]
Hello all! 

First time issue poster so please forgive me if I have not followed a particular format.

Scenario
I am building a theme for a pencilblue website, and I want to have "global theme variables" such as facebook page URL's and twitter profile URL's get loaded with every request so that they can be used as the link for social media icons etc.

Basically, user enters facebook_url in the THEME Settings, and it should be saved in the database to be retrieved by either 
```
pb.PluginService.getThemeSettings
```
but the only values returned are ''. This leads me to assume that the Theme values do not get saved into the database after they are entered in the administration screen.

(further testing reveals that PLUGIN settings work just fine as explained further down, just not THEME settings)

Steps Taken:
1. Created theme settings in my details.json
```
"theme": {
        "settings": 
        [
             {
                "name": "facebook_url",
                "value": ""
            }
        ],
...
```

2. Filled in settings via Administration menu (also another note, one must reset the settings everytime to see new input boxes)
3. Attempted to retrieve settings using
``` 
pb.PluginService.getSettings("THEMENAME",function(err,settings){
console.log(settings);
})
```
^ This is successful.
and 
```
`pb.PluginService.getThemeSettings("THEMENAME",function(err,settings){
console.log(settings);
})
```

^  This was not succesful and returns 

```
{name: 'facebook_url', value: ''}
```

**Comment by brianhyder** [comment]
Good catch and thank you for reporting!
