### ISSUE TITLE
Comments can't be allowed/disallowed per article

### ISSUE THREAD

**Issue by kcdodd** [pencilblue/pencilblue#578]
The "allow comments" option per article doesn't seem to do anything. Only the global "allow comments" option seems to actually restrict comments.

**Comment by brianhyder** [comment]
What theme is active for your site?

On Wed, Apr 29, 2015 at 11:23 PM, kcdodd <notifications@github.com> wrote:

> The "allow comments" option per article doesn't seem to do anything. Only
> the global "allow comments" option seems to actually restrict comments.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/578>.
>



-- 
Brian P. Hyder

**Comment by kcdodd** [comment]
I tested it on default theme.

And, actually, I figured out it does work. It's just yes means no, and no means yes. If I select 'yes' for allow comments on the article editor, it actually disables them.

**Comment by brianhyder** [comment]
Thank you for the clarification. We'll see if we can't knock that out for
you soon.

**Comment by kcdodd** [comment]
I'm not sure if you're looking into the portfolio theme, but now that I see how you fixed the pencil blue theme, I looked at the same code in the portfolio theme and the particular logic seems to be missing, maybe why its not working for portfoli theme?

pencilblue theme: index.js:283
if (isPage || !contentSettings.allow_comments || !content.allow_comments)

portfolio theme: blog.js:311
 if (content.object_type === 'page' || !contentSettings.allow_comments)

**Comment by blakecallens** [comment]
ah, good catch. would you submitting your portfolio theme change as a pull request?
