### ISSUE TITLE
Create an account localization

### ISSUE THREAD

**Issue by kcdodd** [pencilblue/pencilblue#579]
When I start typing in the username field, the 'check' box seems to switch from english to romanian.

**Comment by kcdodd** [comment]
Well, looking at the page source ro-ro.js seems to be loaded on *every page*. When page first loads it puts the correct english 'Check', but I guess sign_up.js then goes off of the ro-ro.js that was loaded into the page as I type in the box.

**Comment by markbaird** [comment]
I'm having similar problems with my entire site defaulting to Romanian. I don't think global.localizationLanguage is being set correctly.

**Comment by blakecallens** [comment]
The localization service creates a client side localization object for real time use. It looks like this is always outputting as Romanian. Looking into it.
