### ISSUE TITLE
Migrate user account management to new AngularJS schema

### ISSUE THREAD

**Issue by kcdodd** [pencilblue/pencilblue#580]
I cannot upload a "User photo" from the personal account manager, but I *can* do it from the admin panel. When I upload a user photo from admin panel it appears where it should. But, if I do anything with the personal account (ie hit the save button), then the user photo is wiped out. Just to reiterate, as it is a user photo has to be re-uploaded from the admin panel anytime I change anything from the personal account manager.

**Comment by blakecallens** [comment]
Thanks for the catch. I need to go through the user screens and update them to be inline with the way the admin section now looks and works.

**Comment by blakecallens** [comment]
Pull request #667 submitted.

**Comment by brianhyder** [comment]
@blakecallens We are good to close out this issue correct?

**Comment by blakecallens** [comment]
Yup!
