### ISSUE TITLE
Sample controller demonstration google like search

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#583]
Can someone show me a sample controller to demonstration a google-like search without the template?

**Comment by brianhyder** [comment]
I don't think I fully understand the question.  Are you trying to create a controller for doing site search or are you trying to setup google site search? 

Is it an API call that returns JSON or are you trying to display search results in HTML format?

**Comment by JahlomP** [comment]
I am trying to create a controller for doing site search
I am trying to display search results in HTML format

**Comment by brianhyder** [comment]
Site search isn't something we have attempted to do yet simply because of
its complexities.  You could possibly leverage some of the code for the
site_map.js controller and check all of the items for the given search
criteria.  I don't think it will be performant but it might get you what
you need.

On Sun, May 3, 2015 at 7:47 PM, Precious Jahlom Agboado <
notifications@github.com> wrote:

> I am trying to create a controller for doing site search
> I am trying to display search results in HTML format
>
> On Sun, May 3, 2015 at 10:07 PM Brian <notifications@github.com> wrote:
>
> > I don't think I fully understand the question. Are you trying to create a
> > controller for doing site search or are you trying to setup google site
> > search?
> >
> > Is it an API call that returns JSON or are you trying to display search
> > results in HTML format?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/pencilblue/pencilblue/issues/583#issuecomment-98544416>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/583#issuecomment-98557659>
> .
>



-- 
Brian P. Hyder

**Comment by brianhyder** [comment]
It also appears that as of 2.6 full text search has been made production
ready.  You could add an index to each field of each collection you want to
search (see include/config.js) and then run parallel queries to search for
results (sitemap.js).

On Sun, May 3, 2015 at 8:25 PM, Brian Hyder <brianhyder@gmail.com> wrote:

> Site search isn't something we have attempted to do yet simply because of
> its complexities.  You could possibly leverage some of the code for the
> site_map.js controller and check all of the items for the given search
> criteria.  I don't think it will be performant but it might get you what
> you need.
>
> On Sun, May 3, 2015 at 7:47 PM, Precious Jahlom Agboado <
> notifications@github.com> wrote:
>
>> I am trying to create a controller for doing site search
>> I am trying to display search results in HTML format
>>
>> On Sun, May 3, 2015 at 10:07 PM Brian <notifications@github.com> wrote:
>>
>> > I don't think I fully understand the question. Are you trying to create
>> a
>> > controller for doing site search or are you trying to setup google site
>> > search?
>> >
>> > Is it an API call that returns JSON or are you trying to display search
>> > results in HTML format?
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/pencilblue/pencilblue/issues/583#issuecomment-98544416
>> >
>>
>> > .
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pencilblue/pencilblue/issues/583#issuecomment-98557659>
>> .
>>
>
>
>
> --
> Brian P. Hyder
>



-- 
Brian P. Hyder

**Comment by JahlomP** [comment]
ok
