### ISSUE TITLE
Language in admin is in German?

### ISSUE THREAD

**Issue by t0t** [pencilblue/pencilblue#585]
Hi, I'm in spain and my browser (Chrome) is set to spanish but after installing pencilblue for first time it is all in german¿? How can I fix this?
thanks.

**Comment by brianhyder** [comment]
The language setting comes from the ```Accept-Language``` header that your browser sends to the server.  When no language is present it *should* fall back to the default language specified in the config.js file or ```en_US``` as a last resort.

**Comment by t0t** [comment]
It works now!
