### ISSUE TITLE
A question about using custom objects

### ISSUE THREAD

**Issue by orangedrink** [pencilblue/pencilblue#589]
Maybe a stupid question but I'm not able to find any documentation or examples on this.

I'm trying to use pencilBlue to create some custom objects and display them with an angular template. So far I have a plugin that creates the types and adds an admin page for the "event" custom objects.

My question is how do I now add the custom object to the navigation of the site. I could build a controller and a template and use a link to point to it but I was hoping for something a little more user friendly. My preference would be to either allow for adding the event object directly to the navigation or to allow adding them to a page or article similar to media (I'm hoping to be able to use some custom template I would add to the page or the event as well)

Thanks for all the hard work you guys put into this! If I come up with anything I'll be glad to share my work.

**Comment by blakecallens** [comment]
There would be two ways of accomplishing this:

1. Override the [TopMenuService's](https://github.com/pencilblue/pencilblue/blob/master/include/theme/top_menu.js) getTopMenu function, by creating your own service that extends the TopMenuService.
2. Append your events to the navigation on retrieval of the top menu object.

Obviously, the first one is more repeatable, so it's generally recommended. To inherit the top menu service, you would add the following line to your custom service.

```JavaScript
util.inherits(MyCustomService, pb.TopMenuService);
```

Then you can add your own getTopMenu function to your custom service and it'll override the default one.

**Comment by orangedrink** [comment]
Ok, I'll give that a try. Thanks Blake.
