### ISSUE TITLE
PRODUCTION = yes! . DEV = nope ;(

### ISSUE THREAD

**Issue by t0t** [pencilblue/pencilblue#591]
I'm testing Pencilblue on Cloud server and all is running well on the server
Howto: http://connorhindley.com/2014/11/25/pencilblue-on-openshift/
My testing page: http://openshiftapp-t0thost.rhcloud.com/

The problem is that I can't look that page on a local environment.
My browser doesn't listen to that port, I tried to activate other ports without success. Can you recommend a beginners guide/url to understand how to listen given port?

As a web designer I usually dont worry for that matters because I use Codekit, but now is different... or not?...

thanks a lot,
s.

// local dev settings on config.js
   config = {
      "siteName": "PencilBlue en LOCAL",
      "siteRoot": "http://localhost:8080",
      "siteIP": "0.0.0.0",
      "sitePort": 8080,
      "log_level": "info",
      "db": {
         "type": "mongo",
         "servers": [
            "mongodb://localhost:27017/pencilblue/"
         ],
         "name": "pencilblue",
         "writeConcern": 1
      }
   }

**Comment by markbaird** [comment]
Can you post the log output you get when you start PencilBlue on your local environment? You should see something like the following in the logs:
```
PencilBlue en LOCAL running at site root [http://localhost:8080] on port [8080]
```

You probably have an error message in the logs that will give us a clue as to what the problem is. Do you have MongoDB installed and running before you try starting PencilBlue?

**Comment by t0t** [comment]
hi,

I don't see any log file or folder. Where is stored?

On the terminal:
`t0t-2:openshiftapp o0$ ls`
`LICENSE			controllers		package.json		test`
`README.md		include			pencilblue.js		yuidoc.json`
`bower.json		lib			plugins`
`config.codekit		min			public`
`config.js		nodemon.json		sample.config.js`
`t0t-2:openshiftapp o0$ nodemon pencilblue`
`-bash: nodemon: command not found`
`t0t-2:openshiftapp o0$ pencilblue start`
`env: node: No such file or directory`

I have MongoDB installed on local and running `mongo`

**Comment by markbaird** [comment]
That console output is from your OpenShift server. That has nothing to do with running it locally. You will have to install NodeJS and start the PencilBlue server locally. View the instructions here: https://github.com/pencilblue/pencilblue/wiki/Quickstart:-Installation

**Comment by t0t** [comment]
:sparkles:
Yeah!!! 
After reinstall node it works!!
Thank you Mark!
:sparkles:
