### ISSUE TITLE
Fetch Depth no longer functioning

### ISSUE THREAD

**Issue by tangledpixel** [pencilblue/pencilblue#593]
Update : The issue was between the keyboard and the chair. This is a non-issue. 

To recreate this error : 

1. create a custom object with a child custom object
2. cos.loadTypeByName('parent', function(err, custObjType) {
  cos.findByType(custObjType, { fetch_depth: 2 }, function(err, custObjArray) {
    console.log(custObjArray);
  });
});

Result: This returns the parent object but the child object isn't accessible without further coding.

**Comment by blakecallens** [comment]
Was this a misreported bug?

**Comment by tangledpixel** [comment]
Yes it is, sorry about that.

On Fri, May 8, 2015 at 7:59 AM, Blake Callens <notifications@github.com>
wrote:

> Was this a misreported bug?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/593#issuecomment-100262736>
> .
>



-- 
Jonathan Eustace
CEO | *Tangled*Pixel | 604.782.6662


*WARNING: CONFIDENTIALITY NOTICE*
This message may contain confidential or privileged material or information
which is exempt from disclosure under applicable law. Any use,
dissemination, distribution or copying of this information by anyone other
than the intended recipient is prohibited. If you are not the intended
recipient, or have received this message in error, please immediately reply
to or telephone the sender, permanently destroy any hard copies and delete
this information from your computer. Thank you.
