### ISSUE TITLE
MongoDB error

### ISSUE THREAD

**Issue by jgerardsimcock** [pencilblue/pencilblue#594]
![screen shot 2015-05-09 at 3 32 04 pm](https://cloud.githubusercontent.com/assets/6101444/7551686/a5c90508-f660-11e4-8f92-d04b89056cc1.png)

**Comment by jgerardsimcock** [comment]
I am just getting started with PencilBlue and I got this error as I tried to run it

**Comment by blakecallens** [comment]
Can you set your log level to silly in config.js and rerun?

```Javascript
logging: {
  level: 'silly'
}
```

**Comment by markbaird** [comment]
That looks like the error I get when the MongoDB service isn't running.

**Comment by jgerardsimcock** [comment]
Thanks Mark. That was the problem
