### ISSUE TITLE
TypeError: Cannot read property 'keywords' of undefined

### ISSUE THREAD

**Issue by maxkudla** [pencilblue/pencilblue#601]
Whoops! Something unexpected happened.

TypeError: Cannot read property 'keywords' of undefined
    at /var/www/TEST/pencil/plugins/pencilblue/controllers/index.js:51:64
    at ArticleServiceModule.ArticleService.getMetaInfo (/var/www/TEST/pencil/include/service/entities/article_service.js:479:20)
    at /var/www/TEST/pencil/plugins/pencilblue/controllers/index.js:50:32
    at /var/www/TEST/pencil/node_modules/async/lib/async.js:592:17
    at done (/var/www/TEST/pencil/node_modules/async/lib/async.js:135:19)
    at /var/www/TEST/pencil/node_modules/async/lib/async.js:32:16
    at /var/www/TEST/pencil/node_modules/async/lib/async.js:589:21
    at /var/www/TEST/pencil/plugins/pencilblue/controllers/index.js:196:21
    at /var/www/TEST/pencil/plugins/pencilblue/controllers/index.js:387:17
    at /var/www/TEST/pencil/include/theme/top_menu.js:224:21

This happens at the start, when there is no any article. 
After adding first article, error has gone

**Comment by brianhyder** [comment]
This issue duplicates #600
