### ISSUE TITLE
Add message to console if MongoDB service is unreachable

### ISSUE THREAD

**Issue by blakecallens** [pencilblue/pencilblue#603]
We get at least one "error" reported each week, where the reporter didn't have their MongoDB service running and PB wouldn't start.

We need to add a clear console message in this instance that says, "Make sure that your MongoDB service is running then restart PencilBlue."

**Comment by markbaird** [comment]
Also, your quickstart guide [here](https://github.com/pencilblue/pencilblue/wiki/Quickstart:-Installation) is missing the "start mongodb" step.

**Comment by blakecallens** [comment]
Good catch.
