### ISSUE TITLE
Pencilblue behind proxy in location /blog

### ISSUE THREAD

**Issue by pando85** [pencilblue/pencilblue#608]
I'm trying to run pencilblue with this settings:
* site root is http://myserver.com/blog
* port:80
* siteIP: 0.0.0.0

I'm runing it in machine with local ip: 192.168.0.100 
The main nginx that listen http://myserver.com  where I try to put pencilblue has a rule like this:
location /blog {
proxy_pass http://192.168.0.100
}

I don't understand why nothing is working. When I connect to http://myserver.com/bog it gives me an 404 error not found inside of pencilble and all routes to img seems to be bad like this: http://myserver.com/img/pb_logo.png instead of http://myserver.com/blog/img/pb_logo.png

Thanks for your help.

**Comment by brianhyder** [comment]
I would modify your config.js file to change the logging level to "silly":

```
{
  "logging": {
    "level": "silly"
  }
}
```

That will tell you what PB is interpreting the path as.  Also check what links are being generated in the source.  Our experience is limited with nginx so I'm not sure what side of the fence the issue falls.

**Comment by keithics** [comment]
I think this is the workaround for your problem:
https://github.com/pencilblue/pencilblue/issues/878
