### ISSUE TITLE
The infinite article scroll on the pencilblue theme is loading duplicate articles

### ISSUE THREAD

**Issue by andparker** [pencilblue/pencilblue#609]
I am seeing some weird behavior with the infinite article scroll on the landing page for the pencilblue theme. It is loading articles that may have already been present on the page. I can replicate the issue on a fresh install with only articles created. It looks like this may be caused by how the offset query is set in infinite_article_scroll.js and then used in get_articles.js.

**Comment by brianhyder** [comment]
Just a heads up that I'm working on refactoring a lot of that article stuff.  Hoping to get through it all by the end of next week.  I will probably fix this as part of that refactor.

**Comment by andparker** [comment]
Sounds good Brian. Thanks for the quick response.

**Comment by bambamx** [comment]
Is this thing fixed? i'm facing the same issue here

**Comment by blakecallens** [comment]
It should be fixed in 0.4.1
