### ISSUE TITLE
PencilBlue API for content generation?

### ISSUE THREAD

**Issue by tommedema** [pencilblue/pencilblue#613]
I've got a lot of text data in an existing database (articles) that I would like to programatically publish to a pencil blue website.

What would be the best way to publish this data? The data is categorized by taxonomies (E.g. finance / banking / loans).

I would prefer Pencil blue to read from my existing database, rather than having to synchronize the two databases.

**Comment by brianhyder** [comment]
Couple of questions:
What type of database are you currently try using?
Are you looking to continue to use that dB or migrate to Mongo?

We currently do not support pulling content from multiple sources. This
could most likely be built as a plug-in to consistently pull content from
other db.

Would you mind elaborating on your use case?
