### ISSUE TITLE
Unable to install the WordPress Import Plugin

### ISSUE THREAD

**Issue by MHerbst** [pencilblue/pencilblue#622]
I have installed Pencilblue on a fresh CentOS 7 machine and tried to install the WordPress Import Plugin.
The installation hangs at about 20%. 
![image](https://cloud.githubusercontent.com/assets/616792/7794951/71720e2c-02d0-11e5-9d9a-d8e2f9996874.png)

The log file contains the following message:
![image](https://cloud.githubusercontent.com/assets/616792/7794968/9bd39dac-02d0-11e5-8162-d97b935caede.png)

Then nothing happens. The node.js version is 0.10.38. It seems that the plugin was partially installed. I can open the settings but the "Import" button is missing.

**Comment by brianhyder** [comment]
Thank you for the report. I'll take a look.
If you restart the pencilblue service does the button appear?
Did you install from the cli?
How did you create your config.js file?
Would you mind sharing your config.js file?

**Comment by MHerbst** [comment]
Thanks for the fast answer. 
I have restarted it and got the messages:  "Initialized plugin ... RESULT=[true]". I think that it was only partially installed because the first installation did not finish. The installation of other plugins (e.g. portfolio theme) worked fine.
I have tried the install from the cli and also the manual install by cloning it from github.
For the config.js I used the sample.config.js and only renamed it to config.js. Without any changes.

**Comment by brianhyder** [comment]
Thank you for the clarification. The WP import plug in has dependencies we
have to retrieve from npm using their module. That is why the others
install fine. They do not do the dependency check. I was able to partially
reproduce locally so I'm hoping I can dive in and figure out what is going
on.
