### ISSUE TITLE
Cannot remove child object from custom object

### ISSUE THREAD

**Issue by tangledpixel** [pencilblue/pencilblue#624]
To create this issue : 

(causes the terminal to also spit out :  DAO: getNotIDField is deprecated. Use getNotIdField instead)

1) create a custom object (type a) 

2) create 2 instances of custom object type a 

3) create another custom object (type b) that holds custom object type a as a child object

4) Add one of the custom objects of type a to type b, save

5) Try to remove the child object from the type b instance, save. 
Error: object is still there. 

6) Add the second instance of type a object into type b instance. (now you have two type a instances held by the type b instance) 

7) remove the bottom child object from type b, save. 
Error: object is still there

8) remove the top child object from type b, save
Object is removed. 

9) remove the last child object from type b, save
Error: object is still there.

**Comment by brianhyder** [comment]
Huge thank you for the detailed bug report.  Turns out the library that powers our ```util.deepMerge``` doesn't overwrite arrays.  instead it does a union.  

I've updated the merge logic to be based off of the fields of custom object type.
