### ISSUE TITLE
Should be able to override parameter routes with static routes

### ISSUE THREAD

**Issue by blakecallens** [pencilblue/pencilblue#63]
When defining a route in a plugin, if a static route matches that of a default parameter based route, the static route should take precedence.

Example: /admin/plugins/settings/:id should be able to be overridden by /admin/plugins/settings/my_plugin

**Comment by JahlomP** [comment]
Can this be added to the upcoming 0.4.0?

**Comment by brianhyder** [comment]
No

**Comment by cchatham** [comment]
I would just like to second this enhancement. This has already created issues for us and we have worked around them by extending/overriding the controllers but we end up copy and pasting code. :(

**Comment by brianhyder** [comment]
I go back and forth but I don't think it would be hard to provide this
behavior. What use cases do you have for this?

**Comment by brianhyder** [comment]
Alright, I added this into the 0.4.0 branch.  Give it a go and let me know if you have any issues.
