### ISSUE TITLE
WYSIWYG: Server running on Ubuntu generate ��� when pasting large chunk of text 

### ISSUE THREAD

**Issue by chamrc** [pencilblue/pencilblue#632]
When saving a long article in Chinese, the server save some parts of the text as ���. The text ��� replaces part of the article in completely random positions after each save. This, however, does not happen when I run it using a Mac. The server is running on a Ubuntu 14.04.

Here's a [sample](http://wenjifdc.com/article/The-administrative-licensing-law-of-the-peoples-Republic-of-China).

I was trying to figure out what caused this to happen but couldn't figure it out. :(

**Comment by blakecallens** [comment]
I think this might have to do with UTF-8 encoding. Can you add the following to [line 9 of the article_form Angular controller](https://github.com/pencilblue/pencilblue/blob/master/plugins/pencilblue/templates/angular/admin/content/articles/article_form.html#L9) and see if it solves this?

```javascript
$http.defaults.headers.common = {
  'Content-Type' : 'application/json; charset=UTF-8'
};
```

**Comment by chamrc** [comment]
I tried it, but doesn't seem to work tho. It seems like the server is using 0.3, I'll update it to 0.4 tomorrow and try it out. It turns out that this problem occurs on all OSes including Windows Server 08 x64 and Mac.

**Comment by blakecallens** [comment]
If it persists with 0.4.0. I would log the POST object to the console and see if it contains the unrecognized characters, or if it's something with data storage.

**Comment by chamrc** [comment]
I figured out why. Adding the following line to BaseController and line 9 that you suggested for Angular Controller solves the problem.

```
/**
 *
 * @method getPostData
 * @param {Function} cb
 */
BaseController.prototype.getPostData = function(cb) {
	var body = '';
    this.req.setEncoding('utf8'); // ADD THIS LINE HERE <------------------
    this.req.on('data', function (data) {
        body += data;
        // 1e6 === 1 * Math.pow(10, 6) === 1 * 1000000 ~~~ 1MB
        if (body.length > 1e9) {
            // FLOOD ATTACK OR FAULTY CLIENT, NUKE REQUEST
            cb(new PBError("POST limit reached! Maximum of 1MB.", 400), null);
        }
    });
    this.req.on('end', function () {
    	cb(null, body);
    });
};
```

**Comment by chamrc** [comment]
nvm, that line did not work. :(

It's related to getPostData function in BaseController.

```
BaseController.prototype.getJSONPostParams = function(cb) {
    this.getPostData(function(err, raw){
        console.log(JSON.stringify(raw, null, 4));  // Contains � already
	......
};
```

**Comment by chamrc** [comment]
I ended up using escape and unescape for Unicode, and that works perfectly. A little bit of hack. The way data is appended using req.on('data', function()) doesn't work very well with unicode. I had to encode unicode to ASCII for it to be transmitted properly.

**Comment by blakecallens** [comment]
Thanks, @chamrc.

@brianhyder maybe there's a quick fix to this in the JSONPostParams stuff?

**Comment by brianhyder** [comment]
Ok guys,

  Here is what I know.  We were incorrectly concatenating buffers.  I've created a branch: issue/632.  @chamrc if you could test that out it would greatly appreciated.  Additionally, it appears that Node.js only supports the following encodings natively: 
http://stackoverflow.com/questions/20224791/what-encodings-are-available-node-js

I'd also like to follow up with a couple of questions:
@chamrc Can you point us to a link where you were copying and pasting data that caused the "�" characters?
@chamrc Would also let us know what the browser is sending back for your 'content-type' header when attempting to save an article?
@blakecallens Is it possible to capture "paste" operations into the wysiwyg and change the encoding to UTF-8?  That would ensure that the UI always sends interpretable characters to the server.

**Comment by blakecallens** [comment]
It's possible to force the page to utf-8, which is what the current admin tmp_head does. It's also possible to force Angular to set all $http headers to Content-Type utf-8, which is what the first code snippet I gave @chamrc did.

The only hesitation I have with adding the second option is there are some outliers who may want another encoding. We could set up a template that sets the common $http headers that could be overwritten with a plugin, though.

**Comment by chamrc** [comment]
I'm trying out branch 632 at the moment.

I was using Chrome, but Safari had the same problem.

The URL of the article content can be found [here](http://www.gov.cn/flfg/2005-06/27/content_9899.htm). Copy everything from "中华人民共和国主席令" to "自本法施行之日起停止执行。"

**Comment by chamrc** [comment]
9a7d375 did fix the problem. No longer has that problem.
