### ISSUE TITLE
404 on articles with url value with 12 characters

### ISSUE THREAD

**Issue by btidwell** [pencilblue/pencilblue#633]
For published articles that have a "url" value of exactly 12 characters, we receive a 404 response when trying load the article on the front end.  

In /plugins/pencilblue/controllers/article.js line 84, we check to see if the "custUrl" parameter is a valid ID string. I did some digging into mongodb and bson modules, we eventually end up instantiating an object of type ObjectID as bson's objectid.js isValid() function will validate anything with 12 characters.   validation_service.js line 115 will return "value instanceof ObjectID".  As a result, we get a where clause querying by "_id" when we intend to query by "url".  

To reproduce my initial experience, create and publish an article with url "test-article" and see the 404 view rendered to the user when you visit "http://localhost:8080/article/test-article"

**Comment by brianhyder** [comment]
Thank you for the report.  I'll get this fixed.

**Comment by btidwell** [comment]
Thanks, Brian
