### ISSUE TITLE
Translatable pages/content

### ISSUE THREAD

**Issue by slavajacobson** [pencilblue/pencilblue#644]
Are there any plans to add ability to translate site content to other languages?

**Comment by blakecallens** [comment]
We have no current plans to maintain pencilblue.org in any other language but English, at the moment. If you're referring to localization capabilities in the platform, it's already built in. [Here's the tutorial](https://github.com/pencilblue/pencilblue/wiki/Quickstart:-Localization).

**Comment by slavajacobson** [comment]
I'll clarify

by site content I meant a site hosted by PencilBlue CMS.

So when a user enters content for a certain page, he/she can choose the Language, for example FR for french site content,

and later when visiting the page site.com/fr/page_name

The content for that specific page/URL will display the French content or have a fallback to English content if French content is not available.

Similar to the way it works with Rails Globalize3 gem.
