### ISSUE TITLE
WordPress data import fails

### ISSUE THREAD

**Issue by veimis** [pencilblue/pencilblue#646]
Hi, 

After installing the wp_import plugin the WordPress XML import fails with the following error message:

> Error: The url and type parameters are required. URL=[] TYPE=[page] at UrlServiceModule.UrlService.existsForType (/home/veimis/dippa/pencilblue/include/service/entities/url_service.js:77:16) at /home/veimis/dippa/pencilblue/plugins/wp_import/services/wp_xml_parse.js:296:28 at /home/veimis/dippa/pencilblue/node_modules/async/lib/async.js:610:21 at /home/veimis/dippa/pencilblue/node_modules/async/lib/async.js:249:17 at iterate (/home/veimis/dippa/pencilblue/node_modules/async/lib/async.js:149:13) at /home/veimis/dippa/pencilblue/node_modules/async/lib/async.js:160:25 at /home/veimis/dippa/pencilblue/node_modules/async/lib/async.js:251:21 at /home/veimis/dippa/pencilblue/node_modules/async/lib/async.js:615:34 at /home/veimis/dippa/pencilblue/plugins/wp_import/services/wp_xml_parse.js:302:32 at /home/veimis/dippa/pencilblue/include/service/entities/url_service.js:96:13

Pages from my WordPress site were imported, but the articles were not.
I had default settings (don't create users, download media).
Full log file is [here](https://gist.github.com/veimis/ce1b8addd148283b6b44#file-pb_wp_xml_import-log)
Here is the [WordPress XML file](https://gist.github.com/veimis/25fbf516a0f2c1c643b5#file-pb_wp_export-xml)

**Comment by brianhyder** [comment]
@veimis The issue is that a couple of your pages do not have a value for the post name element: ```<wp:post_name></wp:post_name>```.  For articles, we fallback to another element.  For pages, the fallback wasn't implemented.  I am pushing a fix that will provide the fallback.

**Comment by brianhyder** [comment]
@veimis You should be good to go.  Let me know if you run into any more issues.  Thank you for working with us.  The feedback is greatly appreciated.

**Comment by veimis** [comment]
@brianhyder great thanks! Quick responses are also greatly appreciated. I now have all my pages and articles imported. 

The problematic page was a draft that had not been published and therefore (I believe) had no ```wp:post_name``` -element. Now this draft also had the same ```<title>Klubi</title>``` as an other page. Luckily the other page, as it was published, had ```wp:post_name``` as lower case "klubi". The result was two pages with the same pb headline "Klubi", but different pb page_url "Klubi" and "klubi". Now that's fine, but I was curious what would happen if the title had been lower case. The title being the fallback in case ```wp:post_name``` is empty:
```
// Draft page
<title>klubi</title>
<wp:page_name></wp:page_name>
// Published page
<title>klubi</title>
<wp:page_name>klubi</wp:page_name>
```
The result of this was that only one page was created with headline and page_url being "klubi". The real problem in this was that as the draft (which had no real content) was handled first and imported, but the actual published page was lost (which had real content). The draft was first in the export file. This is not a problem for me right now, but maybe worth looking into at some point. In case you are wondering "klubi" is finnish for a club.

One more thing, the draft page has ```<wp:status>draft</wp:status>``` -element, which I believe is not considered in the import as all the pages were exported with "Published" status.
