### ISSUE TITLE
Resend verification displays "email address has already been verified" for an unverified email

### ISSUE THREAD

**Issue by andparker** [pencilblue/pencilblue#649]
When I try to resend a verification email, *mysite.com/user/resend_verification*, for an unverified user, I am getting the "*email address has already been verified*" error message. 

I believe here, https://github.com/pencilblue/pencilblue/blob/master/plugins/pencilblue/controllers/actions/user/resend_verification.js#L41, the conditional should be checking if the user is NOT null, right? If the user object comes back null, then that means the user hasn't been created/verified yet and we should try to continue the validation before sending the verification email again.

**Comment by brianhyder** [comment]
@andparker You are correct.  I will make the fix.

**Comment by andparker** [comment]
Thanks Brian!
