### ISSUE TITLE
Do not force navigation names and headlines to be unique

### ISSUE THREAD

**Issue by hello-jason** [pencilblue/pencilblue#653]
## Navigation Links

I receive the error `name:The provided name is not unique` when trying to save a navigation link with the same **name** as another navigation link.

In practice, the following menu structure seems perfectly reasonable (notice repeating names under various sections). I feel **unique navigation link names should not be enforced**.

```
+-- Thing 1
|   +-- About
|   +-- Resources
+-- Thing 2
|   +-- About
|   +-- Resources
```

![2015-06-17_11-37-53](https://cloud.githubusercontent.com/assets/1406213/8213166/a86a053e-14e5-11e5-848c-5dd0209379d8.png)

## Articles/Pages

Trying to save a page that has the same Headline as another page gives the generic error `There was an error saving`. After tinkering, I confirmed this is the same issue; it wants Headlines to be unique. Yet, again, I feel pages and articles can share a headline.

![2015-06-17_11-41-46](https://cloud.githubusercontent.com/assets/1406213/8213199/e950dd84-14e5-11e5-9ee2-be10f8c66d8e.png)

**Comment by brianhyder** [comment]
@hello-jason Thanks for reporting the issue.  We are looking to revamp the navigation by EOY 2015.  This is something we will be including in that refactor.  I wanted to give you a heads up as to where the fix for this would fall.  We are also happy to entertain pull requests to alleviate the current pain point.

When it comes to articles and pages I sit on the fence.  For pages I could see this falling alongside your use case.  However, for articles I can't really see a use case where you would have an article with the same headline.  From an SEO perspective it seems less than optimal.

thoughts?

**Comment by hello-jason** [comment]
I see your thought process with the article names, but I frankly believe that it is not the job of PencilBlue to be dictating what users can name their articles and pages, alike.

Perhaps the functionality you are describing could be a warning which warns the user that another article has the same headline, explains potential duplicate content issues, yadda yadda, then lets the user decide what to do. Even better, perhaps this and more could be a separate SEO-oriented plugin which brings some of the great features of Yoast's WordPress plugin. But I feel such a feature in PencilBlue core is too opinionated, more limiting than helpful.

Mongo issues each object a unique identifier, and that is sufficient for identifying article and page uniqueness. I know that WordPress (which PencilBlue references often) does allow repeat page and article titles (everything’s a post under the hood, after all) and it only enforces a unique slug, which makes complete sense.

**Comment by blakecallens** [comment]
@hello-jason we'd welcome any plugins that modify the core functionality to do what you're requesting, but we would need more requests from our community to change this functionality in the core.

**Comment by hello-jason** [comment]
Understood. Closing, since is not a direct issue.
