### ISSUE TITLE
Cannot opt out of sending information

### ISSUE THREAD

**Issue by hello-jason** [pencilblue/pencilblue#654]
To reproduce:

1. Visit `Site Settings` page
1. Change **Help to improve PencilBlue by sending us information about your installation** to `No`
1. Save
1. Refresh page, and now **Help to improve PencilBlue by sending us information about your installation** is set back to `Yes`

![2015-06-17_11-55-28](https://cloud.githubusercontent.com/assets/1406213/8213532/0235a0da-14e8-11e5-92dd-2c41b0b7a74d.png)

I imagine this is simply a UI issue where the page load does not set the value from the database, but I have not confirmed this; it could not be saving to the database at all.

**Comment by blakecallens** [comment]
Thanks for the catch. The setting is being properly saved. It wasn't being prepared properly for passing to the frontend. I'll merge the fix once the Travis build is done.
