### ISSUE TITLE
Scripts not loading on the footer?

### ISSUE THREAD

**Issue by t0t** [pencilblue/pencilblue#655]
hi guys!

I'm learning PB. Trying to make my first theme and understand the architecture. :frog: 
Have you considered to load js on the footer instead of in the header of the page?

thanks.

**Comment by blakecallens** [comment]
You're welcome to do that in your theme. The script tags can be put anywhere.

**Comment by t0t** [comment]
That's why I told you. When I put them on the footer I get errors. Nav not loading.

**Comment by blakecallens** [comment]
Then please post the error log, so we can look at it.

The nav is laid out server side and rendered with the page, and the scripts are just pointing to the libraries themselves (bootstrap, jquery, angular, etc.). Chances are, there's something missing in your setup.

**Comment by t0t** [comment]
ok, sure. 
thanks!
