### ISSUE TITLE
Meta tags of the page and article

### ISSUE THREAD

**Issue by net1313** [pencilblue/pencilblue#658]
Hi everyone,
I try to use Pencilblue with French localization. Why do the meta tags of the page or article are outputted in HTML encode? It concerns title, description, keywords and headline.  
For example, instead of français you get fran &# 231 ; ais. I can't figure out where it is converted (maybe in getMetainfo?), because MongoDB keeps it in utf-8 format, everything is ok.
Don't think that is good for seo.

**Comment by brianhyder** [comment]
@net1313 When elements are rendered we make sure that the text that will be displayed is properly HTML encoded.  Part the npm encoder package we use ```htmlencode``` converts the higher byte characters to ensure proper encoding for browsers.  The ```&#231;``` represents the  ```ç``` character just HTML encoded.

When search engines read the meta tag it will convert the encoding back to the proper character.
