### ISSUE TITLE
Meta tags of the page and article

### ISSUE THREAD

**Issue by net1313** [pencilblue/pencilblue#659]
Hi everyone,
I try to use Pencilblue with French localization. Why do the meta tags of the page or article are outputted in HTML encode?
It concerns title, description, keywords and headline.  
For example, instead of français you get fran &#231 ais. I can't figure out where it is converted (maybe in getMetainfo?), because MongoDB keeps it in utf-8 format, everything is ok.
Don't think that is good for seo.

**Comment by brianhyder** [comment]
See response for #658
