### ISSUE TITLE
Running instance on AWS and cant seem to get the urls right

### ISSUE THREAD

**Issue by nuhuxi** [pencilblue/pencilblue#661]
Hi guys appreciate your help. I have PB running on my dev server and it installed like magic. Very nice product! Tried to install it on my AWS server and for some reason the site urls are screwed up. Here is the config.js file that I am running - there is more to it but the only fields I am changing from the sample are listed here:

    "siteName": "Linked-2",
    "siteRoot": "http://54.153.86.84:3000",
    "sitePort": 3000,
   
    "siteIP": "0.0.0.0"

Another thing - when I want to kill the server - is there a clean way to do it? I have been "ctrl-z'ing" it, which kills the console but the processes don't seem to want to die.

Many thanks. Looking forward to my first project by the way.

**Comment by brianhyder** [comment]
Hey, we can definitely help out. Can you elaborate a bit more on the part
about the urls being screwed up?

**Comment by nuhuxi** [comment]
Hi Brian - I appreciate your help.

As I said, PB is running on my dev server - no problem... I have loaded
some content - it looks really good. I am going to have some questions and
will probably end up writing a theme, which is OK, because clients always
want  this and that. You know what I mean...

On AWS, I installed the cli - no problem. I used 'pbctrl install' and went
through the setup questions. Two things - one preventing further progress,
one just kind of a pain.

1 - The site does not have a url. It's a test site. If I use the following
in config.js:
    "siteRoot": "http://54.153.86.84:3000",
    "sitePort": 3000,
    "siteIP": "0.0.0.0"
I can get http://54.153.86.83:3000/setup to appear. But I suspect that the
site root is incorrect because the console tells me that it would not find:
http://54.153.86.84/js/setup.js
and
http://54.153.86.84/img/pb_logo.png

This leads me to conclude that site root 54.153.86.84 must not be correct
as it cant navigate and find the files it needs to run.

2 - I would like to be able to kill all process associated with port 3000
so that I can restart pb. When I run (at the command line):

lsof -i tcp:3000

I get a list of all the processes that are listening on port 3000. Usually
I just sudo kill the process(es) and everything is good. These processes
don't die however so I have to restart the server which is kinda time
consuming. Is there an easier way for me to accomplish this? I havent run
into this problem before.

Many thanks for your help.
Mark



On Tue, Jun 23, 2015 at 1:10 PM, Brian <notifications@github.com> wrote:

> Hey, we can definitely help out. Can you elaborate a bit more on the part
> about the urls being screwed up?
> On Jun 23, 2015 4:08 PM, "Mark Keckeis" <notifications@github.com> wrote:
>
> > Hi guys appreciate your help. I have PB running on my dev server and it
> > installed like magic. Very nice product! Tried to install it on my AWS
> > server and for some reason the site urls are screwed up. Here is the
> > config.js file that I am running - there is more to it but the only
> fields
> > I am changing from the sample are listed here:
> >
> > "siteName": "Linked-2",
> > "siteRoot": "http://54.153.86.84:3000",
> > "sitePort": 3000,
> >
> > "siteIP": "0.0.0.0"
> >
> > Another thing - when I want to kill the server - is there a clean way to
> > do it? I have been "ctrl-z'ing" it, which kills the console but the
> > processes don't seem to want to die.
> >
> > Many thanks. Looking forward to my first project by the way.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pencilblue/pencilblue/issues/661>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/661#issuecomment-114626952>
> .
>



-- 
     Mark Keckeis
     480-550-8020



Linked-2 Consulting

**Comment by blakecallens** [comment]
I'll let @brianhyder troubleshoot, but you might be more interested in deploying PencilBlue to Elastic Beanstalk. PB has been set up to work well in those types of PaaS environments.

**Comment by nuhuxi** [comment]
OK - I have it running on my dev server without a problem. Havent really
had a problem with anything else.... It ought to work..

On Tue, Jun 23, 2015 at 2:39 PM, Blake Callens <notifications@github.com>
wrote:

> I'll let @brianhyder <https://github.com/brianhyder> troubleshoot, but
> you might be more interested in deploying PencilBlue to Elastic Beanstalk.
> PB has been set up to work well in those types of PaaS environments.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/661#issuecomment-114649238>
> .
>



-- 
     Mark Keckeis
     480-550-8020



Linked-2 Consulting

**Comment by brianhyder** [comment]
Great.  When you are starting PB are you using the CLI or just a basic command like, ```node pencilblue.js```?  

Additionally, would you mind sharing what you needed to change in order to resolve the issue with the URLs?

**Comment by nuhuxi** [comment]
Hey Brian - I dont mind sharing anything.

I am using pbctrl start.

The process seems to behave a little differently on ec2 because I cant use
cntrl-c to kill it. I have to use ctrl-z. I can use cntrl-c on my dev
server. There are a few things that a bit different on ec2 - like I have to
say 'nodejs blah.js' to get a script to run rather than node 'blah.js'. I
dont pay for an elastic beanstalk account.

The reason I think that I have the root of the site wrong in config.js is
because of the 404's.



On Tue, Jun 23, 2015 at 2:53 PM, Brian <notifications@github.com> wrote:

> Great. When you are starting PB are you using the CLI or just a basic
> command like, node pencilblue.js?
>
> Additionally, would you mind sharing what you needed to change in order to
> resolve the issue with the URLs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/661#issuecomment-114653255>
> .
>



-- 
     Mark Keckeis
     480-550-8020



Linked-2 Consulting

**Comment by nuhuxi** [comment]
No - that isnt the problem. I think it is user error..... :-)

**Comment by nuhuxi** [comment]
Well, I have given up. PB went in like a dream on my dev server. But after a few hours of wrestling with it on AWS - it just isn't happening. The only thing I can think of is that it must some sort of firewall issue.

The config.js files are logically equivalent on both AWS and dev. BUT - on AWS I get timeouts and the setup page can't load setup.js. I know that the firewall is letting me through (I am using port 3000) because I get the setup screen. But the setup screen cannot load pb.png or find setup.js so that is far as the process goes. If I look into mongo I can see that no user has been created.

Let me know if you have any ideas. This is a straight install from github using pbctrl install.

**Comment by nuhuxi** [comment]
BTW - I will leave it up if you want to see the behavior. I am sure you have tons of things to do...

54.153.86.84:3000

**Comment by markbaird** [comment]
If it was a firewall issue you wouldn't be able to get to the setup screen. It sounds like the links to some of the static resources aren't using your custom port 3000. Is that what you are seeing in your browser log? Maybe there is a bug in the way the links are built for those resources.

In the mean time, is there any reason you can't run the server on the standard port 80?

Regarding your second question, in a production environment I would recommend running NodeJS as a service using something like [Forever](https://github.com/foreverjs/forever) instead of using the pbctrl tool.

By the way, http://54.153.86.84:3000/ isn't accessible for me. I'm guessing you have your IP address white listed in your AWS security group, so you can see it but others can't.

**Comment by markbaird** [comment]
Also, you said that you don't pay for an Elastic Beanstalk account, but it is actually included in your AWS account. Elastic Beanstalk just sets up your resources, like your EC2 server, for you. Having Elastic Beanstalk create a single EC2 server for you wouldn't cost any more than manually creating one yourself like you are doing now.

You might also be interested in OpenShift Online which is a PaaS built on top of AWS. It is much easier to use than Elastic Beanstalk or any other AWS offering, and has a more generous free tier.

**Comment by nuhuxi** [comment]
Hey mark. I am guilty on a bunch of fronts. Regarding aws... I have had the
account for about a year and have been busy with client stuff so I haven't
really dived that deeply into the aws pool.... I will check it out.

This a server that I make available so that clients can see things. I don't
think 3000 is open to 0.0.0.0.0. I will try it on port 80 this afternoon
and see if it changes anything.

I'll get back to you. Many thanks....

**Comment by markbaird** [comment]
Not sure what OS you are running on your EC2 server, but you will probably need to bind PencilBlue to a higher port like 8080 and then use iptables rules to open port 80 and redirect traffic on that port to 8080. And of course you'll also need to open port 80 in the AWS security group.

**Comment by nuhuxi** [comment]
Well... I run nod servers on port 3000 all the time and have never had a
problem. Server is running Ubuntu 14.04 LTS. Just got back to my office so
I will change it to run on port 80.

Let me ask you something.... Is there a reason I cant sudo kill the node
processes associated with PB? I notice that I have to use cmd-z to kill the
server instead of cmd-c.

Many thanks... I will do the port switch now.

On Wed, Jun 24, 2015 at 12:38 PM, Mark Baird <notifications@github.com>
wrote:

> Not sure what OS you are running on your EC2 server, but you will probably
> need to bind PencilBlue to a higher port like 8080 and then use iptables
> rules to open port 80 and redirect traffic on that port to 8080. And of
> course you'll also need to open port 80 in the AWS security group.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/661#issuecomment-114989227>
> .
>



-- 
     Mark Keckeis
     480-550-8020



Linked-2 Consulting

**Comment by markbaird** [comment]
If you have `self_managed` set to `true` in your config.js file, then there are multiple threads started, including a management process that monitors and restarts the other threads if they die.

**Comment by nuhuxi** [comment]
OK.... how do you kill this thing? Set self_managed to false?

hey BTW - redirected the port to port 80. If you want to see the behavior
go to 54.153.86.83. I redirected port 80 to port 3000. I get the same
behavior. Can find setup.js or pb.png.

Mark

On Wed, Jun 24, 2015 at 2:21 PM, Mark Baird <notifications@github.com>
wrote:

> If you have self_managed set to true in your config.js file, then there
> are multiple threads started, including a management process that monitors
> and restarts the other threads if they die.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/661#issuecomment-115016219>
> .
>



-- 
     Mark Keckeis
     480-550-8020



Linked-2 Consulting

**Comment by markbaird** [comment]
It looks like you still have port 3000 in your PB config somewhere. It is actually trying to get this URL and failing:  http://54.153.86.84:3000/js/setup.js
So I was wrong about it not using port 3000 for those resources.

When I try to get the resource directly at http://54.153.86.84/js/setup.js that also fails.

**Comment by nuhuxi** [comment]
Yeah it is actually listening on port 3000 but all requests to port 80 are
redirected to port 80. You can see that if you got to either 54.153.86.84
or 54.153.86.84:3000. You will get the same 'first login' page for PB.

You also get the same error:

Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
http://54.153.86.84:3000/img/pb_logo.png Failed to load resource:
net::ERR_CONNECTION_TIMED_OUT

and if you go through the process - you will see that the
checkPasswordMatch function cant be found because it cant load setup.js.
It just is unable to find it.....

Weird that i cloned the exact same code onto my dev server and had no probs
whatsoever..... That went like a dream.



On Wed, Jun 24, 2015 at 3:24 PM, Mark Baird <notifications@github.com>
wrote:

> It looks like you still have port 3000 in your PB config somewhere. It is
> actually trying to get this URL and failing:
> http://54.153.86.84:3000/js/setup.js
> So I was wrong about it not using port 3000 for those resources.
>
> When I try to get the resource directly at http://54.153.86.84/js/setup.js
> that also fails.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/661#issuecomment-115029498>
> .
>



-- 
     Mark Keckeis
     480-550-8020



Linked-2 Consulting

**Comment by nuhuxi** [comment]
oops all requests to port 80 are redirected to port 3000....

On Wed, Jun 24, 2015 at 3:52 PM, Mark Keckeis <mark.keckeis@gmail.com>
wrote:

> Yeah it is actually listening on port 3000 but all requests to port 80 are
> redirected to port 80. You can see that if you got to either 54.153.86.84
> or 54.153.86.84:3000. You will get the same 'first login' page for PB.
>
> You also get the same error:
>
> Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
> http://54.153.86.84:3000/img/pb_logo.png Failed to load resource:
> net::ERR_CONNECTION_TIMED_OUT
>
> and if you go through the process - you will see that the
> checkPasswordMatch function cant be found because it cant load setup.js.
> It just is unable to find it.....
>
> Weird that i cloned the exact same code onto my dev server and had no
> probs whatsoever..... That went like a dream.
>
>
>
> On Wed, Jun 24, 2015 at 3:24 PM, Mark Baird <notifications@github.com>
> wrote:
>
>> It looks like you still have port 3000 in your PB config somewhere. It is
>> actually trying to get this URL and failing:
>> http://54.153.86.84:3000/js/setup.js
>> So I was wrong about it not using port 3000 for those resources.
>>
>> When I try to get the resource directly at
>> http://54.153.86.84/js/setup.js that also fails.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pencilblue/pencilblue/issues/661#issuecomment-115029498>
>> .
>>
>
>
>
> --
>      Mark Keckeis
>      480-550-8020
>
>
>
> Linked-2 Consulting
>
>
>
>
>
>


-- 
     Mark Keckeis
     480-550-8020



Linked-2 Consulting

**Comment by markbaird** [comment]
How are you doing the port forward/redirect? Are you running PencilBlue behind some sort of reverse proxy like HAproxy or Nginx?

**Comment by nuhuxi** [comment]
I am using this chuck of code which  has worked for me in other instances
like this.

sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT
--to-port 3000

I don't know the pb code but if you look at what it looking for - it's off
by one directory.... both of these files are in the public directory. The
should have './public/...' in front of them.



On Wed, Jun 24, 2015 at 4:04 PM, Mark Baird <notifications@github.com>
wrote:

> How are you doing the port forward/redirect? Are you running PencilBlue
> behind some sort of reverse proxy like HAproxy or Nginx?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/661#issuecomment-115041323>
> .
>



-- 
     Mark Keckeis
     480-550-8020



Linked-2 Consulting

**Comment by markbaird** [comment]
Can you try removing the port from your siteRoot setting?

**Comment by nuhuxi** [comment]
I tried that.... Didnt do anything... Same results. Try it your self... It
is running using forever.... it is not redirected from port 80 at the
moment so you will have to access 54.153.86.83:3000

Sorta weird... At first it says checkPasswordMatch is not defined. Usually
that means that node found at least one script - ran it and there was some
problem with this function which is in a file that it cant find. So it is
finding some of the scripts - but not the ones in the public folder... at
the very least...

On Wed, Jun 24, 2015 at 4:40 PM, Mark Baird <notifications@github.com>
wrote:

> Can you try removing the port from your siteRoot setting?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/661#issuecomment-115046497>
> .
>



-- 
     Mark Keckeis
     480-550-8020



Linked-2 Consulting

**Comment by blakecallens** [comment]
@nuhuxi perhaps at this point you should try a different method of deployment. PB has been deployed on AWS and Elastic Beanstalk, so it's definitely something in your custom setup. I recommend a PaaS, since they're geared for optimized Node.js deployments.

@markbaird thanks for helping out with this!

**Comment by nuhuxi** [comment]
Blake and Mark - thanks for all of the help.

Best regards,
Mark

On Wed, Jun 24, 2015 at 5:09 PM, Blake Callens <notifications@github.com>
wrote:

> @nuhuxi <https://github.com/nuhuxi> perhaps at this point you should try
> a different method of deployment. PB has been deployed on AWS and Elastic
> Beanstalk, so it's definitely something in your custom setup. I recommend a
> PaaS, since they're geared for optimized Node.js deployments.
>
> @markbaird <https://github.com/markbaird> thanks for helping out with
> this!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/661#issuecomment-115051155>
> .
>



-- 
     Mark Keckeis
     480-550-8020



Linked-2 Consulting

**Comment by nuhuxi** [comment]
Guys - I have a project and would really like to find a node based cms to
use for it. I appreciate your help yesterday and after a few hours of
tweaking on the installation, I agreed with you that maybe my server was
jacked up in some way and was screwing up the installation. So this morning
I provisioned a brand new AWS Ubuntu 14.04 LTS server. I followed the
instructions on the site installing git, mongodb, pencilblue-cli and then
pencilblue. Seems like this should work as I have done almost nothing
(other than edit config.js so that I didnt have to restart the server to
kill the pencilblue processes).

The behavior was exactly the same as it was on my first server. I wont bug
with you this anymore. If you want to send me a public key, you can ssh
into the server yourself. I appreciate your time.

Mark

On Wed, Jun 24, 2015 at 5:18 PM, Mark Keckeis <mark.keckeis@gmail.com>
wrote:

> Blake and Mark - thanks for all of the help.
>
> Best regards,
> Mark
>
> On Wed, Jun 24, 2015 at 5:09 PM, Blake Callens <notifications@github.com>
> wrote:
>
>> @nuhuxi <https://github.com/nuhuxi> perhaps at this point you should try
>> a different method of deployment. PB has been deployed on AWS and Elastic
>> Beanstalk, so it's definitely something in your custom setup. I recommend a
>> PaaS, since they're geared for optimized Node.js deployments.
>>
>> @markbaird <https://github.com/markbaird> thanks for helping out with
>> this!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pencilblue/pencilblue/issues/661#issuecomment-115051155>
>> .
>>
>
>
>
> --
>      Mark Keckeis
>      480-550-8020
>
>
>
> Linked-2 Consulting
>
>
>
>
>
>


-- 
     Mark Keckeis
     480-550-8020



Linked-2 Consulting

**Comment by keithics** [comment]
@nuhuxi  pls see my fix/workaround : https://github.com/pencilblue/pencilblue/issues/878
