### ISSUE TITLE
Option to disallow new users from being created

### ISSUE THREAD

**Issue by kevinhikaruevans** [pencilblue/pencilblue#662]
Would it be possible to add an option to prevent new users from being created?

**Comment by brianhyder** [comment]
This clearly needs to be refactored to properly support this but you can do this already by disabling the ```allow_comments``` content setting.  

You can change this setting by going to ```/admin/site_settings/content``` then clicking the comments tab.  Select "No" under "Allow Comments" and then save.  That should cause the user to be redirected to the home page when attempting to access the signup view.

You can see the implementation of the controller here:
https://github.com/pencilblue/pencilblue/blob/master/plugins/pencilblue/controllers/user/sign_up.js#L34

**Comment by brianhyder** [comment]
If you want comments enabled then another option would be to override the route in your theme and just redirect or serve a 404.
