### ISSUE TITLE
gyp and node-pre-gyp erroring during initial installation

### ISSUE THREAD

**Issue by ogrotten** [pencilblue/pencilblue#671]
Install appears to complete, but with significant errors from gyp and node-pre-gyp. Here's the [install log](https://gist.github.com/ogrotten/c7144f35fd7c8c3caf11).

Same string is the result whether I do npm or manual install. I've done nothing to try to fix it as I'm just wanted to try out PB on for size.

node versions, node-gyp  2.0.1, node-pre-gyp 0.6.7
pencilblue versions are different older, 1.0.3 and 0.6.4 respectively

Afterwards, the default site will load the "create admin page", and it appears to act right, but I'm simply not sure it's installed completely.

Please advise.

**Comment by brianhyder** [comment]
Hey, 

  We've never tried to run in a vagrant container before.  Not to say other haven't had success but I personally haven't experimented with it.

It appears from your output that you are running Node 0.10.38.  

Recommendations:
Delete node_modules directory for installation
Upgrade to Node.js 0.12.x
Re-run ```npm install```

**Comment by brianhyder** [comment]
@ogrotten Did you have any success?
