### ISSUE TITLE
Latest installed plugins localization file takes precedence over active theme 

### ISSUE THREAD

**Issue by kylebechtel77** [pencilblue/pencilblue#677]
There are several plugins that have some localized fields that have the same key e.g. 404_error (located in their localization/en-us.json file). I would expect pencilblue to use the active themes localization files, or use the localization files from the plugin that the page's route belongs to, but it does not. Instead, it takes the latest one it comes to in the list of installed plugins.

To replicate this I cloned down the latest pb project, installed sample and set it to active and viewed its page on sample/random/text. Then I edited portfolios localization/en-us.json file to contain "SAMPLE_HELLO_WORLD": "Hello World!!! from portfolio", and installed it, set it to the active theme and viewed it to make sure there were no issues. I then set sample to the active theme again and viewed its page and it said Hello World!!! from portfolio.

**Comment by brianhyder** [comment]
@kylebechtel77 This should have been fixed in the latest merge into 0.5.0.  If you run into issues again please let us know.
