### ISSUE TITLE
ReferenceError: localizationLanguage is not defined

### ISSUE THREAD

**Issue by ticidesign** [pencilblue/pencilblue#681]
I'm creating a new template and in my new controller, this line is not working. 

self.ts.registerLocal('meta_lang', localizationLanguage);

This is the error I get everytime I restart my application:
ReferenceError: localizationLanguage is not defined
    at /Users/andradet/development/au.com.uniting/plugins/uniting/controllers/index.js:172:54

Where can I define this?

**Comment by brianhyder** [comment]
@ticidesign This is an old relic of an earlier version of PB.  We recently went through and cleanup up the remaining references to the global variable ```localizationLanguage```.  It referred to the default language for the system.  

Moving forward, the default language is configurable via the config.js or it will default back to ```en-US```.

To correct the issue please replace the erroring line with:
```
self.ts.registerLocal('meta_lang', pb.config.localization.defaultLocale);
```

**Comment by lukasfrei** [comment]
had the same problem. replaced as you suggested and it works perfectly now!
