### ISSUE TITLE
Add custom dates to each article

### ISSUE THREAD

**Issue by janpetras** [pencilblue/pencilblue#682]
The articles have a published date. What I'd like to do is to have several custom dates instead (4 or 5). What sort of changes would I need to do to achieve this?

**Comment by brianhyder** [comment]
A good place to start would be to look at the portfolio plugin.  It adds a field to the page form.  The approach would be almost identical to adding a field to the article form.

https://github.com/pencilblue/pencilblue/blob/master/plugins/portfolio/templates/admin/content/pages/page_form.html
https://github.com/pencilblue/pencilblue/blob/master/plugins/portfolio/templates/angular/admin/content/pages/page_form.html

**Comment by blakecallens** [comment]
A way to make this work without having to alter the article interface would be to create a custom object that contains the date fields and a peer object of the article type. Then you could add the dates and associate them with the article.
