### ISSUE TITLE
Different articles, same headline

### ISSUE THREAD

**Issue by jsEklund** [pencilblue/pencilblue#683]
As I tested Pencilblue I run into an article bug. As far as I see, it is not possible to save another article with the same headline.

I get the following error: "There was an error saving".

After I change to a headline not in use, it works. Of course i have used different URL's :)

---
Version in use: v0.4.0
Node: v0.12.2

**Comment by brianhyder** [comment]
Duplicates #653 

@jsEklund Thank you for the feature request.  We have gotten this request before and are considering changing the behavior in a later version.  Before we make a decision one way or the other we'd like to get the use cases from our users to validate the need.  If you could post your use case(s) on issue #653 it would be greatly appreciated.

Thanks!
