### ISSUE TITLE
rs command not working

### ISSUE THREAD

**Issue by ticidesign** [pencilblue/pencilblue#686]
I'm building a new theme and after start the app using pbctrl start I can't restart the app using the command line rs as it is in the tutorial. Is there another command? is there another way to restart the local app without the need to close my terminal and open a new tab?

**Comment by blakecallens** [comment]
Do you have nodemon installed?

**Comment by ticidesign** [comment]
Yes

**Comment by blakecallens** [comment]
If you have forever installed too, then that'll take precedence. You can always directly run nodemon (it's usually what I do). Just cd to the install directory and run:

```shell
nodemon pencilblue.js
```

**Comment by brianhyder** [comment]
The launcher does not pass standard input  (stdin) to the child process instance of nodemon that it creates.  There is no special reason to use the command line tool to start pencilblue.  The most convenient way is as Blake mentioned.  Simply run the command, ```nodemon``` or ```nodemon pencilblue.js``` from the root of the pencilblue installation directory and everything should start and provide the ability to exercise the ```rs``` command.
