### ISSUE TITLE
Standalone template of new article published overrides default theme chosen for CMS

### ISSUE THREAD

**Issue by github-ptaylor** [pencilblue/pencilblue#690]
Hello

You can re-create the issue by doing this:

1. install multiple themes
2. add a new article (blog should have a minimum of two articles); choose a template for the article that is different than the chosen theme in (Plugins --> Themes).
3. reload the main page of your CMS

You should see that the main page takes on the theme of the standalone template of the new article.

Patrick

**Comment by brianhyder** [comment]
Confirmed, thank you for reporting.  Looking into it.
