### ISSUE TITLE
PencilBlue Patterns Series

### ISSUE THREAD

**Issue by JuniorHaxe** [pencilblue/pencilblue#695]
PencilBlue Team, I am beginning a PencilBlue Patterns Series to document my journey exploring the source of PencilBlue and comparing it to WordPress. I will be rolling out a few demo projects using the platform. 

In these series, I would like to:

* Develop custom themes and support themes with configurable options for the end-user (much like the WordPress customizer framework)
* Compare and contrast development plugins for PencilBlue versus WordPress. 
* Demonstrate authorization and authentication. I would like to demo custom roles and privileges and enhance the existing security framework to support RBAC. I would like to implement role specific backends and exposed API functionality 
* I would like to demonstrate PB running as a CMS for cloud-connected clients, Angular and React SPA. 

I am busy going through the tutorials and very new to the codebase. Any input or direction as to the PencilBlue-way would be appreciated. 

Cheers,
JH

**Comment by JahlomP** [comment]
Hi, I am around if you need me.

On Wed, Jul 22, 2015 at 1:11 PM Junior Haxe <notifications@github.com>
wrote:

> PencilBlue Team, I am beginning a PencilBlue Patterns Series to document
> my journey exploring the source of PencilBlue and comparing it to
> WordPress. I will be rolling out a few demo projects using the platform.
>
> In these series, I would like to:
>
>    - Develop custom themes and support themes with configurable options
>    for the end-user (much like the WordPress customizer framework)
>    - Compare and contrast development plugins for PencilBlue versus
>    WordPress.
>    - Demonstrate authorization and authentication. I would like to demo
>    custom roles and privileges and enhance the existing security framework to
>    support RBAC. I would like to implement role specific backends and exposed
>    API functionality
>    - I would like to demonstrate PB running as a CMS for cloud-connected
>    clients, Angular and React SPA.
>
> I am busy going through the tutorials and very new to the codebase. Any
> input or direction as to the PencilBlue-way would be appreciated.
>
> Cheers,
> JH
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/695>.
>
-- 
Best Rregards,
Precious Jahlom Agboado,
NibbleIT,
www.twitter.com/jahlomp
+233 54 0915 108.

**Comment by brianhyder** [comment]
@JuniorHaxe We try to keep the tutorials up to date but the videos are probably a bit behind the most efficient way to do certain things.  With each release we update the "sample" plugin to use the latest techniques.  I would use that as a the best source of information.  Aside from that diving into the code that drives each of the areas you would like to compare is best.  We strive to ensure that the code is documented at a function level as well as inline.  Code level documentation can be found here: http://pencilblue.github.io/

If you have specific questions around certain files or the way that certain parts of the core work feel free to reach out here or on Twitter and we'll do what we can to help.

**Comment by JuniorHaxe** [comment]
@brianhyder @JahlomP Thanks for your responses. This project is now in progress and possibly funded.

**Comment by JahlomP** [comment]
No P

On Fri, Aug 7, 2015 at 7:56 PM Junior Haxe <notifications@github.com> wrote:

> @brianhyder <https://github.com/brianhyder> @JahlomP
> <https://github.com/JahlomP> Thanks for your responses. This project is
> now in progress and possibly funded.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/695#issuecomment-128815976>
> .
>
-- 
Best Rregards,
Precious Jahlom Agboado,
www.twitter.com/jahlomp
+233 54 0915 108.

**Comment by brianhyder** [comment]
:+1:
