### ISSUE TITLE
PB Plugin Organization

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#698]
Hello guys, 
I started an initiative I wanted to let you know about and seek for your support.

I have created a GitHub Organization called PB Plugins (https://github.com/pbplugins). My intentions is to have a place where we have opensource PencilBlue plugins. With this any time we have a project we can just go there if a feature we need has been implemented so we don't reinvent the wheel. 

This will not be possible without the help of the community that is why I am reaching out here so you can help out.

Anyone who will want to join the can hit me at jahlomp@gmail.com.

I have initialized 4 plugins. I just realease the first version of one of them and is at https://github.com/pbplugins/pencilblue-social-links. Please check it and the others out and see if you can help out if you may not want to join as a core developer.

**Comment by blakecallens** [comment]
Please use the issues section for bugs and other issues.
