### ISSUE TITLE
[Articles|Comments] Comment Override

### ISSUE THREAD

**Issue by blakecallens** [pencilblue/pencilblue#7]
As an author, I should have the ability to select whether or not my article should allow comments. This override should only work if comments are enabled globally. Meaning that if comments are enabled globally there should be an option on the article to turn them off.
The reasoning is that some articles could be sensitive in nature and targets for inappropriate remarks. These pieces of content should be protected.

**Comment by JahlomP** [comment]
Since it is global, it will affect all articles even those that allows comments.
Adding a setting to article_service for enabling and disabling comments then turning them on or off locally will be a better solution I think.

**Comment by JahlomP** [comment]
I think turning comments off globally will affect some other articles which allow comments. I think a setting should be added to the article service to allow or prevent comments locally on each article.

**Comment by JahlomP** [comment]
I understand your point now

**Comment by JahlomP** [comment]
Can this be closed?
