### ISSUE TITLE
wysiwygElement error

### ISSUE THREAD

**Issue by TriHasmoro** [pencilblue/pencilblue#713]
Found errors while creating or editing Content::Pages and Content::Article (both containing wysiwygElement) in Admin Panel. Firefox 39.0.3

wysiwyg.js (line 82): return $document[0].queryCommandState(type)
[Exception... "Unexpected error"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: http://localhost:8080/js/angular/directives/wysiwyg.js :: .link/scope.isFormatActive :: line 82"  data: no]	

wysiwyg.js (line 61): var block = $document[0].queryCommandValue('formatblock'); 
[Exception... "Unexpected error"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: http://localhost:8080/js/angular/directives/wysiwyg.js :: .link/scope.getCurrentElement :: line 61"  data: no]

**Comment by blakecallens** [comment]
Can you give us steps to reproduce? You're the first to report this type of error. Thanks.

**Comment by TriHasmoro** [comment]
Did the fresh install and tried the wysiwyg editor in the admin panel (articles and pages). 
I can't delete (it's "backspace" in a non Mac) the text written in the editor and after looking into firebug i found the errors above.

After updating the firefox to version 40.0 on my Yosemite, the error messages are gone, but the symptom (the text can not be deleted) remains.

**Comment by blakecallens** [comment]
The issue with the errors was a Firefox bug with supporting queryCommandValue and queryCommandState. Recommended action is for users to upgrade to the latest version of Firefox.

Looking into the backspace issue.

**Comment by blakecallens** [comment]
Bug has to do with rangy and Firefox. Looking into it.

**Comment by blakecallens** [comment]
@TriHasmoro please give branch [PB713](https://github.com/pencilblue/pencilblue/tree/PB713) a run and let me know if backspace is working for you. Thanks.

**Comment by TriHasmoro** [comment]
Great, now it's working! Good job, mate.
Thanks
