### ISSUE TITLE
Embed.ly Integration Plugin Ideas 

### ISSUE THREAD

**Issue by JuniorHaxe** [pencilblue/pencilblue#716]
Requirement: when a user associates remote media with an article, I want to run a query against an external API like (e.x. Embed.ly API) to append that media instance with additional meta data. Secondly, when a listing of articles or a single article is displayed, I want to use a custom template decoration (for example to credit the source reference). 

Obviously, we will need a custom plugin and the API access data to be stored as settings. I am not sure as the best integration strategy with the core. I had considered even a custom object (?) that would get created once the user creates the association. 

Suggestions to point me in the right direction?

**Comment by blakecallens** [comment]
For the first one, I think you could pull that off with the BaseObjectService. @brianhyder, does that sound right?

For the second one, you could probably just replace the default media html template with one that has the fields you need.

**Comment by JuniorHaxe** [comment]
I had thought about overriding and extending the base media type directly, actually. Ideas? 

I implemented the screen flow this evening for a more robust catalog manager. Painless in PencilBlue.

**Comment by blakecallens** [comment]
@brianhyder can talk to you better than I can about overriding MediaProviders and MediaRenderers.

**Comment by brianhyder** [comment]
The MediaService doesn't currently extend the base object service so media events are currently not possible to register for.  I do not believe there is going to be an easy way to do this without extending the current MediaService implementation or MediaRenderer implementation.

**Comment by blakecallens** [comment]
If that's the case, maybe he can override the template that powers the media association drag and drop and add a frontend listener.

**Comment by JuniorHaxe** [comment]
@blakecallens I agree. Clever admin template extension and relationship to custom object will do the trick. Will release as plugin.
