### ISSUE TITLE
Custom Object Conditional, Related, Dependent, and LifeCycle Fields Plugin Ideas

### ISSUE THREAD

**Issue by JuniorHaxe** [pencilblue/pencilblue#717]
Requirement:  I would like to create custom objects with fields dependent on other fields. The would be disabled, enabled, and derived when another field in the custom object is activated.

Example: if users selects external media, the 'used under license' drop down would appear. Or, if I select California, and select list of 'freedoms I view not important' would appear. Is this possible in PencilBlue? Possibly a simple override of admin page template for the custom object in question?

**Comment by blakecallens** [comment]
What you're going to want to do here is create your own admin page for this and then use Angular to drive the interface. Take a look at the Portfolio plugin's home page settings page to see how to make a custom admin page. You might also want to create a custom navigation item for this. There's an example in the sample plugin.

You'll then create a custom controller to take the post from your page and use the CustomObjectService to save the data in the proper custom object schema.

**Comment by JuniorHaxe** [comment]
Roger, that. The custom admin route made this a cake feature to implement.
