### ISSUE TITLE
Depricated Warnings

### ISSUE THREAD

**Issue by sganz** [pencilblue/pencilblue#721]
Don't want to overload the list of issues, would you find any value in seeing the console warnings that I come across as I play around? 

I see things of this nature -

*2015-08-19T20:35:15.812Z - warn: [1] PencilBlue: pb.users is deprecated.  Use new pb.UserService(context) instead 0*

**Comment by blakecallens** [comment]
These are correct notifications that things in use will soon be deprecated. We'll be changing the core code to the newer functions in the future.
