### ISSUE TITLE
Enhancement [IDEA] - Localization/Dynamic Template Plugin

### ISSUE THREAD

**Issue by JuniorHaxe2** [pencilblue/pencilblue#724]
Idea: I want to be able to edit localization strings on the backend in the admin area or have templates for pages where the author populates the fields when used. 

Ex: The localization service details a listing of all localized strings in use on an install. I as the admin can then create new language versions of my site, with the ability to override or extend any localization template call. 

Ex: I am a news agency. I want to write articles in multiple languages using one template.

Ex: An article or page template, where the layout  provides fields filled in the backend when the template is used.  (A custom page object?)

**Comment by blakecallens** [comment]
You could write a plugin that passes new values to the LocalizationService and stores them in the cache when you update the values.
