### ISSUE TITLE
Portfolio Theme Homepage Settings WYSIWYG element causing angular error on v.0.4.1

### ISSUE THREAD

**Issue by jasonsalzman** [pencilblue/pencilblue#725]
On a fresh install of pencilblue, I sign into the admin and then activate the Portfolio theme included with the repo. Then go to settings>Homepage settings and the page only partially loads (as seen in screenshot below) due to an angular module error. The same exact issue occurs with the [devblog theme](https://github.com/pencilblue/devblog-pencilblue). The error is pretty generic, but you can view the angular error output [here](https://goo.gl/w1On4N).

![here](https://cloud.githubusercontent.com/assets/1934760/9396409/b952ee6a-4749-11e5-92ef-c91b51261482.png)

In both themes if you goto page editor the WYSIWYG element loads without any errors. So it doesn't seem like a module is missing or an issue with angular version.

I'm running Chrome v44.0.2403.155 on OSX 10.10.4, but also tried in Firefox v39.0.3 and Safari v8.0.7 with the same results.

**Comment by brianhyder** [comment]
This is confirmed.  @blakecallens I'll try and gather a few more details but can you take a look at this one?  My best guess is that this is wysiwyg related.
