### ISSUE TITLE
Issue using new events emitted by BaseObjectService

### ISSUE THREAD

**Issue by markbaird** [pencilblue/pencilblue#739]
I'm working on some plugins to integrate with third party tools and services (CloudFlare and Sendy). I need to be able to make some API calls to those third party services when an article is created or updated. So I created a new plugin and added the following line to the main plugin module:
`BaseObjectService.on('article.' + BaseObjectService.AFTER_SAVE, CloudFlareService.afterSave);`

However my `afterSave()` function is never called. I tried tracking down the issue by setting breakpoints in BaseObjectService, but they were never hit. So I viewed the actual API calls being made by the browser when the admin saves a page, and those are going to `ArticleApiController -> BaseAdminController -> SiteQueryService -> DAO`. So it looks like the ArticleService/BaseObjectService isn't being used at all when an article is saved.

Am I just going about this all wrong? Or is this a known issue, currently being worked on? It seems that the SiteQueryService is a wrapper for the DAO (it says so in the comments) that is bypassing the object service implementations. It seems like it would be better if it called the object services (ArticleService, PageService, etc.) but it isn't clear to me how it would know which one to call.

**Comment by brianhyder** [comment]
@markbaird can you provide the URL that you are hitting to expect your afterSave function to be called?

My guess is that it is the end-point called when the article is saved from the admin UI.  If this is the case then you are correct.  The afterSave function would not be called.  We haven't yet gotten all of the controllers converted over to utilize the new article service.  

Not 100% sure if it is as simple as changing the resource URL in the form or if the controller needs to be updated.  Most likely, it is both.  

@blakecallens was targeting the conversion of the controllers between now and the 4th quarter.

**Comment by markbaird** [comment]
Yes it is the end-point that is called when the article is saved from the admin UI. So basically I'm trying to use a feature that isn't implemented yet.

I'd be interested in helping to implement this feature, given some guidance on how you envisioned it working. It doesn't appear to be as simple as swapping out the ArticleService for the ArticleServiceV2 in the controller.

Thanks

**Comment by brianhyder** [comment]
We would be thrilled to have the help.

UI:
* Change the URI path to the new API end-point: ```/api/content/articles```
* Ensure the date fields send the values back in ISO format as a string
* Ensure the meta-keywords are sent back as an array of strings
* Update portfolio form to do the same thing

Controllers (new_article.js & edit_article.js):
* Deprecate the controller in the prototype comments

**Comment by markbaird** [comment]
I'll work on this. You can assign the issue to me if you want.

**Comment by blakecallens** [comment]
Awesome! I'll start my reconfiguration work with topics. Let's compare when we're done and set up a standard method.

**Comment by blakecallens** [comment]
I took my first pass at Manage Topics today. I decided to go with the original plan for the refactor of moving to factories, but I didn't use ng-resource. It would just be another bower/cdn library that would need to be managed and could break the admin section when people upgrade to 0.5.0.

[Here's a code comparison to 0.5.0](https://github.com/pencilblue/pencilblue/compare/0.5.0...factories). Let me know what you think, @brianhyder and @markbaird.

**Comment by brianhyder** [comment]
@blakecallens I mentioned a couple of weeks ago that there are already APIs in place for Topics, comments, and articles.  Your ```get_topics.js``` file is not needed.

**Comment by blakecallens** [comment]
I see the topics_api_controller, but it doesn't have any content. What do you expect to be there?

**Comment by brianhyder** [comment]
The [TopicApiController](https://github.com/pencilblue/pencilblue/blob/0.5.0/plugins/pencilblue/controllers/api/content/topic_api_controller.js) extends from the [BaseApiController](https://github.com/pencilblue/pencilblue/blob/0.5.0/controllers/api/base_api_controller.js).  The base API controller eliminates all of the duplicate code needed for CRUD operations by leveraging the object specific implementation of a BaseObjectService.  The routes for the topics API are already registered in the ```routes.js``` file.  

If you run into a situation where the API does not already exist let me know so it can be implemented in a consistent manner to everything else.

**Comment by blakecallens** [comment]
Ok, updated to the existing controllers.

**Comment by brianhyder** [comment]
It looks good @blakecallens! Thank you!

Optimizations we need to talk through at some point:
* Passing options to the ```getTopics``` such as limit offset and filters.  The pattern for this is already built into the base API controller we just need to figure out how to handle it on the UI side.
* Returning the paging wrapper back instead of just the data.  To prevent mis-use the new API controllers impose a max limit on the number of results returned (1K I *think*)
