### ISSUE TITLE
Pencilblue does not work in some browsers.

### ISSUE THREAD

**Issue by meqube** [pencilblue/pencilblue#740]
Hello,
I am having some trouble with Pencilblue in some browsers. For example does the save buttons and some other functions not work in Safari (i tested in 8) and Internet Explorer (i tested in IE 9). How can i fix this problem?

**This is the console log error that i get in Safari when i try to go to the "pages" page:**
    Error: undefined is not an object (evaluating 'loc.pages')

**Comment by blakecallens** [comment]
I confirmed PB running properly in Safari 8.0.3 and IE8 (although we don't officially support IE8). Can you share details on your installation, so we can narrow down what your issue might be?

**Comment by SuperNovaJD** [comment]
Hello, I am trying to use IE11, however it seems doesn't work in IE11. Could you share any details about that and how can I solve that ?

**Comment by blakecallens** [comment]
@SuperNovaJD we're unable to reproduce on our end. Can you send any IE console output?
