### ISSUE TITLE
Angular error ni admin plugin settings home page 

### ISSUE THREAD

**Issue by Jean-PhilippeD** [pencilblue/pencilblue#743]
Hi,

I'm new to node.js, angular and so pencilblue :)
I've read many docs, watch some good videos of Blake and now ...  I'm stuck ! 

First, I've just copied portofilio plugin and renamed it.
Then, I've subsitute all portofolio by <myname>.

And It works well when I click on Settings in the plugin home page.

Then I decided to remove things I don't need, I removed media stuff in the controller and I removed the 2 last tabs. before sending it to AngularObjects method

And Then It was still working well.

So I decided to clean the template file, I remove all the stuff in "home_page_settings.html".
And then I get an Angular error and almost blank page !

Adding and removing piece of html, I finally found that the error occur just if I remove the ^tmp_admin=elements=inline_media^ (inside the div tab which I removed in the controller, so it's hidden by the way).

When I put it back, The page works fine, and clearly if I remove it, the page is almost blank and Angular is broken.

I have no idea why It need it .... I've read what's inside inline_media.html but I found nothing what could explain the issue.

What's I'm doing wrong ??

**Comment by Jean-PhilippeD** [comment]
After digging, I've found angular module was still try to load inline_media (and upload_photo + wysiwyg)...
I've got a lot to learn ... 
It's ok for me !

**Comment by brianhyder** [comment]
Glad you were able to get everything situated. Let us know of you run into
any other issues.
