### ISSUE TITLE
WSYWIG Editor - Not working for UL List Items

### ISSUE THREAD

**Issue by thcase** [pencilblue/pencilblue#749]
I am not sure this is an issue with Pencil Blue or the WSYWIG editor you include.  When editing a page in WSYWIG HTML mode and working on a list (bulleted), the editor wants to insert paragraphs between list items and close off the UL element on each item.

Original text:
<ul><li>Ascension Resurrection</li><li>Happy Dragon</li><li>PS/IS 49</li><li>IS 73</li><li>PS 58</li><li>PS/IS 102</li><li>PS 128</li><li>Saint Adalbert School</li></ul>

Edited text:
<ul><li>Ascension Resurrection</li></ul><p></p><ul><li>Happy Dragon abc</li></ul><p></p><ul><li>PS/IS 49</li><li>IS 73</li><li>PS 58</li><li>PS/IS 102</li><li>PS 128</li><li>Saint Adalbert School</li></ul>

**Comment by blakecallens** [comment]
What operating system and browser are you experiencing this in?

We'll take a look at it.

**Comment by thcase** [comment]
I am on a Mac OS X 10.10.5 (Yosemite) with Safari 8.0.8. 

Thomas Case
thcase@outlook.com

**Comment by blakecallens** [comment]
@thcase you can pull the latest version of master and this will be fixed. Thanks for the catch!

**Comment by thcase** [comment]
This fixed the issue.  Editing appears to act as expected now.  Thank you very much for great turn around.  I was also able to figure out how to fetch and merge using git and keep my other changes.
