### ISSUE TITLE
no metho update on when batch.update(item) in dao.saveBatch

### ISSUE THREAD

**Issue by Jean-PhilippeD** [pencilblue/pencilblue#758]
Hello,

While trying to use saveBatch method on DAO, I get this error 
>TypeError: Object [object Object] has no method 'update'

line 461 on dao.js:

>                if (item[DAO.getIdField()]) {
>                    batch.update(item);
>                }
>                else {
>                    batch.insert(item);
>                }

Everything works fine when I insert, but doesn't work with update.
When I print the item before the saveBatch, here what I see :
>{ _id: '1',
>  object_type: 'theme_random',
>  last_modified: Tue Sep 22 2015 17:25:53 GMT+0200 (CEST) }
>2015-09-22T15:25:53.481Z - error: [1] RequestHandler: An error occurred during controller >execution. URL=[DELETE:/actions/admin/content/delete/560172c12cb3bd541d6af6de] ROUTE={"path":"actions/admin/content/delete/:id","pattern":"^/actions/admin/content/delete/[^/]+[/]{0,1}$","path_vars":{"id":5},"expression":{},"themes":{"theme_random":{"DELETE":{"method":"DELETE","path":"/actions/admin/content/delete/:id","auth_required":true,"access_level":2,"content_type":"text/html"}}}}
TypeError: Object [object Object] has no method 'update'

**Comment by brianhyder** [comment]
@Jean-PhilippeD Thanks for reporting.  My guess is that this is a breaking change from when we updated the driver a few months back.  If you have a minute would you mind trying to modify the DAO file to mimic the way the update piece works in this example:
http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#initializeUnorderedBulkOp

**Comment by Jean-PhilippeD** [comment]
This seems to work:

>                if (item[DAO.getIdField()]) {
>                    batch.find({_id: item[DAO.getIdField()]}).updateOne( {$set: item});
>                    //batch.update(item);
>                }

This is working fine if you consider updating the document with only "item" field(s).

If you don't provide $set, it update the whole document (only _id remains unhanged). 
So with the method saveBatch, if you provide _id in the array item, you will only replace some fields.


If you want to replace the whole document, I think you should use :
>batch.find({_id: item[DAO.getIdField()]}).updateOne( item );

It depends what you want, maybe you should add an option somewhere to difference "replace" and "update"

**Comment by brianhyder** [comment]
Awesome. Thank you for doing the heavy lifting on this one. An option seems
like a good idea in this case.

**Comment by brianhyder** [comment]
@Jean-PhilippeD I've created branch https://github.com/pencilblue/pencilblue/tree/issue/758

It should have the fix on it.  Would you mind trying it out for us.  If it is all good I will merge it in.

**Comment by Jean-PhilippeD** [comment]
@brianhyder The fix works nicely ! 
I've both tested "replace:false" and with no options and in the first case, my document has been updated, and in the second case, it has been replaced. 
Exactly what I needed and what's described :)

Thanks !

**Comment by brianhyder** [comment]
Great, thank you for testing it out.
