### ISSUE TITLE
Error: Cannot find module 'async'

### ISSUE THREAD

**Issue by radiovisual** [pencilblue/pencilblue#759]
I just tried installing PencilBlue for the very first time. I followed the instructions line-by-line to get things working on my Mac, and I was greeted with this error:

```
$ pbctrl start
module.js:338
    throw err;
          ^
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/michael/gitprojects/ElectonTest/PencilBlue/pencilblue.js:22:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
Failed to start PencilBlue: {"code":1,"output":"module.js:338\n    throw err;\n          ^\nError: Cannot find module 'async'\n    at Function.Module._resolveFilename (module.js:336:15)\n    at Function.Module._load (module.js:278:25)\n    at Module.require (module.js:365:17)\n    at require (module.js:384:17)\n    at Object.<anonymous> (/Users/michael/gitprojects/ElectonTest/PencilBlue/pencilblue.js:22:19)\n    at Module._compile (module.js:460:26)\n    at Object.Module._extensions..js (module.js:478:10)\n    at Module.load (module.js:355:32)\n    at Function.Module._load (module.js:310:12)\n    at Function.Module.runMain (module.js:501:10)\n"}
```

Has this happened before? I tried running `npm install` thinking maybe I needed to load the dependencies, but that didn't work either (nor was it in the setup instructions).

When I ran `npm install` from my PencilBlue directory, I got this error:

```
npm WARN package.json pencilblue@0.4.1 No license field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.3
npm ERR! path /Users/michael/.npm/npm/2.10.1
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/Users/michael/.npm/npm/2.10.1'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/Users/michael/.npm/npm/2.10.1']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/michael/.npm/npm/2.10.1',
npm ERR!   parent: 'pencilblue' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/michael/gitprojects/ElectonTest/PencilBlue/npm-debug.log
```

**Any ideas?**

**Comment by blakecallens** [comment]
Looks like npm doesn't have write access. [Here's instructions on fixing that](https://docs.npmjs.com/getting-started/fixing-npm-permissions).

**Comment by radiovisual** [comment]
npm has proper write access everywhere else, it seems that the directory created by the PencilBlue-CLI is the only directory that is getting permission issues.

**Comment by blakecallens** [comment]
If that's the case then you can try explicitly setting permissions for the directory or run npm install under sudo.

**Comment by radiovisual** [comment]
Thanks for your help. I was able to get things up and running with `sudo npm install`, but having to force the install of pencilblue's dependencies didn't feel right, since it wasn't one of the installation steps listed on the website. Does the cli look for the existence of the dependencies, and install them if needed, or is the step of installing npm modules missing from the install steps?

**Comment by brianhyder** [comment]
The installer runs the npm install command from the user that triggered the
cli

**Comment by radiovisual** [comment]
Ok, thanks. Well it just seemed like permissions got mangled for this one install. After I ran `sudo npm install` inside the generated pencilblue directory things started working. Just seems weird that I am not having permission issues anywhere else except for on the generated pencilblue folder. Thought I may have stumbled onto something here.

**Comment by brianhyder** [comment]
No problem.  Let us know if you run into any other blockers. We're happy to help.

**Comment by radiovisual** [comment]
@brianhyder . Thanks very much. I appreciate it.
