### ISSUE TITLE
[0.5.0] Unable to uninstall plugin on global site (perhaps only on single site mode)

### ISSUE THREAD

**Issue by blakecallens** [pencilblue/pencilblue#765]
Steps to reproduce:

* Log into your global url in single site mode.
* Install any plugin
* Attempt to uninstall the plugin.

Result: plugin will not uninstall.

**Comment by brianhyder** [comment]
Can you include the output from the job and any console error so we can
identify which step failed?

**Comment by blakecallens** [comment]
No console errors

```
2015-09-25T18:37:22.498Z:[1] UNINSTALL_PLUGIN_pb-site-v2: Updating job [894929b0-145a-4323-af5b-1149973d6e70:UNINSTALL_PLUGIN_pb-site-v2] by 0 percent with status: 
2015-09-25T18:37:22.534Z:[1] UNINSTALL_PLUGIN_pb-site-v2: Calling plugin onUnstall pb-site-v2
2015-09-25T18:37:22.536Z:[1] UNINSTALL_PLUGIN_pb-site-v2: Unregistered 0 routes
2015-09-25T18:37:22.598Z:[1] UNINSTALL_PLUGIN_pb-site-v2: Setting job [894929b0-145a-4323-af5b-1149973d6e70:UNINSTALL_PLUGIN_pb-site-v2] as completed with status: COMPLETED
```

**Comment by cchatham** [comment]
Hey guys we were having issues with this too. @wesanderson303 did you make any head way on why yours was not uninstalling?

**Comment by blakecallens** [comment]
IMO we need to raise this bug to top priority, since it's the only one blocking release of 0.5.0

**Comment by brianhyder** [comment]
@blakecallens Will look into this tonight.  Wanted to get a clarification:

Above you said log into your global site when in single site mode.  Why would you do that?  It should just be your site root correct?  Can you provide the relevant parts of your config.js?

**Comment by blakecallens** [comment]
Right. That's what I meant, global.localhost

**Comment by brianhyder** [comment]
@blakecallens @cchatham I took the configuration that Blake was using.  I was unable to replicate the issue on the 0.5.0 branch.  If you guys have any more information please send it my way.

**Comment by blakecallens** [comment]
I'll try to replicate with a fresh install.

**Comment by wesanderson303** [comment]
I was having this trouble (with the same uninstall logs blake posted above) with a new plugin and diving through the uninstall job (plugin_uninstall_job.js), noticed I was bombing out in the "getLocalizations" task. My plugin was missing a "\public\localization" directory, which caused "getLocalizations" to bomb out, killing the rest of the uninstall process. I'm not super familiar with the job_runner, but I'm guessing the error thrown just needs to be handled better in the uninstall job? Anyways, hopes that gives some clues. Adding "\public\localization" fixed my plugin's uninstallation problem.

**Comment by blakecallens** [comment]
That could definitely be the trigger on ky end too.

**Comment by blakecallens** [comment]
That was it. I added the localization folder and everything uninstalled fine. Looks like we just need to make that folder optional on the uninstall.

**Comment by brianhyder** [comment]
I wanted to say thanks to everyone for digging in and confirming the issue.  I'm looking into the issue now and will put a fix into a pull request tonight.

**Comment by brianhyder** [comment]
I put a fix in a branch issues/765.  I tested it and it appeared to work.  Can I get a second set of eyes to confirm the fix?

**Comment by blakecallens** [comment]
Good on my end!
