### ISSUE TITLE
[0.5.0] External media URLs are rendering incorrectly

### ISSUE THREAD

**Issue by blakecallens** [pencilblue/pencilblue#766]
The base media renderer is tacking on a forward slash to the beginning of every media URL, regardless of the location value. This means that the src of an image can wind up being ```/http://[whatever]'```, causing it to break.

**Comment by markbaird** [comment]
Looks like I introduced this bug. Sorry about that. What is the scenario where this would occur? A media object has a URL stored in the ID field? I'd like to add a unit test for this but I don't understand the use case.

**Comment by blakecallens** [comment]
No worries. This happened when you linked to an external image, like on
imgur.

**Comment by markbaird** [comment]
Ah, I didn't realize it just stored the link. I thought it would download the linked image and store it locally. Guess I've never actually tried that to see what the behavior was.
