### ISSUE TITLE
Searching and displaying custom objects

### ISSUE THREAD

**Issue by bawarchiproject** [pencilblue/pencilblue#768]
Hi,
 I am new to nodejs and have previous done few wordpress builds. i have a custom objects called projects which has a field category. I am trying to search the projects objects using input text field category. It should display all the projects belonging to that category.

My doubt:
1. I am really stuck at displaying the custom object data in my html markup.(It will be good if i get a startup advice on this)
2. Also the search using category. What approach should i take??

**Comment by blakecallens** [comment]
The findBy functions of the CustomObjectService [support the same query options](https://github.com/pencilblue/pencilblue/blob/master/include/service/entities/custom_object_service.js#L200) as DAO.q.

DAO.q has the ['where' option](https://github.com/pencilblue/pencilblue/blob/master/include/dao/dao.js#L218). So you can send in the option of ```{where: {[text_field]: [text_value]}}``` and get only the custom objects that match.
