### ISSUE TITLE
PencilBlue Admin Home not showing news on Safari

### ISSUE THREAD

**Issue by thcase** [pencilblue/pencilblue#769]
The Admin home page for pencil blue doesn't seem to pull in the PencilBlue news.  The spinner keeps going.  I am on Mac OS X 10.10.5 (Yosemite) running Safari 8.0.8 using PencilBlue v0.4.1.  I have attached an image.  This does work in Chrome on the Mac.  The Safari Console log shows the following error:

[Error] Error: undefined is not an object (evaluating 'b.innerHTML.replace')
http://localhost:8081/bower_components/jquery/dist/jquery.min.js:4:21838
access@http://localhost:8081/bower_components/jquery/dist/jquery.min.js:4:3539
html@http://localhost:8081/bower_components/jquery/dist/jquery.min.js:4:21737
http://localhost:8081/admin:226:46
http://localhost:8081/bower_components/angular/angular.min.js:81:27
http://localhost:8081/bower_components/angular/angular.min.js:112:183
$eval@http://localhost:8081/bower_components/angular/angular.min.js:126:250
$digest@http://localhost:8081/bower_components/angular/angular.min.js:123:370
$apply@http://localhost:8081/bower_components/angular/angular.min.js:127:19
l@http://localhost:8081/bower_components/angular/angular.min.js:81:333
w@http://localhost:8081/bower_components/angular/angular.min.js:85:814
onload@http://localhost:8081/bower_components/angular/angular.min.js:86:463
	(anonymous function) (angular.min.js, line 102)
	(anonymous function) (angular.min.js, line 76)
	(anonymous function) (angular.min.js, line 112)
	$eval (angular.min.js, line 126)
	$digest (angular.min.js, line 123)
	$apply (angular.min.js, line 127)
	l (angular.min.js, line 81)
	w (angular.min.js, line 85)
	onload (angular.min.js, line 86)

![screen shot 2015-09-26 at 3 34 33 pm](https://cloud.githubusercontent.com/assets/13628647/10120191/ff62d72a-6464-11e5-8695-10434ae8e22d.png)

**Comment by brianhyder** [comment]
@blakecallens Can you take a look at this when you get a chance.  I was able to replicate.

**Comment by blakecallens** [comment]
Known issue with Safari and XML parsing. I'm on it.
