### ISSUE TITLE
Attaching image cause strange editor behavior

### ISSUE THREAD

**Issue by mykiimike** [pencilblue/pencilblue#770]
Hi team,

When i add an image into a Page i got a strange editor behavior. Actually the dropped image is replicated a lot of time and it breaks all the formatting.
That's very annoying ;) 
Someone can help ?

Thanks 
MV

**Comment by blakecallens** [comment]
Confirmed only happening with images.

**Comment by blakecallens** [comment]
This bug was introduced with the fix for #749. The creation of a p element is duplicating the image.

**Comment by blakecallens** [comment]
The bit of code that was auto creating paragraph tags was breaking the img tags and, as far as I can tell, there's no way for us to make exceptions for img tags. I've removed it for now.

**Comment by brianhyder** [comment]
How does the removal of this code change editor behavior?

**Comment by blakecallens** [comment]
No more auto p tags. Other than that, it'll work exactly the same.
