### ISSUE TITLE
how to display custom objects in a specific template page?

### ISSUE THREAD

**Issue by aquibmomin007** [pencilblue/pencilblue#779]
I have custom objects called publications. i want to display them in a list view. I am new to nodejs. Please help me with which files to edit, how to fetch custom objects and how to display them in a specific template? I googled a lot but didn't find any clear explanation anywhere. And the pencilBlue video regarding custom objects show how to create a custom object and not how to display the custom objects in a template page.

**Comment by blakecallens** [comment]
This is answered in issue #771
