### ISSUE TITLE
Can't get post params

### ISSUE THREAD

**Issue by artembarmin** [pencilblue/pencilblue#781]
Hi. I write my own pencilblue plugin. Here is some code from my plugin controller: 

PeerController.prototype.test = function(cb) {
    cb({
      code: 200,
      content: "All is OK!"
    });
  };

  PeerController.getRoutes = function(cb) {
    var routes = [{
        method: 'get',
        path: "/peerlog",
        handler: 'peerLog',
        auth_required: false,
        content_type: 'text/html'
    },
    {
        method: 'get',
        path: "/peerconnected",
        handler: 'peerConnected',
        auth_required: false,
        content_type: 'text/html'
    },
    {
        method: 'post',
        path: "/test",
        handler: 'test',
        auth_required: false,
        content_type: 'application/x-www-form-urlencoded'
    }];
    cb(null, routes);
  };

How can I get post params from test function?

**Comment by blakecallens** [comment]
[getJSONPostParams()] comes with the BaseController

**Comment by brianhyder** [comment]
```getJSONPostParams``` is deprecated.  Please do not use it.  Instead, please setup your route definition to specify the expected body mime type as demonstrated in the sample plugin with the ```request_body``` property: https://github.com/pencilblue/pencilblue/blob/master/plugins/sample/controllers/api/book_api.js#L75

In your controller's route handler ("render" by default) you can access the params via:
```
Controller.prototype.render = function(cb) {
  console.log(this.body);
};
```

**Comment by artembarmin** [comment]
Thanks for your answer. All works.
