### ISSUE TITLE
Error: MongoError:  sockets closed - mongodb://159.8.128.196:10189/db

### ISSUE THREAD

**Issue by Molnfront** [pencilblue/pencilblue#783]
I get this error on BlueMix when I try to deploy:
Error: MongoError: server 159.8.128.196:10189 sockets closed - mongodb://159.8.128.196:10189/db

My conf.js:

module.exports = {
    "siteName": "test",
    "siteRoot": "http://test.eu-gb.mybluemix.net",
    "logging": {
    "level": "info"
    },
    "db": {
        "type": "mongo",
        "servers": [
            "mongodb://xxxxxnjjdujrjfjfgjgjkrgjkngkjkg:hbhefbhjfbgjhbrfghjb@159.8.128.196:10189/"
        ],
        "name": "db",
        "authentication": {
            "un": "xxxxxnjjdujrjfjfgjgjkrgjkngkjkg",
            "pw": "hbhefbhjfbgjhbrfghjb"
        },
        "writeConcern": 1
    }

Mongodb manifest looks like this:
{
  "mongodb-2.4": [
    {
      "name": "mongodb01",
      "label": "mongodb-2.4",
      "plan": "100",
      "credentials": {
        "hostname": "159.8.128.196",
        "host": "159.8.128.196",
        "port": 10189,
        "username": "xxxxxnjjdujrjfjfgjgjkrgjkngkjkg",
        "password": "hbhefbhjfbgjhbrfghjb",
        "name": "664fc563-d212-4f56-bf13-1c7abb8168ba",
        "db": "db",
        "url": "mongodb://1c08ca4c-4692-41bf-b4ee-251535ce28ea:3b929ddb-5db0-4f65-a5b8-da3f90a14213@159.8.128.196:10189/db"
      }
    }
  ]
}

I have tried every possible combination:
mongodb://159.8.128.196:10189/
mongodb://159.8.128.196:10189/db
mongodb://159.8.128.196:10189/db/

Also tried to hard code it in the db_manager:

var dbURL = "mongodb://xxxxxnjjdujrjfjfgjgjkrgjkngkjkg:hbhefbhjfbgjhbrfghjb@159.8.128.196:10189/db";
      
 What am I missing?

No luck yet.

**Comment by brianhyder** [comment]
Couple of questions:
1. What version of PB are you working from?
2. Can you connect to your DB instance through a different client?

**Comment by Molnfront** [comment]
1. 0.4.1 the version you build with the CLI.
2. No. IN BlueMix you can not connect to an experimental MongoDB service remotely. 

My next trial will be to delete all from BlueMix and try again. My problem right now is that I can not delete...

Maybe i test if a BluMix Docer Container is more practical.

**Comment by blakecallens** [comment]
Have you followed the Bluemix tutorial in the quickstart guide?

**Comment by Molnfront** [comment]
Yes the one in the Wiki!

**Comment by Molnfront** [comment]
Did a new setup. This time I used the web gui to set up the SDK for node and only cf push for the PB and it works!
I have slightly changed the setup procedure by adding a manifest instead of a proc file.

I don not like that I can not do all the build steps from command line. If one could check for the mongodb credentials in the env it could be automated like this:

var mongo = process.env.VCAP_SERVICES;
var port = process.env.PORT || 3030;
var conn_str = "";
if (mongo) {
  var env = JSON.parse(mongo);
  if (env['mongodb-2.4']) {
    mongo = env['mongodb-2.4'][0]['credentials'];
    if (mongo.url) {
      conn_str = mongo.url;
    } else {
      console.log("No mongo found");
    }  
  } else {
    conn_str = 'mongodb://localhost:27017';
  }
} else {
  conn_str = 'mongodb://localhost:27017';
}

**Comment by Molnfront** [comment]
I have done a quick hack to add VCAP_SERVICES:  https://gist.github.com/Molnfront/c9552bb50fa66fad03b2#file-config-js
