### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by bohdanafanasyev** [pencilblue/pencilblue#784]
Greetings, 
I am pretty new to mean stack development, but would like to learn. While trying to run pencilblue using pbctrl start, I get following error:

Override file [/Users/Illusion/peter/config.js] will be applied.
2015-10-12T12:36:29.683Z - info: [M] SystemStartup: Log Level is: info
2015-10-12T12:36:29.992Z - info: [M] System[M]: 1 workers spawned. Listening for disconnects.
Override file [/Users/Illusion/peter/config.js] will be applied.
2015-10-12T12:36:30.231Z - info: [1] SystemStartup: Log Level is: info
/Users/Illusion/peter/node_modules/mongodb/lib/server.js:228
        process.nextTick(function() { throw err; })
                                      ^

Error: MongoError: connect ECONNREFUSED 127.0.0.1:27017 - mongodb://127.0.0.1:27017/pencilblue
Is your instance running?
    at /Users/Illusion/peter/include/dao/db_manager.js:84:31
    at /Users/Illusion/peter/node_modules/mongodb/lib/mongo_client.js:236:20
    at /Users/Illusion/peter/node_modules/mongodb/lib/db.js:203:14
    at null.<anonymous> (/Users/Illusion/peter/node_modules/mongodb/lib/server.js:226:9)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at null.<anonymous> (/Users/Illusion/peter/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:255:68)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
Override file [/Users/Illusion/peter/config.js] will be applied.
2015-10-12T12:36:30.900Z - info: [2] SystemStartup: Log Level is: info
/Users/Illusion/peter/node_modules/mongodb/lib/server.js:228
        process.nextTick(function() { throw err; })

Can you please suggest what has been done wrong?

**Comment by brianhyder** [comment]
As the error suggests PencilBlue cannot connect to your mongo DB instance.  Please check to make sure that mongo DB is running on your local environment at the default port (27017) and then restart your PencilBlue Instance

**Comment by bohdanafanasyev** [comment]
I will appreciate a lot if you could point me to some place where I can read how to achieve that :)

**Comment by brianhyder** [comment]
Download & install MongoDB from: https://www.mongodb.org/downloads#production
Installation instructions are provided at the link above.  Starting the mongo server is OS dependent but on linux systems it is: ```mongod```

**Comment by bohdanafanasyev** [comment]
As a result the it was very easy to resolve that problem by simple running mongoDB before starting the server by sudo mongod, maybe its obvious for experienced user, but for beginner like me it took some time, please include in installation guide that mongoDB should be run before you start pencilblue, thank you! :)
