### ISSUE TITLE
Trouble installing PencilBlue on Centos 7 1503-01

### ISSUE THREAD

**Issue by yokotsumo** [pencilblue/pencilblue#795]
Hi,

I have trouble installing PencilBlue on CentOS 7 1503-01. CentOS is hosted on a Hyper-V virtual machine on Windows 10 with a 192.168.1.199 IP.
I followed the Github install instructions and everythig seemed to be fine. 
After pbctrl install [], I keep the default settings, except for the server address where I put http://192.168.1.199:8080.
I type pbctrl start and get this output:

[root@pc13 PencilBlue]# pbctrl start &
[1] 2591
[root@pc13 PencilBlue]# Override file [/home/admin/web/default.domain/public_html/PencilBlue/config.js] will be applied.
2015-11-01T16:53:50.040Z - info: [M] SystemStartup: Log Level is: info
2015-11-01T16:53:50.411Z - info: [M] System[M]: 1 workers spawned. Listening for disconnects.
Override file [/home/admin/web/default.domain/public_html/PencilBlue/config.js] will be applied.
2015-11-01T16:53:50.611Z - info: [1] SystemStartup: Log Level is: info
2015-11-01T16:53:51.095Z - info: [1] PencilBlue: Ensuring indices...
2015-11-01T16:53:51.126Z - info: [1] PencilBlue: My PencilBlue Site running at site root [http://192.168.1.199:8080] on port [8080]
2015-11-01T16:53:51.181Z - info: [1] PencilBlue: Ready to run!

A netstat command gives me:
[root@pc13 PencilBlue]# netstat -an | grep 8080
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN

The problem is that if I enter the 'http://192.168.1.199:8080' address in a browser, the webpage is not accessible. I have disabled all firewall protections on my computer.

This type of configuration is working fine with a more standard WordPress configuration.

Can you help me?

**Comment by brianhyder** [comment]
Everything from the output above suggests that PB started normally and is accessible.  Were you attempting to access the URL from a browser in windows or from the virtual machine?  My guess is that it is a bridging problem between the host networking and the virtual machine because the netstat output shows that it is wildcarded and hasn't bound to a specific IP.  

If you attempt to access the site through curl or a browser in Cent OS what happens?

**Comment by yokotsumo** [comment]
The port 8080 is indeed listening but no assigned to an IP (as it is correctly done on the other WP VM). I tried to access the website from Windows, not the VM. When I try to access the website (192.168.1.199:8080) from the VM with curl, I get this (with a 'pbctrl start &' launched in the same terminal):

[root@pc11 PencilBlue]# curl http://192.168.1.199:8080
2015-11-02T08:52:17.097Z - warn: [1] RequestHandler: The active theme is not set.  Defaulting to 'pencilblue'

**Comment by yokotsumo** [comment]
It was really stupid in fact. The built-in firewall of centOS was blocking the traffic. Just disable it or had corresponding rules.
