### ISSUE TITLE
Creating Multilingual Sites 

### ISSUE THREAD

**Issue by daslicht** [pencilblue/pencilblue#796]
Hi,
is it possible to create a multilingual webpage (multilingual slugs and content) with pencilblue?
Cheers
Marc

**Comment by brianhyder** [comment]
The upcoming release will have this capability.  The current 0.5.0 branch already has multi-site and localized routing is in progress.  The branch ```feature/501``` contains a stable and working implementation.  The design and conversation can be found on issue #501
