### ISSUE TITLE
What I'm loving in this CMS and what I'm wishing for.

### ISSUE THREAD

**Issue by datdevdave** [pencilblue/pencilblue#797]
Dedicated PencilBlue team,  thank you for creating this cms. I have been wishing for and looking for a MEAN stack cms and I was delighted to discover this project.  I’ve done my time with Joomla and WordPress and I’m ready for something better.

I don’t know if this is the right place for this but I’m sharing what I like about PencilBlue and what I hope it will become.  I represent that guy that everybody knows who does websites on the side for friends and small businesses.  I love that PencilBlue will be a viable solution for larger commercial needs with its horizontal scaling but I think that the casual web guy like me will still be a big part of your userbase.   It’s guys like me that purchase plugins and themes because we can’t code fast enough or well enough to get the functionality we need with reasonable effort.  With your open source model, I assume plugins and themes are how you will get reimbursed for all the hard work you are putting into this project.  I need this cms and I want you to make a lot of money for developing it.  So here is what a casual web guy like me wants in a cms:

__I love the light and simple content control panel.__  The casual web guy makes sites for low budget clients who want to manage the site themselves.  If I give my client the login for a Joomla backend, they go crosseyed and have an anxiety attack.  So I have had to make front end content editors for these clients.  What’s the point in using a cms if I have to provide my own content editing solution?  I really want to work with a cms where the backend is simple enough to turn over to a client.  PencilBlue wins here.  Some ideas for more win:
* Hide or separate settings and options that require a brain.  For example, you might reorganize the admin navigation such that the client would understand the “Content” area to belong to them and everything under “Content” would be dummieproof: 
 * Layout
   * Navigation
    * Pages
    * Custom Objects
 * Content
    * Articles
    * Media
    * Comments
* Maybe remove the “Topics” item in the navigation or hide it under settings.  I don’t see a reason to have a special page for this.  We should be able to create or delete topics on the article and media pages.  The tag editor on YouTube’s video manager is a good example of how this could look on the create article page.
* Reduce the number of steps required to add media to an article.   I know from experience, clients can never figure out how to include an image in their article.  If they have to first upload, then associate, then add to content, they will never get it and they will be calling me for help. Current technologies can support a dummieproof publishing workflow and your cms would stand out even more than it does if it showcased this.  As an example, how about supporting drag and drop media upload directly onto the WYSIWYG text area where the image would actually land where it dropped.  Then it could give them handle bars to resize the image and the cms would actually optimize the media, not just scale it.  (Clients always put 4mb images in their articles).  Little slick things like this are what makes us fall in love with good software.  It’s nice to have media packaged as an object but it shouldn’t be mandatory. 
* This is probably already planned but the Media manager needs a thumbnail view.  Also the media tab on the article creation tab needs to show thumbnail previews.
* Tooltips for everything.  There is a saying, “A mouseover tooltip is worth a thousand pages of documentation.”

__I love the modern user experience.__  Things like drag-n-drop topic association and dropdown lists that populate as you search are good examples of the kind of user experience we should enjoy on websites built in 2015.  PencilBlue wins here.  Ideas for more win:
* Angular Material (material.angularjs.org)  If you want to be the poster child of the modern cms, you need to have Google’s Material Design as a selling point.
* Defeat the dreaded Page refresh.  Maybe I don’t understand enough about how the PencilBlue engine works to properly articulate my thoughts here.  I feel like navigating from one page to another causes a page refresh.  I don’t understand why a cms built with AngularJS should ever reload the page.  I want my main site navigation to have the same seamless user experience as navigating the tabs on your create article page. I don’t want anything that has not changed to redraw. If you could pull this off you would make WordPress and Joomla look like relics of an extinct civilization. Could you comment on this?

__I love the Topics system.__  This is pure win, makes things so simple and flexible.  Having specific categories and subcategories for each type of object is such an outdated tedium.  Ideas for more win:
* Imitate the UI on YouTube's video tag editor everywhere Topics selectors are used.
* Abolish Sections.  As far I can tell, sections are redundant with topics.  We can create a section navigation link that will display all the articles that are associated with a certain section.  Why not just replace this with a navigation link that will display all the articles that are associated with a certain Topic?  

__Logical Organization.__  I like that PencilBlue doesn’t have as many redundant content object types as the rest of the cms world (e.g. Posts, Pages, Articles) but it seems like there is room for simplifying.  I like less types, more options. 
* Abolish Pages. Is there a need to have both “pages” and “articles”?  If pages and articles are both objects to store html, they seem redundant.  If Articles were the one and only place where you go to edit html content, it would just be easier for the client to find the thing they want to edit.  If I ever needed to distinguish an article from a page, I could just add the tag “page” in the topics or I could create a custom object.  This would be more consistent with PencilBlue’s modern twitter-style data organization.
* Change how the Navigation system works.
 * Remove type “Container”.  A blank “Link” type can serve this purpose. Any Nav item should be able to function as a parent item.
 * Remove type “Page”, “Article”, and “Section”. Replace with type “Layout”:  Allows user to select a layout from a list of layouts defined by the theme creator. Each layout presents it’s own set of options.  For each content area defined in a layout, user must select an article or content population method (e.g. recent articles, topic, etc).  A layout may include checkboxes to show/hide certain dom elements like sidebars, widgets, etc.  Ideally, layouts would not load new dom elements or trigger a page reload.  They would only trigger responsive behavior on the existing dom. It would use ngAnimate to change active css classes on the original page or other Angular functions to show/hide elements.  So for example, as we navigate from one page to the next, instead of a jerky page reload, we see a sidebar fade out and the center content area shows a stretch animation to fill the vacant space.  Theme creators want to give their customers a selection of page types like this so that whatever kind of site the customer is building, they can choose what they need and have a site up in minutes.  The more polished functional layouts a commercial theme offers, the more obvious value the customer will see in the product.  So if you provide a platform for defining page layouts, you will give the theme development community a huge head start. If you could provide a platform that could support this variety of layouts with smooth transition animations between each with no page refresh, it would be like nothing else the cms world has seen.

__I love the custom objects.__  This is really smart and it is going to make my life easier.

Great work PencilBlue!  I’m excited to watch this project progress and be involved in the PencilBlue community.

-Dave

**Comment by blakecallens** [comment]
Thanks for the feedback, @datdevdave. I'm going to try to hit on some key points that I hope will cover where we see the platform going, and where we see community involvement. Hopefully this will answer most, if not all of your questions.

When we first released PB last year, we intended it to be more of a WordPress competitor, but the market had different ideas. We've seen the majority of our adoption come strongly from the enterprise/business side of things, with the most active developers being those who want to dive, head first, into the code.

This is where we see the future of PB - as a *business class* CMS first and foremost. That means that any future core development will be primarily for this target demographic. For example, the plan is to *expand* the topics section to include fully object-oriented taxonomy (all Mitsubishis are Cars, and all Cars are Vehicles, etc).

That doesn't mean that it still can't suit a more casual use case, but we're not going to target that as *default* behavior. The functionality you're requesting is completely possible through plugins, because the entire admin section is a plugin itself. I would love to see developers like you build an alternate admin section plugin that meets your specific needs. We're always here to advise on the development of any PB plugin.

Ultimately, that's the goal of the platform, a "top down" approach, where an admittedly complicated, business class platform can be expanded or contracted at will. The more "point and click" type functionality will take time, though, because we need to build upon a community of developers, like yourself, who are willing to do some of the leg work to meet non-default use cases.

Thanks again, and we're always here to help with your specific needs.
