### ISSUE TITLE
Adding custom fields in Page and Article

### ISSUE THREAD

**Issue by khurrumqureshi** [pencilblue/pencilblue#798]
I want to add few custom fields in Page and Article for all. When user create any new page and article those fields will be there. I know there is already an issue created for this #682 but my question is if this is necessary that we have to create a theme to achieve this objective we can not do with a simple plugin which just added my custom fields in Page and Article. I would be greatful if you guide me in a right direction.

**Comment by blakecallens** [comment]
You don't have to create a theme for this. As long as your active theme doesn't create it's own article/page template, a basic plugin can override it.
