### ISSUE TITLE
Right To Left

### ISSUE THREAD

**Issue by amirsaber** [pencilblue/pencilblue#800]
Hello Sir,

Thanks for your great effort on PencilBlue and it got me really interested in your work. I am considering using PencilBlue as our CMS here in office, I just have a question about Right to Left languages.

There are more than 20 languages which are RTL (http://www.i18nguy.com/temp/rtl.html). Do you have an approach or solution to support it into your templates? how about admin dashboard? Thing about RTL languages is that it's not only needs localization, which I noticed that you have, it also requires some changes on the template, like in admin site, the menu(master view) should move to right and options(detail view) should move to left or in navigations is the same.

I am also willing to help you localize PencilBlue to the language that I know(Farsi/Persian), please let me know how do you want me to do it.

With Regards,
AmirSaber Sharifi

**Comment by blakecallens** [comment]
Thanks, @amirsaber. We're excited to have Farsi as a language.

You can override the [admin head template](https://github.com/pencilblue/pencilblue/blob/master/plugins/pencilblue/templates/admin/head.html#L19) in a plugin and point to an modified CSS file that moves everything to right to left.

**Comment by amirsaber** [comment]
Is there any need for something like WPML for PencilBlue? What is the best practice for one to have their templates adopted to language of the content or user?

**Comment by blakecallens** [comment]
Globalization of URLs is coming with 0.5.0 in December, and article/page
translation in 2016, so we'll soon have it covered in the core platform.

**Comment by amirsaber** [comment]
Oh, great, I can't wait to see new versions of PencilBlue, count on me if I can help in developing and coding.

**Comment by amirsaber** [comment]
I created the first version of portfolio RTL themplate: https://github.com/amirsaber/portfolio-rtl
