### ISSUE TITLE
TemplateService Loading

### ISSUE THREAD

**Issue by amirsaber** [pencilblue/pencilblue#812]
In creating a RTL version of portfolio template I noticed something that I believe it's a bug.
In home_page_setting.js file of portfolio template in line 105 

```
 self.ts.load('admin/settings/home_page_settings', function(err, result) {
        cb({content: result});
});
```

This line will load a wrong template file. If two templates have the same structure of template files, it will load the one that installed first not the one which it should be
consider this scenario:
portfolio
    |----controllers
        |----home_page_settings.js
            -->line 105 self.ts.load('admin/settings/home_page_settings', function(err, result) {.....
portfolio-rtl
    |----controllers
        |----home_page_settings.js
            -->line 105 self.ts.load('admin/settings/home_page_settings', function(err, result) {.....
the first one supposed to load portfolio/templates/admin/settings/home_page_settings and the second one supposed to load portfolio-rtl/templates/admin/settings/home_page_settings while both of them loads the first one. you can check it by adding a small change into the second one and then go to template setting, you will see the first one is loaded.
I am investigating on this, any help will be appreciated

**Comment by amirsaber** [comment]
my latest finding is this:
by setting self.ts.setTheme("Template uid"); before loading the html file will solve the problem. I believe this should be done and also for portolio, because having the same name is totally possible and don't want to have unpredicted file loading.

**Comment by brianhyder** [comment]
The behavior you experienced is a bit confusing at first but is as designed.  The template handler allows for developers to override the look and feel of a page without having to modify the controller behavior.  To accomplish this behavior the TemplateService has a prioritized list of places to find a suitable template along the same folder structure.

The priority is as follows:

* The hinted theme, ```self.ts.setTheme('portfolio-rtl');```
* The active theme 
* Iterates over the list of active plugins
* falls back to ```pencilblue``` theme

The desired behavior can most likely be accomplished by setting ```portfolio-rtl``` theme to active.  The behavior is also documented [here](https://github.com/pencilblue/pencilblue/wiki/Quickstart:-HTML-Templates#hierarchical-loading-of-templates).  If you are interested in the source code that provides this logic it is located [here](https://github.com/pencilblue/pencilblue/blob/master/include/service/entities/template_service.js#L267)

**Comment by amirsaber** [comment]
Thanks @brianhyder for your answer
