### ISSUE TITLE
[0.5.0] Saving article or page returns SUCCESS as message

### ISSUE THREAD

**Issue by blakecallens** [pencilblue/pencilblue#817]
1. Edit an existing article or page.
2. Click Save or Save Draft.
3. The resulting success message only says 'SUCCESS'
4. Expected to say '[Article/page name] was successfully edited'

I believe this is an aftereffect of moving to the new article service.

**Comment by markbaird** [comment]
Looks like I did that in #739 because the new API endpoint wasn't returning a user friendly message like the old service did. I can look at this bug if you want. Would it make sense to construct that message on the AngularJS side since the server isn't returning that string anymore?

**Comment by blakecallens** [comment]
Thanks, @markbaird. We appreciate the help. It's possible to construct it in AngularJS, but we'll need to make sure it's using the localization object (the global *loc* object in client side JS). The 'was edited' text is ```loc.admin.EDITED```, for example.

**Comment by markbaird** [comment]
@blakecallens sorry about that. I had intended to go back and fix that before submitting the pull request for #739 but I simply forgot. I believe this pull request should fix the issue.
