### ISSUE TITLE
Redis Connection

### ISSUE THREAD

**Issue by amirsaber** [pencilblue/pencilblue#819]
Since to connect to a real Redis server, username and password is required as well as host and port, I believe we need to use a Redis Url in config.js, same as what it's happening for mongo. and then parse the url in cache file. Any idea on that?

**Comment by markbaird** [comment]
PencilBlue is using the `node_redis` library and calling the version of `createClient()` that takes port, host and extra config options: `Redis.createClient(config.port, config.host, config);`. You can see this happening in cache.js.

So you can define extra options in the `cache` section of `config.js` that will be passed to the Redis library, such as the `auth_pass` option. This is noted in a comment in the cache section of `include/config.js`.

Note that Redis doesn't use usernames. For more details on the Redis library PencilBlue is using, you can view the documentation here https://github.com/NodeRedis/node_redis.

**Comment by amirsaber** [comment]
Thanks @markbaird for info. I will have a look into it.
