### ISSUE TITLE
Access another plugin with a plugin

### ISSUE THREAD

**Issue by amirsaber** [pencilblue/pencilblue#823]
What is the best way to override plugin routes? I am trying to make a plugin which when it's active, I want to load another page for Admin/login, but since pencilblue has that path it always load pencilblue plugin template file. Since it's just for login page, it's better not to define a theme and set it as active theme to make it higher priority in TemplateService. So is there anyway to manipulate another plugin and for example remove one of it routes so that the TemplateService while loading a page would not be able to load that route?

**Comment by markbaird** [comment]
Are you using PencilBlue as the active site theme? There is a special case where that theme, when active, can't be overridden. If you set the active site theme to something else you should be able to override the template file in your plugin or custom theme, unless the login page is some special case that I'm not aware of.

**Comment by amirsaber** [comment]
Ah, I see, so the plugin that I am trying to make, as an exercise for myself with pencilblue, is google recaptcha, What I want to do is that when a user set that plugin to active and enabled it in it's settings, the admin/login page will be loaded with google-recaptcha. how do you think might be the best case to achieve this. I am trying to do the plug-in as generic as possible so anyone can use in their pencilblue, so it will cover those who want to have pencilblue set as their active theme too.

**Comment by markbaird** [comment]
I don't think that's possible right now if PencilBlue is the active theme. I ran into a similar issue with my Sendy plugin. It just doesn't work if PencilBlue is the active theme. The active theme's implementation takes priority, so if PencilBlue is active it provides the implementation that will be used.

**Comment by amirsaber** [comment]
```
paths.push(TemplateService.getDefaultPath(relativePath));
```

On template_service.js file line 287 pencilblue plugin path will be pushed into paths arrays as the default path, to me, as the last fallback to check on. and on the life 277 activetheme will be pushed as one of the paths. I think we can check if the activeTheme is pencilblue to not to push it on top of path array. This will solve this problem for now. It might be also a good idea to come up with a route service and an admin panel to manage handling plugin routes in case of conflict.

**Comment by markbaird** [comment]
I really like the idea of an admin page to handle route conflicts.

**Comment by amirsaber** [comment]
changing line 277 of template_service to : 
```
            if (activeTheme !== null && activeTheme !== 'pencilblue') {
```
solved my issue. But we need to handle route conflicts and prioritize them. Let's see what others think about this.

**Comment by amirsaber** [comment]
I've managed to do it, by having in mind that templates and routes are different, what I did was to use RequestHandler to unregisterRoute while starting up my plugin, something like this:
```
    GoogleCaptchaPlugin.onStartup = function(cb) {
        pb.RequestHandler.unregisterRoute("/admin/login", "pencilblue");
        cb(null, true);
    };
```
Then in my controller, inside render function, using self.ts.setTheme('google-recaptcha'); I managed to load the file that I need.

**Comment by amirsaber** [comment]
I just have another question, do we have any function in plugin to get triggered when plugin setting changes? I know we have onStartup and onInstall and those, but do we have onConfigure or onSettingChange or something like that?

**Comment by brianhyder** [comment]
Currently, we do not have that capability.  Are you looking to perform a single operation or an operation on all servers?
