### ISSUE TITLE
Google reCaptcha Plugin

### ISSUE THREAD

**Issue by amirsaber** [pencilblue/pencilblue#825]
Here I created a google reCaptcha plugin for Pencilblue, any contribution will be appreciated.
https://github.com/amirsaber/google-recaptcha
The only thing that I couldn't manage to do is to register a call back into plugin change setting to detect change of settings into plugin and register or unregister required routes for the plugin. So for now if you turn off or on the required login for admin or user you should restart the Pencilblue to take effect. Please give me your suggestions. I think we might be able to add it to Wiki in Wordpress required plugins as a captcha option.

**Comment by blakecallens** [comment]
You could remove the routes from the google-recaptcha.js file and have your plugin override the login routes no matter what. Then you can have your controllers inherit from the original controllers and go to their functions, if reCaptcha is turned off, with a ```super_.prototype``` call. [Here's an example of that in action.](https://github.com/pencilblue/pencilblue/blob/master/plugins/pencilblue/controllers/page.js#L54)
