### ISSUE TITLE
[enhancement] Add the functionality to create APIs right from the admin section

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#826]
Since PencilBlue is data driven platform, I was wondering if we could add the functionality for users to create APIs right from the admin section. WRITE, GET, UPDATE and DELETE options will be possible on these APIs. APIs could be secured and APIs, created could operate on existing data/objects or new once could be created automatically for it.

**Comment by JahlomP** [comment]
This can help users expose their data to the public or reduce the amount of work they will do when implementing features. They only have to write client side code and leverage the APIs.

**Comment by amirsaber** [comment]
Good idea, having that combined with custom objects, one can create most sophisticated web apps such as CRMs and ERPs with that.

**Comment by blakecallens** [comment]
This should be a plugin, IMO. There are too many security concerns with the auto-generation of APIs that expose custom data to make it good for the core of the platform.
