### ISSUE TITLE
Enhancement - Excel copy & paste

### ISSUE THREAD

**Issue by adrianeguez** [pencilblue/pencilblue#830]
Hello, I have copy & pasted some contend from excel 2013 to an article, pencilblue override the aligment, bold and table style.

### Excel format
![image](https://cloud.githubusercontent.com/assets/5687655/11106127/a5ed6d34-88a1-11e5-9291-5c81cde60d4c.png)
### Pencilblue Format

![image](https://cloud.githubusercontent.com/assets/5687655/11106150/cca422ce-88a1-11e5-94d9-25f2b65b0eeb.png)

### Code

` 
<table border="0" cellpadding="0" cellspacing="0" width="855" style="width: 641pt;">

    <colgroup>

        <col width="128" style="mso-width-source:userset;mso-width-alt:4551;width:96pt">

            <col width="92" style="mso-width-source:userset;mso-width-alt:3271;width:69pt">
        
                <col width="125" style="mso-width-source:userset;mso-width-alt:4437;width:94pt">
        
                    <col width="170" style="mso-width-source:userset;mso-width-alt:6058;width:128pt">
        
                        <col width="272" style="mso-width-source:userset;mso-width-alt:9671;width:204pt">
        
                            <col width="34" span="2" style="mso-width-source:userset;mso-width-alt:1194; width:25pt">
        
    </colgroup>
    
    <tbody>
        
        <tr height="53" style="mso-height-source:userset;height:39.6pt">
            
            <td rowspan="3" height="119" class="xl77" width="128" style="border-bottom:.5pt hairline black;  height:89.4pt;width:96pt">9</td>
            
            <td rowspan="3" class="xl68" width="92" style="width:69pt">Ético y Político</td>
            
            <td class="xl68" width="125" style="border-left:none;width:94pt">Sistema de gobierno
            </td>
            
            <td colspan="2" class="xl69" width="442" style="border-right:1.0pt solid black; border-left:none;width:332pt">El Poder Ejecutivo, el Poder Legislativo, el Poder Judicial, el
                <br> Poder Electoral y el poder de participación ciudadana. Estado plurinacional,unitario y descentralizado. Desarrollo endógeno con vinculación estratégica al sistema mundo</td>
            
            <td class="xl71" width="34" style="border-left:none;width:25pt">X</td>
            
            <td class="xl72" width="34" style="border-left:none;width:25pt">&nbsp;</td>
            
        </tr>
        
        <tr height="32" style="height:24.0pt">
            
            <td height="32" class="xl68" width="125" style="height:24.0pt;border-top:none;  border-left:none;width:94pt">Partidocracia y grupos de poder</td
                
            <td colspan="2" class="xl69" width="442" style="border-right:1.0pt solid black;  border-left:none;width:332pt">Desconocido.</td>
            
            <td class="xl71" style="border-top:none;border-left:none">&nbsp;</td>
            
            <td class="xl72" style="border-top:none;border-left:none">X</td>
            
        </tr>
        
        <tr height="34" style="mso-height-source:userset;height:25.8pt">
            
            <td height="34" class="xl68" width="125" style="height:25.8pt;border-top:none;  border-left:none;width:94pt">Ético</td>
            
            <td colspan="2" class="xl69" width="442" style="border-right:1.0pt solid black;  border-left:none;width:332pt">Ecuador en el puesto 102 de 175 países evaluados a nivel mundial, Nivel de transparencia 53/100</td>
            
            <td class="xl71" style="border-top:none;border-left:none">&nbsp;</td>
            
            <td class="xl72" style="border-top:none;border-left:none">X</td>
            
        </tr>
        
        <tr height="19" style="height:14.4pt">
            
            <td rowspan="2" height="52" class="xl77" style="border-bottom:1.0pt solid black; height:39.0pt;border-top:none">10</td>
            
            <td rowspan="2" class="xl68" width="92" style="border-bottom:1.0pt solid black;  border-top:none;width:69pt">Proveedores</td>
            
            <td class="xl68" width="125" style="border-top:none;border-left:none;width:94pt">Calificación y selección</td>
            
            <td colspan="2" class="xl69" width="442" style="border-right:1.0pt solid black;border-left:none;width:332pt">Proveedores de muy alta calidad, Pluralsight, Codeschool, Lynda, Udemy, Egghead.io, etc</td>
            
            <td class="xl71" style="border-top:none;border-left:none">X</td>
            
            <td class="xl72" style="border-top:none;border-left:none">&nbsp;</td>
            
        </tr>
        
        <tr height="33" style="height:24.6pt">
            
            <td height="33" class="xl80" width="125" style="height:24.6pt;border-top:none; border-left:none;width:94pt">Organización de los proveedores</td>
            
            <td colspan="2" class="xl81" width="442" style="border-right:1.0pt solid black; border-left:none;width:332pt">Online todos, actualizados, faciles de acceder, gran soporte</td>
            
            <td class="xl73" style="border-top:none;border-left:none">X</td>
            
            <td class="xl74" style="border-top:none;border-left:none">&nbsp;</td>
            
        </tr>
        
    </tbody>
    
</table>`

### Enhancement

It will be very nice to keep the format, but also apply classes to be a responsive table.

**Comment by blakecallens** [comment]
contenteditable divs, which most wysiwygs are built on, don't support this type of copy/pasting. Html tables are different from Excel tables.
