### ISSUE TITLE
Responsive Problems

### ISSUE THREAD

**Issue by adrianeguez** [pencilblue/pencilblue#832]
### Issue
I am ussing as default the portfolio plugin, but when my articles are open, this happens: 
![image](https://cloud.githubusercontent.com/assets/5687655/11106811/2f1ec680-88a6-11e5-995a-d14c255febfb.png)
### <head> code:

`<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no">`

### All Head html tags:

`<meta name="description" content="Investigación interna y externa de Celula Fis para entender dónde se desenvuelve la organización.">`

`<meta property="og:locale" content="en-US">`

`<meta property="og:title" content="Diagnóstico estratégico">`

`<meta property="og:description" content="Investigación interna y externa de Celula Fis para entender dónde se desenvuelve la organización.">`

`<meta property="og:url" content="https://pencilblue-adrianeguez.c9.io/section/DiagnosticoEstrategico">`

`<meta property="og:image" content="">`

`<meta property="og:site_name" content="Celula Fis EPN">`

`<meta property="og:type" content="article">`

`<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no">`

`<link rel="shortcut icon" href="/favicon.ico">`

`<link rel="stylesheet" type="text/css" href="/bower_components/bootstrap/dist/css/bootstrap.min.css">`

`<link rel="stylesheet" type="text/css" href="/bower_components/fontawesome/css/font-awesome.min.css">`

`<link rel="stylesheet" type="text/css" href="/public/portfolio/css/portfolio_theme.css">`

        `<link rel="shortcut icon" href="/favicon.ico">`

        `<link rel="stylesheet" type="text/css" href="/bower_components/bootstrap/dist/css/bootstrap.min.css">`
       ` <link rel="stylesheet" type="text/css" href="/bower_components/fontawesome/css/font-awesome.min.css">`
       ` <link rel="stylesheet" type="text/css" href="/public/portfolio/css/portfolio_theme.css">`

        `<script type="text/javascript" src="/bower_components/jquery/dist/jquery.min.js"></script>`
        `<script type="text/javascript" src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>`
       ` <script type="text/javascript" src="/bower_components/angular/angular.min.js"></script>`
       ` <script type="text/javascript" src="/bower_components/angular-route/angular-route.min.js"></script>`
        `<script type="text/javascript" src="/bower_components/angular-sanitize/angular-sanitize.min.js"></script>`
      `  <script type="text/javascript" src="/js/media.js"></script>`
        `<script type="text/javascript" src="/api/localization/script"></script>`

Sorry for the formating.

**Comment by blakecallens** [comment]
Based on your the other issue you opened, I'm guessing this is due to the content you're pasting into your articles.
