### ISSUE TITLE
urlSafe directive error

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#842]
urlSafe directive throws TypeErrorr when article url or page url is filled and then emptied

**Comment by blakecallens** [comment]
@JahlomP, since your working on auto-generated URLs, can you add this to that pull request?

**Comment by JahlomP** [comment]
K

On Fri, Nov 13, 2015 at 8:05 PM Blake Callens <notifications@github.com>
wrote:

> @JahlomP <https://github.com/JahlomP>, since your working on
> auto-generated URLs, can you add this to that pull request?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/842#issuecomment-156543199>
> .
>
-- 
Best Rregards,
Precious Jahlom Agboado,
www.twitter.com/jahlomp
+233 54 0915 108.
