### ISSUE TITLE
Events and server restart

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#843]
There are certain actions that require server restart like when site libraries are updated and running on a server cluster.

Instead of manually restarting server, why not have those actions throw events, when they happen then automatic initialization is done to get changes take effects and even enable the creation of events and event handlers in plugins for certain actions to be taken when certain events occur. 

@amirsaber, is this not what you were proposing?

I hope I make since.

**Comment by blakecallens** [comment]
I believe we can start doing this, now that we have the BaseObjectService. We'll be integrating these types of changes after 0.5.0 is released.

**Comment by JahlomP** [comment]
OK

On Fri, Nov 13, 2015 at 8:06 PM Blake Callens <notifications@github.com>
wrote:

> I believe we can start doing this, now that we have the BaseObjectService.
> We'll be integrating these types of changes after 0.5.0 is released.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/843#issuecomment-156543390>
> .
>
-- 
Best Rregards,
Precious Jahlom Agboado,
www.twitter.com/jahlomp
+233 54 0915 108.

**Comment by brianhyder** [comment]
The types of changes that you are asking for cannot be done through the BaseObjectService alone.  It would require a cluster job to run to interact with each running instance in the cluster to refresh data or perform some other action.  We'd be happy to have someone work on this but I doubt this will be a high priority for 2016.
