### ISSUE TITLE
Vagrant + Ansible

### ISSUE THREAD

**Issue by RopoMen** [pencilblue/pencilblue#845]
Hi,

Have you thought about adding any kind of automation to setting up environment for development and / or production?

Something like these 
https://github.com/roots/trellis
https://github.com/776166/ansible-django-cms

that automation stuff can be in its own repository, but it would be good if environment management would be simple :)

**Comment by blakecallens** [comment]
We have an [automatic deployment to OpenShift](https://github.com/pencilblue/pencilblue-openshift), and since Red Hat just bought Ansible, I wouldn't be surprised if that'll come as part of the package soon.
