### ISSUE TITLE
[0.5.0] Visibility, accessibility and easy switch among subdomains/sites

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#848]
Lets say I have built a platform for users/organisations where i will like them to signup and on successful signup a sub domain be allocated to them. In this case the should not be able to access the admin both the global admin and the admin of the other clients. 

If we could have some settings in the global admin side to prevent access to other sub domain admin and remove links in the admin used to switch between sites, that will be great.

Hop I make sense.

**Comment by cchatham** [comment]
If I am reading this correctly, pencilblue 0.5.0 supports this for users who are editors, writers, and readers. These three types are assigned to a site and cannot switch between sites in the admin console.

Let me know if I misread your request.

**Comment by blakecallens** [comment]
I chatted with @JahlomP about this on gitter. That *is* what he meant with this. Thanks for the clarification, @cchatham. I'll close the request.
