### ISSUE TITLE
[0.5.0] Extensibility and feature addition by plugin first

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#851]
If the whole system including base services and controllers can be extended by plugins, this could enable feature addition to be done by developing a plugin for it first. After used by the community and made solid with updates and bug fixes, it could then be added directly to pencilblue core.

**Comment by JahlomP** [comment]
This will also ensure developers have a stable core to work with until major releases are made.

**Comment by brianhyder** [comment]
This is why we operate using Git Flow. All new features are added to the
next release branch. Hot fixes are added back to master.

**Comment by JahlomP** [comment]
Ok

On Sat, Nov 14, 2015 at 1:16 PM Brian <notifications@github.com> wrote:

> This is why we operate using Git Flow. All new features are added to the
> next release branch. Hot fixes are added back to master.
> On Nov 14, 2015 6:37 AM, "Precious Jahlom Agboado" <
> notifications@github.com>
> wrote:
>
> > This will also ensure developers have a stable core to work with until
> > major releases are made.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/pencilblue/pencilblue/issues/851#issuecomment-156689706
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/851#issuecomment-156694741>
> .
>
-- 
Best Rregards,
Precious Jahlom Agboado,
www.twitter.com/jahlomp
+233 54 0915 108.
