### ISSUE TITLE
Mobile View: Pencilblue.org not displayed properly

### ISSUE THREAD

**Issue by n1ru4l** [pencilblue/pencilblue#855]
http://imagr.eu/up/r7xdJ_image.png

Visited on iPhone 5 iOS 9 Safari

**Comment by brianhyder** [comment]
Thank you for the heads up. We'll look into it.

**Comment by brianhyder** [comment]
@blakecallens did we resolve this after our conversation this morning?

**Comment by blakecallens** [comment]
Perhaps. I'm unable to reproduce so far.

**Comment by brianhyder** [comment]
@n1ru4l Has the issue been resolved?

**Comment by n1ru4l** [comment]
Nope, it still looks the same

**Comment by brianhyder** [comment]
Issue confirmed on iPhone 5S.  It looks OK in landscape but is offset to the left in portrait mode.

**Comment by blakecallens** [comment]
Ok, I'll take a look

**Comment by blakecallens** [comment]
I've been unable to reproduce on an iPhone on my end. With the new site launching with 0.5.0, I'm going to let this slide. Either way, thanks for the heads up @n1ru4l.
