### ISSUE TITLE
pid file && pbctrl stop && process-naming

### ISSUE THREAD

**Issue by itsatony** [pencilblue/pencilblue#858]
it'd really help to be able to control pb better from the outside.
three small things that would help a lot would be
- [ ] write a pid file
- [ ] name the process
- [ ] add a "pbctrl stop" command

**Comment by markbaird** [comment]
I would suggest using a different NodeJS management service such as [forever](https://github.com/foreverjs/forever) to start/stop PencilBlue if you need those features.
