### ISSUE TITLE
Wordpress import plugin wp_import requires xml2js

### ISSUE THREAD

**Issue by vitaliec** [pencilblue/pencilblue#870]
Perhaps a notice about this dependency should be added to the plugin description block.

**Comment by blakecallens** [comment]
The proper installation of the plugin retrieves than npm module. Did it not install the module for you?

**Comment by vitaliec** [comment]
Thanks for your reply. It did not install it automatically.
Maybe something was wrong on my windows machine, I will try again once 0.5.0 will be released.

**Comment by blakecallens** [comment]
Make sure that npm has write permissions in your install folder. Thats
probably it.
