### ISSUE TITLE
Feature request: shortcodes support

### ISSUE THREAD

**Issue by vitaliec** [pencilblue/pencilblue#871]
Hi,
There is a whole group of plugins in wordpress which replace article content inside so-called "shortcodes" with a content post-processed by plugin, which opens very interesting and useful possibilities.
Is there any similar feature in pencilblue or are you planning to add it anytime? 
Maybe it is a good idea to add this also for pages, so theme developers can create dedicated places in their html pages which will be populated by plugins (but this is already comes closer to "widget areas").
Thank you.

**Comment by blakecallens** [comment]
This is easily supported through the template service or a specially built plugin. We'll leave it to the community to build a plugin.
