### ISSUE TITLE
Add class to MediaService rendering options

### ISSUE THREAD

**Issue by Chris-Satchell** [pencilblue/pencilblue#872]
Removed issue that wasn´t one

**Comment by Chris-Satchell** [comment]
Current options are `attrs`, `style` and `view`. Would it be possible to add `class`?

**Comment by brianhyder** [comment]
Yes, it is.  As mentioned in the code level docs [here](http://pencilblue.github.io/classes/MediaService.html#method_renderById) the function supports passing in an object ```options.attr``` that contains the HTML attributes for the element(s) to be rendered.

Example:
```
var id = 'abc123';
var options = {
  view: 'post',
  style: 'max-width: 500px;',
  attrs: {
    id: 'media_item_' + id,
    class: 'my-custom-media-class'
  }
};
mediaService.renderById(
```

**Comment by Chris-Satchell** [comment]
Uh, it is pretty obvious on rereading that, thanks for the quick response.

**Comment by brianhyder** [comment]
No problem, happy to help.
