### ISSUE TITLE
Article Page Stuck

### ISSUE THREAD

**Issue by misbahneo** [pencilblue/pencilblue#876]
Hi there 

Was just trying to upload an article to my site, 

and it seems to have frozen my back end 

Everytime i try and navigate to the page now i See this

![screen shot 2015-11-24 at 14 58 31](https://cloud.githubusercontent.com/assets/4047558/11370482/df4883ba-92bb-11e5-8a52-063d0053ae22.png)
 

![screen shot 2015-11-24 at 14 37 54](https://cloud.githubusercontent.com/assets/4047558/11369922/0d21a710-92b9-11e5-86fe-d90d039070d2.png)
![screen shot 2015-11-24 at 14 33 59](https://cloud.githubusercontent.com/assets/4047558/11369923/0d22ef62-92b9-11e5-9b3a-2c4a375647cf.png)

can you reccomend a way to fix this?

**Comment by misbahneo** [comment]
I managed to navigate into the page where I was editing the article and it looks like this:

![screen shot 2015-11-24 at 14 54 19](https://cloud.githubusercontent.com/assets/4047558/11370367/61811c94-92bb-11e5-8d12-bf5e55668d44.png)
![screen shot 2015-11-24 at 14 54 06](https://cloud.githubusercontent.com/assets/4047558/11370366/61805cfa-92bb-11e5-8a04-7e48ce5cf956.png)

**Comment by blakecallens** [comment]
We'll need steps to reproduce. It looks like some illegal characters might have gotten injected into the article.

**Comment by misbahneo** [comment]
I tried to embed an instagram image into the article at which point i ended up here

**Comment by blakecallens** [comment]
Can you post the snippet of HTML that you used? Those types of illegal characters are supposed to be sanitized, so that might be a bug.

Use the media screen to add an Instagram image in the system, then use the media tab in the article page to embed it.

**Comment by misbahneo** [comment]
Yeah after i initally embeded it i realised that it was possible to upload it to the media library at which point i'd fucked it, either it's this one 

<blockquote class="instagram-media" data-instgrm-version="6" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50.0% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div><p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;"><a href="https://www.instagram.com/p/-Uj5Ogtm3m/" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_blank">A video posted by Tom Guerriero-Davies (@tgdavies93)</a> on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2015-11-20T21:11:55+00:00">Nov 20, 2015 at 1:11pm PST</time></p></div></blockquote>
<script async defer src="//platform.instagram.com/en_US/embeds.js"></script>

or 

<blockquote class="instagram-media" data-instgrm-version="6" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50.0% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div><p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;"><a href="https://www.instagram.com/p/-Uof8Jtm-5/" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_blank">A video posted by Tom Guerriero-Davies (@tgdavies93)</a> on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2015-11-20T21:52:09+00:00">Nov 20, 2015 at 1:52pm PST</time></p></div></blockquote>
<script async defer src="//platform.instagram.com/en_US/embeds.js"></script>

**Comment by blakecallens** [comment]
Try deleting the article from the manage articles screen. If you can't do that, you can either manually remove the article in Mongo or send a DELETE request via REST.

**Comment by blakecallens** [comment]
@misbahneo what version are you running?

**Comment by misbahneo** [comment]
0.4 , cant access the article manage page at all 

will try and acess mongo now

**Comment by brianhyder** [comment]
This is a known issue with the browsers.  If a script tag is included in JSON withing a script block it is executed on the browser and causes everything to get screwed up from an HTML perspective.  This is why we attempt to strip out script content when articles are posted back to the server.  

When the forms are modified to retrieve content from an API call vs. loading from a JS object in a script this will be a non-issue.

In the meantime, I will verify tonight that script content is getting stripped out (only in 0.5.0).  The best way to correct the issue is to delete the document from Mongo.

**Comment by brianhyder** [comment]
@misbahneo This issue has been corrected in 0.5.0.
