### ISSUE TITLE
Inability to modify table headers for custom object types

### ISSUE THREAD

**Issue by HadenHiles** [pencilblue/pencilblue#877]
It would be nice if there was a tab when creating the custom object, or an init structure to use when initializing a plugin that allows the developer to add/remove/modify the table headers used to manage each custom object type.

Currently the table headers are hard coded into the `pencilblue/templates/angular/admin/content/objects/manage_objects.html` angular initialization template as an array of objects with the fields "name", "description", and "last_modified".

I would much prefer to use for example a "display_name" field instead of the url friendly "name" field for the ease of use my clients need. In some use cases I don't even have a description so the ability to use whatever fields you want would be very useful.

I think I made my point :)

**Comment by blakecallens** [comment]
I'm torn on whether this should be default functionality or part of an "enhanced custom objects" plugin. I'm concerned that adding this kind of control to the default interface might confuse some users.

**Comment by HadenHiles** [comment]
That is understandable, perhaps instead of using a plugin just have a global boolean site setting for "Complex Custom Objects" On/Off?

Could you accomplish the same result with a plugin?.. Yes but when I beg the question of what the plugin is for, the organizational structure that seems to make most sense to me is to have it built in to the base pencilblue installation.

This enhancement isn't a complete game changer for me right now, but if it is in the future for one of my clients then I will be sure to share my solution :grinning:
