### ISSUE TITLE
nginx proxy issue + fix (workaround)

### ISSUE THREAD

**Issue by keithics** [pencilblue/pencilblue#878]
I see a lot of issues with Nginx unsolved  . It works on the development side but fails on the production if you are using proxy.

The problem:
siteRoot isn't always correct if you are using proxy like nginx 

config.js

        module.exports = {
        "siteName": "my blog",
        "siteRoot": "http://localhost:8080",
        "sitePort": 8080,

nginx.conf

        server {
            listen 80;

            server_name mydomain.com;

            location / {
                proxy_pass http://localhost:8080;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
            }
        }

In the setup page, images and forms are pointing to the SITEROOT which is the localhost:8080 instead of mydomain.com

setup.html in the template

        <div id="login_logo">
                                <img src="^site_root^/img/pb_logo.png" style="max-width: 100%"></img>
                            </div>
                            ^error_success^
                            <div class="panel panel-default">
                                <div class="panel-heading">^loc_REGISTER_ADMIN^</div>
                                <div class="panel-body">
                                    <form id="setup_form" method="post" action="^site_root^/actions/setup">

The main culprit is the file /include/service/entities/template_service.js : 147

        var GLOBAL_CALLBACKS = {
            site_root: pb.config.siteRoot,//this one!
            site_name: pb.config.siteName,
            site_logo: function(flag, callback) {
                pb.settings.get('site_logo', function(err, logo) {
                    callback(null, logo ? logo : '/img/pb_logo.png');
                });
            },

manually editing site_root from pb.config.siteRoot to mydomain.com fixes the problem. But it would be better to have another entry in the config to fix this workaround.

**Comment by blakecallens** [comment]
You should be able to place any nginx environment variables directly in the config.js file with the $ENV values.

**Comment by markbaird** [comment]
Won't this work by just setting site_root in config.js to be your domain? So in your config.js:
```
"siteRoot": "http://mydomain.com",
"sitePort": 8080
```

That should cause the server to listen for requests on port `8080`, and build URLs with a root of `http://mydomain.com` unless I'm missing something.

@keithics did you try this configuration and encounter issues handling requests from Nginx?

**Comment by keithics** [comment]
@markbaird i removed the installation and redo everything from scratch and now it's working fine :heart_eyes: .
though, I always have this npm module not installed error everytime on ubuntu 14.0 but should be an easy fix. Though i don't have this kind of error on OSX.

    Error: Cannot find module 'npm-registry-client'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:289:25)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (/home/azureuser/blog/node_modules/npm/lib/cache/caching-client.js:9:22)
        at Module._compile (module.js:425:26)
        at Object.Module._extensions..js (module.js:432:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:313:12)
        at Module.require (module.js:366:17)

**Comment by net1313** [comment]
Hello everyone,
Tell me please, how can I set a custom cookie, or Cache-control header when a user is logged in?
It allows to manage the caching of pages via reverse proxy like Nginx or Varnish.
For example, the page is cached only for visitors and not for users, when "Cache-Control: no-cache" or a specific cookie is present.

Thanks in advance.

**Comment by qualitycode** [comment]
What should I set siteIP to in config.js?  Also, how do I set this up with nginx using https?

Also, I tried to get multisite working with https and nginx, and could not.  With no documentation that describes values such as siteIP, I cannot use pencilBlue.

**Comment by brianhyder** [comment]
The site IP can be set to "0.0.0.0" (accept incoming connections on any of the IP address that the server is bound to) or a specific IP (accept incoming connections only from those that request the IP specified).  You can learn more about how PB handles SSL by looking our system level config.js file.  It provides inline documentation on each property:
https://github.com/pencilblue/pencilblue/blob/master/include/config.js#L323
