### ISSUE TITLE
WYSIWYG editor doesn't take changes

### ISSUE THREAD

**Issue by stefanganchev** [pencilblue/pencilblue#881]
Hi. First of thanks for this awesome open source cms. I have an issue with the WYSIWYG editor that I added on a custom object. When I type in "text" mode, the text does not save. Only when I type in "code" mode, the text is saved. I had an older version of pencilblue that didn't have that issue.
Thanks!

**Comment by brianhyder** [comment]
Hey, would you mind including what version/commit you are using?

**Comment by stefanganchev** [comment]
The latest release 0.4.1

**Comment by brianhyder** [comment]
We are getting close the release of 0.5.0.  We've made a lot of improvements along the way.  Can you try and replicate the issue on the 0.5.0 branch?  If it exists there can you provide the following information:

* Relevant output from the console (server side and client side)
* The response from the server when the save button is clicked
* Does the screen indicate a successful or failed save?
