### ISSUE TITLE
[0.5.0] Sites with non-80 port crashes

### ISSUE THREAD

**Issue by brianhyder** [pencilblue/pencilblue#890]
With multi-site enabled setup any number of sites through the admin section.

Map your hosts file

```
global.localhost localhost
test1.localhost localhost
test2.localhost localhost
test3.localhost localhost
```

Set your site port to:
```
8080
```

Navigate in the browser to:
``` 
http://test1.localhost:8080 
```

The page does not load and the following error is displayed in the console:

```
2015-12-08T01:26:13.810Z - error: [M]  Error: The host (test1.localhost:8080) has not been registered with a site. In single site mode, you must use your site root (http://localhost:8080).
    at RequestHandlerModule.RequestHandler.onSessionRetrieved (/Users/code/pencilblue/include/http/request_handler.js:700:31)
    at /Users/code/pencilblue/include/http/request_handler.js:498:18
    at /Users/code/pencilblue/include/session/session.js:137:17
    at /Users/code/pencilblue/include/dao/dao.js:143:12
    at /Users/code/pencilblue/include/dao/dao.js:272:17
    at handleCallback (/Users/code/pencilblue/node_modules/mongodb/lib/utils.js:95:12)
    at /Users/code/pencilblue/node_modules/mongodb/lib/cursor.js:590:16
    at handleCallback (/Users/code/pencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:234:5)
    at setCursorDeadAndNotified (/Users/code/pencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:424:3)
```

The ```RequestHandler.sites``` property contains all of the active sites.  However, the keys in the object are the hostnames where the ```hostname``` property when the RequestHandler instance is created is the hostname and the port.

**Comment by brianhyder** [comment]
@cchatham @btidwell I'm trying to figure out what the correct and expected behavior is for the map of sites in request handler and the hostname instance property.  Any help tracking this down would be amazingly helpful.

**Comment by btidwell** [comment]
@brianhyder the hostname of the site instance should have the port number if it's non 80/443.  So for your test1 site, you should have "test1.localhost:8080" set in the hostname field as that is what is passed via the host header.

**Comment by brianhyder** [comment]
@btidwell Awesome, thank you for the additional info.  That part is correct.  I guess something changed in the site_service when ```RequestHandler.loadSite``` is called causing the port to not be appended to the end.  Is the expectation that when setting up the site I include the hostname and port?

When I created the site I used: ```test1.localhost``` instead of ```test1.localhost:8080``` in the text box.

**Comment by btidwell** [comment]
@brianhyder That was the way we intended it when building it.  It is also what powers the cross site auth in the admin console.  The auth request can be sent to the hostname of the site, port would be required in this case, unless you append the port somehow like you are thinking for the request handler loadSite function.

**Comment by brianhyder** [comment]
Sounds good.  We'll leave as is and address as concerns come up.
