### ISSUE TITLE
Duplicate declaration of require('process') in include/config.js

### ISSUE THREAD

**Issue by radiovisual** [pencilblue/pencilblue#897]
In the file `include/config.js`, you have two identical declarations for:

`var process = require('process');`

First declaration is on [line #22](https://github.com/pencilblue/pencilblue/blob/master/include/config.js#L22), and the second declaration is on [line #24](https://github.com/pencilblue/pencilblue/blob/master/include/config.js#L24).

**Comment by brianhyder** [comment]
@radiovisual Thanks for the report.  You are correct.  It was added twice.  We have already addressed it in our upcoming release, 0.5.0.
