### ISSUE TITLE
[0.5.0] Server Initialization Should be Abstracted and Extendable

### ISSUE THREAD

**Issue by brianhyder** [pencilblue/pencilblue#901]
The current server creation and initialization is not extendable or flexible.  It should be abstracted out into its own prototype that can be overriden in the configuration.

**Comment by blakecallens** [comment]
Blocker?

**Comment by brianhyder** [comment]
No, it is not.  Just making things simpler for those that want to extend our basic setup.  No breaking changes and implementation is already done.  About to go into PR.
