### ISSUE TITLE
Rangy Library URL not protocol generic in "include/libraries.js"

### ISSUE THREAD

**Issue by thcase** [pencilblue/pencilblue#903]
I was working on a new site today and in testing found that there was an issue with the Rangy Library URL.  It has http:// instead of just "//" in the beginning like the others.  This causes angular errors when editing  page in secure mode (e.g., when require https for /admin files).  I revised the site library to use the "//" instead and the error went away.  Recommend update to "include/libraries.js" to remove the http: in front of the url.

**Comment by markbairlift** [comment]
What version of PB are you using? This is fixed in 0.5.0 
https://github.com/pencilblue/pencilblue/issues/869

**Comment by thcase** [comment]
This is on 0.4.1.

**Comment by markbaird** [comment]
Yeah it's already known. There's a workaround for 0.4.1 and a fix in 0.5.0. https://github.com/pencilblue/pencilblue/issues/869

**Comment by blakecallens** [comment]
Btw, I suggest using bower if possible. It's almost always the better performing option.

**Comment by thcase** [comment]
@blakecallens I don't know if I fully agree with local vs CDN for external libraries.  The reason for "production" sites to use CDN path is two-fold.  One, for common libraries (such as jQuery), other sites will also use the same CDN and thus the browser should already have cached the resource.  This saves download time and bandwidth.  The second reason isn't necessarily performance, but cost and maintenance.  If each site stores a copy of the resource, then this takes up disk space, which in cloud environment does add up, and also requires local maintenance (installation).  I will be interested on this second point, your multisite approach coming in 0.5.0.  Ideally, plugins and external resources should be a common external library to the web site/application, that gets included.  For example, for our internal sites, we often include via IIS virtual directories, common JS libraries (or in case of external sites we point to the CDN).  This also allows us to use single version of a library (such as jQuery) instead of relying on version when the application was developed (and loaded in application child path).  The same can be done with Apache and NGNIX.  You have this case covered in PencilBlue via the External Libraries feature, although it would be nice to override the defaults automatically for new sites, instead of a manual process (e.g., place in config file?).  Multi-site has two meanings when one talks corporate world.  It can mean different host names, but can also mean different sub-paths.  For example, in SharePoint, one can have host-named based site collections, or path based site collections.  Often we (corporate world) want a single host name that we can set as browser default and then run all applications (and sites) as paths off that common hostname with shared UI.

**Comment by blakecallens** [comment]
@thcase in cases where you would want to get that granular and performant, I wouldn't use the Libraries feature at all, but instead concatenate and minify your vendor libraries. The Libraries feature was designed as a "casual" feature.

It's true that someone *might* have a JS library from a free CDN already cached on their machine, but if not their response times can leave a lot to be desired. By far the most performant solution is to serve your concatenated, minified JS through a commercial CDN.

**Comment by markbaird** [comment]
Concatenation is [no longer preferred](https://blog.cloudflare.com/http-2-for-web-developers/) if your server or CDN supports HTTP/2. Personally I change all my libraries to point to [CDNJS](https://cdnjs.com/) which is hosted by CloudFlare, the same CDN I'm using for my website.
