### ISSUE TITLE
New Media Styling - not backwards compatible

### ISSUE THREAD

**Issue by cchatham** [pencilblue/pencilblue#914]
Hey guys,

I saw that you added the ability to put styling on media using a '/'. However, if you have media tags that do not contain '/' and call MediaService.parseMediaFlag, the whole Article and Page management pages break in the Admin Console. Are we not remaining backwards compatible with this feature?

The specific issue is on line 738 of the MediaService:

        var attrs = parts[1].split(',');

If you do not use the / in your tag, parts 1 is undefined and throws an error when you call split.

Thanks,
Christina

**Comment by brianhyder** [comment]
Thanks for the report @cchatham.  We'll get it fixed and pushed into the next RC for 0.5.0.

**Comment by cchatham** [comment]
Thanks! @brianhyder
