### ISSUE TITLE
Limits

### ISSUE THREAD

**Issue by andrewtheone** [pencilblue/pencilblue#925]
Hey!

I just found this magnificient module, and is interested in using it for my upcoming project.

My project would be an online store with more then 25k products, each product has common details such as (title, sku, original_price, discount_price, vat, weight, description, image_list, reviews, questions, category_list, tag_list) and they can have other attributes such as (size, variation, color, warranty) and according to these attributes the price of the product may change. The category tree consists of more than 200 categories (parent->children), one product may belong to multiple categories and product searches are accesible via category search or tag_list/title/description search and the current site has a traffic of roughly 500-1500k unique visitors a day. The engine which is running on right now is PhalconPHP and MySQL on a Debian server, it has roughly about 15-35ms page generation time (may vary based on load and how much data it needs to dig up). 

My question is, is PencilBlue stable enough for this kind of project and can it handle that much requests and data and data-transformation?

**Comment by brianhyder** [comment]
The short answer is yes.  It is possible to create and query the data structures you describe and serve the data in a reasonable amount of time.  While the platform is not at a 1.x version it is utilized by many people who need web-scale.  A few of those are featured on the website, [pencilblue.org](https://pencilblue.org).  

The extended answer is that with any given project you need to evaluate the strengths of the underlying systems (MongoDB & Redis) to see if similar implementations on such systems have been successful.  In terms of page load time, this depends on how you setup your infrastructure: server(s) size, memory, cpus, etc.  

I would recommend taking a little time to examine the platform by attempting to build a small 1 or 2 page site.  We provide a sample plugin to help developers get started.  We're happy to answer questions here, on twitter, or on Gitter.  We also love feedback: the good, the bad, and the ugly.

Hope that helps!
