### ISSUE TITLE
node process constantly uses 80% of CPU when there is no request at all

### ISSUE THREAD

**Issue by koverg70** [pencilblue/pencilblue#928]
Pencilblue: 0.4.1
OS: Ubuntu 14.10
Node: 4.2.4
Mongodb: 3.2.1

**Comment by brianhyder** [comment]
Can you please provide your configuration?

In addition, would you please try the 0.5.0 branch to see if the issue
still exists?

**Comment by koverg70** [comment]
I am not sure what you mean by configuration. I am running my server on a VM in the cloud. It has 512MB of RAM and 1 core CPU.

![pb_cpu](https://cloud.githubusercontent.com/assets/4959128/12394206/bae2d024-bdfa-11e5-96d1-5f66affe60cb.png)

I will try with 0.5.0 but I need some time.

Thanks again!

**Comment by blakecallens** [comment]
He's referring to your config.js file. It'll show how you're configuring
your environment.

**Comment by brianhyder** [comment]
If you could also provide the log/console output for startup that would be immensely helpful. 
Are you able to access the site or does the server never start?

**Comment by koverg70** [comment]
It starts and works fine. Only the high CPU usage is bothering me. I will also try it on my Windows machine.

My config and log:
[pb.zip](https://github.com/pencilblue/pencilblue/files/94544/pb.zip)

**Comment by brianhyder** [comment]
@koverg70 I took a look at the information you provided.  It doesn't appear to show anything out of the ordinary.  Please let us know if you experience the same issue with 0.5.0.  We'd also be interested in the command you used to start pencilblue

**Comment by koverg70** [comment]
Sorry, but I still could not test with 0.5.0. I got the following error:

Error: The host (localhost:8080) has not been registered with a site. In single site mode, you must use your site root (https://**.***.**).
    at RequestHandlerModule.RequestHandler.onSessionRetrieved (/home/pb/install2/include/http/request_handler.js:780:23)
    at /home/pb/install2/include/http/request_handler.js:554:18
    at /home/pb/install2/include/session/session.js:137:17
    at /home/pb/install2/include/dao/dao.js:143:12
    at /home/pb/install2/include/dao/dao.js:272:17
    at handleCallback (/home/pb/install2/node_modules/mongodb/lib/utils.js:95:12)
    at /home/pb/install2/node_modules/mongodb/lib/cursor.js:590:16
    at handleCallback (/home/pb/install2/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:234:5)
    at setCursorDeadAndNotified (/home/pb/install2/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:424:3)
    at nextFunction (/home/pb/install2/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:541:14)

I should dig into the documentation about registering my site.

**Comment by koverg70** [comment]
Sorry I am OT, but may be related to this problem.
I start Pencilblue with: nohup pbctrl start &
After that I can see three node processes:

pb        6329  6324  0 11:40 pts/2    00:00:00 /bin/sh -c node pencilblue.js > /tmp/shelljs_8338860fbad105307fc1 2>&1
pb        6330  6329  0 11:40 pts/2    00:00:01 node pencilblue.js
pb        6339  6330  0 11:40 pts/2    00:00:02 /usr/bin/nodejs /home/pb/install2/pencilblue.js

What is the right way to stop Pencilblue? Why there is no pbctrl stop?

I suspect that node uses too much memory (see VIRT on the above screenshot), and the system is constantly swapping. That causes the high CPU.

**Comment by brianhyder** [comment]
The CLI is simply a convenience tool for installing the system.  We encourage people to use nodemon when developing ```nodemon pencilblue.js``` and a program like forever ```forever start pencilblue.js``` when in production.  

You see three processes because the cli is running, plus a master process to manage the children, and a third child process that acts as the worker process handling incoming requests.

I would try starting PB without the CLI.  If that doesn't work you can try adjusting the cluster settings in the config.js file.  You can find out more about how to configure the number of processes [here](https://github.com/pencilblue/pencilblue/blob/master/include/config.js#L587)

**Comment by koverg70** [comment]
The process which hooked CPU time was the pbctrl command and it only caused problem on Linux. With forever the issue doesn't occure. 

Thanks for your help!
