### ISSUE TITLE
In Single Site Mode only Managing Editors and Administrators can be created

### ISSUE THREAD

**Issue by brianhyder** [pencilblue/pencilblue#930]
As an administrator in single site mode I only have the option to create users as an administrator or managing editor.  

Thanks to @purnendu9 for reporting the issue.

It appears that the [UserService](https://github.com/pencilblue/pencilblue/blob/master/include/service/entities/user_service.js#L159) does not take into account that single site mode is activated.  It only performs a check to see that the site is not global.

By my assessment, the check should actually look like:
```if (!pb.config.multisite.enabled || pb.SiteService.isGlobal(this.context.site)) {```

@btidwell Do you guys concur?

**Comment by cchatham** [comment]
We concur.

**Comment by brianhyder** [comment]
Great, I'll make the change this evening and merge it in.
