### ISSUE TITLE
Feature: QuoteBox

### ISSUE THREAD

**Issue by el-sammo** [pencilblue/pencilblue#933]
A feature that should be in the wysiwyg editor, right next to the "Insert Link"-"Insert Media"-"Insert Read More Break" options, is "Insert QuoteBox": the ability to highlight a quote from the story in a stylized div offset with a stylized border.

I'll use the Font Awesome quote-right icon, as shown in the attached screenshot.

I'll implement this feature; it will be my first open source contribution!  Yay for el-sammo!

![quotebox](https://cloud.githubusercontent.com/assets/8061623/12590857/421859ce-c422-11e5-949a-8def06feae58.png)

**Comment by blakecallens** [comment]
Quote is a formatblock in contenteditable divs (the thing that drives wysiwygs), so you'll find the quote block in the dropdown on the left side of the toolbar.

**Comment by el-sammo** [comment]
Blake,

I'm certain that content creators want to affect the positioning and style of a quotebox; refer to this article as an example:

https://www.healthline.com/health-news/debate-heats-up-over-growing-human-tissue-in-farm-animals-012116

I've already finished creating the modal, directive, etc - it's almost done - do you really want to kill this feature?

**Comment by blakecallens** [comment]
@el-sammo the quote tag is it's own HTML node, which is why it's one of the formatblock options. The CSS of a theme can style a quote box. Adding classes to the quote box can offer multiple layouts. It doesn't have to be something built into the wysiwyg.

We designed PencilBlue to be extendable via plugins, and we welcome your addition as an installable extension. We will not be adding it as a core feature, though.

**Comment by el-sammo** [comment]
@blakecallens  Perhaps I'm not familiar enough with the wysiwyg editor, but I didn't see any way for a non-tech-savvy content creator to add a class to a quote - it appears to be predefined; how would a non-tech user define the width, position and border color of a quotebox?

**Comment by blakecallens** [comment]
@el-sammo we don't add any point and click custom styling functionality to the wysiwyg. That's why that type of feature should be a plugin.
