### ISSUE TITLE
errased option from navigation map and now page doesnt work

### ISSUE THREAD

**Issue by KarlaRomero** [pencilblue/pencilblue#934]
TypeError: Cannot read property 'active' of null
    at /var/lib/openshift/55eee0cf2d527157e9000010/app-root/runtime/repo/include/service/entities/section_service.js:207:38
    at /var/lib/openshift/55eee0cf2d527157e9000010/app-root/runtime/repo/include/dao/dao.js:277:9
    at /var/lib/openshift/55eee0cf2d527157e9000010/app-root/runtime/repo/node_modules/mongodb/lib/mongodb/cursor.js:172:16
    at commandHandler (/var/lib/openshift/55eee0cf2d527157e9000010/app-root/runtime/repo/node_modules/mongodb/lib/mongodb/cursor.js:720:16)
    at b (domain.js:183:18)
    at /var/lib/openshift/55eee0cf2d527157e9000010/app-root/runtime/repo/node_modules/mongodb/lib/mongodb/db.js:1874:9
    at b (domain.js:183:18)
    at Server.Base._callHandler (/var/lib/openshift/55eee0cf2d527157e9000010/app-root/runtime/repo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /var/lib/openshift/55eee0cf2d527157e9000010/app-root/runtime/repo/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
    at MongoReply.parseBody (/var/lib/openshift/55eee0cf2d527157e9000010/app-root/runtime/repo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)

**Comment by brianhyder** [comment]
@KarlaRomero We need a bit more information:
* version of PB
* Steps to reproduce

**Comment by KarlaRomero** [comment]
Hello, just letting you know the page is now working fine. Thanks for
replying.

On Sat, Jan 30, 2016 at 4:01 PM, Brian <notifications@github.com> wrote:

> @KarlaRomero <https://github.com/KarlaRomero> We need a bit more
> information:
>
>    - version of PB
>    - Steps to reproduce
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/934#issuecomment-177316101>
> .
>



-- 
Karla Romero  |  Talent Management Specialist/ Training Coordinator
kromero@itexico.com
HQ: 4807 Spicewood Springs Rd, Building 2, Suite 220.  |  Austin TX 78759
Delivery Center: Lopez Mateos Sur 2077-Z9.  |  Guadalajara MX
Phone:  +1 (512) 535 1650 <+15125351650>  |  +52 (33) 3030 6 <+523330307222>
922  |   karlaromero_itexico
[image: iTexico] <http://www.itexico.com/>   [image: Twitter]
<https://twitter.com/itexico> [image: Facebook]
<https://www.facebook.com/itexico> [image: LinkedIn]
<https://www.linkedin.com/company/itexico> [image: Google Plus]
<https://plus.google.com/+itexico>

2015 Rank *#188*
[image: Inc 500 recognition]
