### ISSUE TITLE
Error in link "Read more"

### ISSUE THREAD

**Issue by mapeveri** [pencilblue/pencilblue#941]
In the admin, in the section "PencilBlue News:" the link "Read more" has this url:

"http://pencilblue.orghttps//pencilblue.org/es-ES/article/technical-highlights-of-0-5-0"
 
And obviously this not found.

The feed https://pencilblue.org/feed in the tag <link> is wrong the url.

![image](https://cloud.githubusercontent.com/assets/6276555/12924375/758b0be6-cf38-11e5-9fb2-8a8112101b67.png)

**Comment by brianhyder** [comment]
Thank you for reporting!
