### ISSUE TITLE
AnalyticsManager does not respect site

### ISSUE THREAD

**Issue by cchatham** [pencilblue/pencilblue#945]
This is not a high priority issue because it is not impacting functionality. 

If you install the GA plugin on a site specific level, every site hits GoogleAnalytics.onRequest method. This is okay since there is error handling around not having the settings, but it clutters the logs with warnings.

I found the issue with the AnalyticsManager not respecting site and I will fix, but if there is a specific solution you want to implement, let me know soon. I will resolve it that way. :)

**Comment by brianhyder** [comment]
Thanks, @cchatham!  

```
//constructor to take required options object with site property
function AnalyticsManager(options) {
  this.site = options.site;
}

//optional site parameter - in implementation check if site is function.  If yes, onPageRendering=site;site=global
AnalyticsManager.registerProvider = function(name, site, onPageRendering)

//optional site parameter - defaults to global
AnalyticsManager.unregisterProvider = function(name, site)

//optional site parameter - defaults to global
AnalyticsManager.isRegistered = function(name, site)

//optional options argument - when options is a function: cb=options; options = {site: global}
AnalyticsManager.onPageRender = function(req, session, ls, options, cb)
```

Then the base controller will need to be updated to account for the change to onPageRender.

let me know if you have any questions and thank you!

**Comment by cchatham** [comment]
Pull requested a fix to master (do I need to do another branch?)

Let me know what you think.

**Comment by brianhyder** [comment]
My comments are on the PR.  The master branch is fine since it is a hotfix for analytics.
