### ISSUE TITLE
Create a reaper to remove aging documents in the unverified user collection

### ISSUE THREAD

**Issue by blakecallens** [pencilblue/pencilblue#95]
This was the second half of enhancement #6 but should be it's own enhancement

**Comment by brianhyder** [comment]
We need to add a new index to ```include/config.js``` db index section to timeout after 30 days. The ```created``` field should be the source of expiry.

**Comment by JahlomP** [comment]
Why this feature? Whats the purpose?

**Comment by brianhyder** [comment]
When users are added to the system they are unverified. This means that
they have not confirmed their accounts. The user details sit in a different
collection. Over time this collection will accumulate users that never
activated their account. They should be removed to ensure that we aren't
taking up space with data that isn't needed.

**Comment by JahlomP** [comment]
I've  implemented something, but I used the user collection. Can you please verify and comment?

**Comment by brianhyder** [comment]
See the following resources:

* http://docs.mongodb.org/manual/tutorial/expire-data/
* https://github.com/pencilblue/pencilblue/blob/master/include/system/registry/mongo_registration_provider.js#L88

You will also need to change the collection to ```unverified_user```
