### ISSUE TITLE
Heroku Deployment Mongodb socket closed issue

### ISSUE THREAD

**Issue by sachingill** [pencilblue/pencilblue#953]
Hi ,
I tried deploying pencil blue on Heroku and I faced this issue. I followed steps metioned  at "https://github.com/pencilblue/pencilblue/wiki/Cloud-Hosting:-Heroku-and-Compose"  :

2016-02-28T17:04:56.775572+00:00 app[web.1]: 2016-02-28T17:04:56.775Z - error: [
28] System[28]: uncaught Exception detected : Error: MongoError: server aws-eu-w
est-1-portal.0.dblayer.com:11266 sockets closed - mongodb://{awsurl}/penciltest?
2016-02-28T17:04:56.775609+00:00 app[web.1]: Is your instance running?
2016-02-28T17:04:56.775611+00:00 app[web.1]:     at /app/include/dao/db_manager.
js:113:31
2016-02-28T17:04:56.775612+00:00 app[web.1]:     at /app/node_modules/mongodb/li
b/mongo_client.js:236:20

Please help

**Comment by blakecallens** [comment]
Can you share your config.js (without passwords, of course)?

**Comment by sachingill** [comment]
/**
 * This is a sample configuration meant to get users and up running on a local 
 * machine.  The configuration will not support multi-process on a single 
 * server or multi-server/elastic environments.  For more detailed information 
 * on the options provided please refer to the /include/config.js file.
 * 
 * The file can be renamed to "config.js" in the same directory as this file 
 * and it will be used as the configuration when PencilBlue is started.  If 
 * this file is used then there is no need to create a "config.json"
 */
```json
module.exports = {
    "siteName": "blogapps",
    "siteRoot": "http://localhost:8080",
    "logging": {
        "level": "info"
    },
    "db": {
        "type": "mongo",
        "servers": [
            "mongodb://aws-eu-west-1-portal.0.dblayer.com:11266/"
        ],
        "name": "penciltest",
        "authentication": {
            "un": "",
            "pw": ""
        },
        "writeConcern": 1
    },
    "cache": {
        "fake": true,
        "host": "localhost",
        "port": 6379
    },
    "settings": {
        "use_memory": false,
        "use_cache": false
    },
    "templates": {
        "use_memory": true,
        "use_cache": false
    },
    "plugins": {
        "caching": {
            "use_memory": false,
            "use_cache": false
        }
    },
    "registry": {
        "type": "mongo"
    },
    "session": {
        "storage": "mongo"
    },
    "media": {
        "provider": "mongo",
        "max_upload_size": 6291456
    },
    "cluster": {
        "workers": 1,
        "self_managed": true
    },
    "multisite": {
        "enabled": false,
        "globalRoot": "http://global.localhost:8080"
    },
    "siteIP": "127.0.0.1"
};
```

**Comment by blakecallens** [comment]
It looks like that MongoDB instance isn't listening. Can you hit it with the *mongo* CLI when SSH'd into your server?

**Comment by sachingill** [comment]
I was able to ping it using cli. Also raised this issue with compose and
they said it's a code issue. I'll try again and let you know. Can i try
this with mongolab instead of compose?

**Comment by brianhyder** [comment]
Just to be sure, what version of mongo are you using?  PB uses the 2.x driver and is not guaranteed to work with MongoDB V3.x

**Comment by sachingill** [comment]
Hi,
The Mongo DB version is: 3.2.1

**Comment by blakecallens** [comment]
> server aws-eu-west-1-portal.0.dblayer.com:11266 **sockets closed**

It's unlikely that it's either a MongoDB version or PB code issue. You'd have to be able to hit the Mongo server before either would fail.

Try changing the URL to ```mongodb://aws-eu-west-1-portal.0.dblayer.com:11266/penciltest/```
