### ISSUE TITLE
Url generator generates invalid URL when using colon in article title

### ISSUE THREAD

**Issue by eric-burel** [pencilblue/pencilblue#955]
Hi, 

When the title of an article includes a colon, the generated URL does not delete the colon.
For exemple an article title such as "Pencilblue : A CMS" would generate automatically "pencilblue-:-a-cms" as the article URL, which is invalid and leads to a 404 when we click on "Read more".

I am trying to figure out which file handles this generation to correct that.

**Comment by blakecallens** [comment]
Thanks for the catch. I'll put in a fix soon.

**Comment by noogen** [comment]
FYI - it's just just colon.  Another common one that I ran into is the single quote character.  Maybe it need to go through some kind of slugify?

**Comment by brianhyder** [comment]
@blakecallens I'd like to release 0.5.1 next week.  Any chance you could squeeze this in?

**Comment by blakecallens** [comment]
Addded a URL safe regex to the generateUrl function.
