### ISSUE TITLE
Pencil blue tries to access a wrong port number?

### ISSUE THREAD

**Issue by JohnLi2012** [pencilblue/pencilblue#956]
I am trying to spin up pencil blue on cloud9. I update the site root to my cloud9 site url, and i can see the setup page. However, after i put in my info, and hit submit, it throws ECONNRESET: Request could not be proxied! error. 

On the server side, i could see it errors out at below point
![image](https://cloud.githubusercontent.com/assets/3833946/13480350/3c9dc5f6-e0ab-11e5-8041-0b45538a6e53.png)

it seems that pencil blue tries to access url with a wrong port number(pen-johnlizenith.c9users.io:80). I am very new with pencilblue, anyone could advise me where to modify or what i did wrong?

**Comment by JohnLi2012** [comment]
BTW, my installation steps are exactly same as this post below,
http://blog.rubypdf.com/2015/10/22/how-to-install-pencilblue-on-cloud9/
However, i can not get into admin portal.

**Comment by blakecallens** [comment]
It looks like you've incorrectly set your siteRoot set it to https://pen-johnlizenith.cyusers.io

**Comment by JohnLi2012** [comment]
@blakecallens https://pen-johnlizenith.c9users.io is the site root. I am not running it on localhost but on web ide cloud9 platform. As i said earlier, i can see the setup page
![image](https://cloud.githubusercontent.com/assets/3833946/13512737/7ca91082-e16a-11e5-9aeb-94f1c93b04bc.png)
but after submission, it errors out where above screen shot shows. Any idea?

**Comment by JohnLi2012** [comment]
`module.exports = {
    "siteName": "pen",
    "siteRoot": "https://pen-johnlizenith.c9users.io",
    "sitePort": 8080,
    "logging": {
        "level": "info"
    },
    "db": {
        "type": "mongo",
        "servers": [
            "mongodb://127.0.0.1:27017/"
        ],
        "name": "pencilblue",
        "writeConcern": 1
    },
    "cache": {
        "fake": false,
        "host": "localhost",
        "port": 6379
    },
    "settings": {
        "use_memory": false,
        "use_cache": false
    },
    "templates": {
        "use_memory": true,
        "use_cache": false
    },
    "plugins": {
        "caching": {
            "use_memory": false,
            "use_cache": false
        }
    },
    "registry": {
        "type": "mongo"
    },
    "session": {
        "storage": "mongo"
    },
    "media": {
        "provider": "mongo",
        "max_upload_size": 6291456
    },
    "cluster": {
        "workers": 1,
        "self_managed": true
    },
    "multisite": {
        "enabled": false,
        "globalRoot": "https://pen-johnlizenith.c9users.io"
    },
    "siteIP": "0.0.0.0"
};`

**Comment by JohnLi2012** [comment]
module.exports = {
    "siteName": "pen",
    "siteRoot": "https://pen-johnlizenith.c9users.io",
    "sitePort": 8080,
    "logging": {
        "level": "info"
    },
    "db": {
        "type": "mongo",
        "servers": [
            "mongodb://127.0.0.1:27017/"
        ],
        "name": "pencilblue",
        "writeConcern": 1
    },
    "cache": {
        "fake": false,
        "host": "localhost",
        "port": 6379
    },
    "settings": {
        "use_memory": false,
        "use_cache": false
    },
    "templates": {
        "use_memory": true,
        "use_cache": false
    },
    "plugins": {
        "caching": {
            "use_memory": false,
            "use_cache": false
        }
    },
    "registry": {
        "type": "mongo"
    },
    "session": {
        "storage": "mongo"
    },
    "media": {
        "provider": "mongo",
        "max_upload_size": 6291456
    },
    "cluster": {
        "workers": 1,
        "self_managed": true
    },
    "multisite": {
        "enabled": false,
        "globalRoot": "https://pen-johnlizenith.c9users.io"
    },
    "siteIP": "0.0.0.0"
};

**Comment by blakecallens** [comment]
You're running your site on port 8080, so your site root should be https://pen-johnlizenith.c9users.io:8080

**Comment by JohnLi2012** [comment]
still doesnt work. errored out at the same place. ) :

**Comment by blakecallens** [comment]
Well then... try changing your sitePort to 80 and changing your siteRoot back to https://pen-johnlizenith.c9users.io

Maybe cloud9 is forcing you to port 80.

**Comment by JohnLi2012** [comment]
ok. i got it working now. The app runs on c9 need to listen to either 8080 8081 or 8082  see below
![image](https://cloud.githubusercontent.com/assets/3833946/13535033/1010f6be-e206-11e5-86d9-b8dd428e2a31.png)
by default, it listens to 8080. I just happened to try port 8081, and make siteroot:https://pen-johnlizenith.c9users.io:8081 and it just worked. Dont know why 8080 wouldnt work, but anyway thank for your help blake. 
This thread could be valuable for anyone who tries to run PencilBlue on Cloud9 ( :

**Comment by blakecallens** [comment]
Glad it's working! BTW, looking at that info from cloud9, I think you should change your config.js if you don't want to have the port in the URL.

```Javascript
"siteRoot": "https://pen-johnlizenith.c9users.io",
"sitePort": process.env.PORT,
"siteIP": process.env.IP
```

That should fix everything.

**Comment by brianhyder** [comment]
For those that come back to this post looking for answers.  Here is a base config that worked as of the posting of this comment:

```
module.exports = {
  siteRoot: "https://workspace-user.c9users.io:8081",
  sitePort: 8081,
  db: {
      name: "pencilblue",
      servers: [
        "some.mongo.server:74829"    
      ],
      authentication: {
          un: "someuser",
          pw: "somepassword"
      }
  },
  server: {
      ssl: {
          enabled: false,
          use_x_forwarded_for: false
      }
  },
  cluster: {
      self_managed: false
  }
};
```

Using the environment variables does not currently work with PB (0.5.0) because they must be included in the siteRoot.  The port will be necessary to include in your site root.
