### ISSUE TITLE
Using just in time compilation using gulp

### ISSUE THREAD

**Issue by JSinghDev** [pencilblue/pencilblue#957]
Is there a way for using JIT compilation & browser reloading(ex: using browser sync) using gulp for sass in plugin templates?

**Comment by blakecallens** [comment]
You don't have to do browser sync, since PB does its own serving.

I use gulp for LESS when building themes, so it's definitely possible. I just put a gulpfile inside the theme plugin and run it from inside that folder. I have the LESS compile to the theme's public/css folder.

**Comment by larskarbo** [comment]
I'm just curious, why aren't there any gulp or grunt files on the public plugins for pencilblue?

**Comment by brianhyder** [comment]
We created the pencilblue theme before we started to integrate gulp.  @blakecallens is working on a UI update that leverages these capabilities.
