### ISSUE TITLE
Deploying Multi Tenancy on a vm with domain name configured with it

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#968]
Hi, I want to deploy pencilblue with Multi Tenancy enabled on a vm. I have also configure a domain name to the vm so going to global.example.com is not working. What is the trick?

**Comment by brianhyder** [comment]
If you are running a VM on your local machine then you _probably_ want to also configure the hosts file on your local machine not just your VM.  This is something that I have tried before.

**Comment by JahlomP** [comment]
Can you share sample of your config with me or how you went about it?

**Comment by brianhyder** [comment]
We haven't attempted to run multi-site in a VM before.  The configuration on your VM would be no different than running multi-site on your host OS.

**Comment by JahlomP** [comment]
OK
