### ISSUE TITLE
Custom Sanatization Filter

### ISSUE THREAD

**Issue by jeff8bitrocket** [pencilblue/pencilblue#977]
I need to create pages that have links to named anchors in the WYSIWYG editor (so the user can later edit them). I could make this a custom page theme, but that will not allow the user to edit page. 
What is the best way to create a sanitization filter to omit the name divs for anchor links?

Thanks!

Forget the one by Momentage, I should not have been logged in as their account when I sent that.

**Comment by blakecallens** [comment]
@brianhyder it looks like name attributes are not being sanitized, but id attributes are. IMO we should allow id in default sanitization.

**Comment by brianhyder** [comment]
@jeff8bitrocket if you'd like to submit a PR to add in the exceptions I'd be happy to merge that in.  Just submit it against the 0.6.0 branch.

**Comment by jeff8bitrocket** [comment]
Interesting. I think It is ok, I think it is cool as is. I  Think the mark-up in the WYSIZWYG editor should be as clean as possible. That forces use to write a custom themes/Plugins for those articles that need it. 

That is better. In the long run.   What I could use is a simple example of reading the data from the database and using it (custom data).   I have been the tutorial on storing the contact lists, but there was never a follow up on reading it. 

I’m sure I can look at the controller for the base header.js to see how to read regular CMS data (the nav data for example), but I’m not sure how the custom data is stored or  retrieved.

**Comment by brianhyder** [comment]
If you are using custom objects then you will want to take a look at creating an instance of ```CustomObjectService```.  You can find the documentation for it [here](http://pencilblue.github.io/classes/CustomObjectService.html).

The code to to retrieve a single object would look something like this (NOTE: not guaranteed to be exact):
```
var cos = new pb.CustomObjectService(siteUidStr, onlySearchTheSpecifiedSiteBool);

//fetch depth indicates how deep to join other objects
cos.loadById(vars.id, {fetch_depth: 1}, function(err, custObj) {
  //continue on here
});
```

The code to query would look something like:
```
var cos = new pb.CustomObjectService(siteUidStr, onlySearchTheSpecifiedSiteBool);

cos.loadTypeByName('contact', function(err, typeObj) {
  //do error handling here

  //build options for mongo query
  var options = {
    where: {},
    select: {},
    order: {}, //etc http://pencilblue.github.io/classes/DAO.html#method_q
  };
  cos.findByType(typeObj, options, function(err, customObjsArray) {
    //do error handling here

    //continue on
  });
});
```
